### ISSUE TITLE
noDataMessage not showing in 0.3.16

### ISSUE THREAD

**Issue by denov** [SitePen/dgrid#1001]
Everything was great before updating to 0.3.16 from 0.3.4.  No I'm not sure about the the refresh function in _StoreMixin.js.  This seems to break things. I poked around but not sure where logic to get the count of records from the query.

**Comment by kfranqueiro** [comment]
Given no further response and our inability to reproduce, I'm closing this issue.  If you can provide more information on the server response in your problem's case, it should help determine whether there is any issue on dgrid's end.
