### ISSUE TITLE
Changing query engine of Memory Store breaks Pagination extension and sort function of grid 

### ISSUE THREAD

**Issue by lisasroughdrafts** [SitePen/dgrid#1004]
After changing the query engine for my Memory store from it's default value to the rql engine, my dgrid is no longer sortable and the Pagination is broken.  I am using "rql/js-array" which is a javascript implementation of RQL for javascript arrays.

define([
    "dojo/_base/declare",
    "dojo/_base/lang",
    "dojo/_base/array",
    "dojo/json",
    "dojo/request/script",
    "dojo/store/Memory",
    "dojo/dom",
    "dojo/dom-construct",
    "dojo/dom-style",
    "dgrid/Grid",
    "dgrid/extensions/Pagination",
    "dojo/i18n!app/nls/swapResources",
    "rql/js-array"
], function(declare, lang, array, JSON, script, Memory, dom, domConstruct, domStyle, Grid, Pagination, resourceBundle,rql) {
  var CustomGrid = declare([Grid, Pagination ]);
            var gridStore = new Memory({ idProperty: 'tsn', data: null });

            //For using RQL
            gridStore.queryEngine = rql.query;
           
            try {
                this._grid = new CustomGrid({
                        store: gridStore,
                    noDataMessage: "",
                    columns:
                            [
                            { field: "tsn", label: "TSN #"},
                            { field: "scientificName", label: "Scientific Name"},
                            { field: "commonName", label: "Common Name",},
                            { id:"numStates2005", field: "numStates2005", label: "# of States 2005"},
                            { id:"numStates2015", field: "numStates2015", label: "# of States 2015",
                                    renderHeaderCell: function(node) {
                                        //Create a tooltip inside of the header cell to the right of the text.  Use the Bootstrap
                                        //class glyphicon-info-sign for the icon.
                                        domConstruct.create("div", {innerHTML: this.label + "  "}, node);
                                    }
                                },
                            { field: "taxaGroup", label: "Taxonomic Group"},
                            ],
                    loadingMessage: "Loading data...",
                    noDataMessage: "Loading data...",
                    autoHeight: 'true',
                    firstLastArrows: 'true',
                    rowsPerPage: 25,
                    pageSizeOptions: [50, 100],
                    showLoadingMessage: 'true'
                }, id);

 Thanks in advance for any help you can provide.

**Comment by edhager** [comment]
Hi @lisasroughdrafts,

dgrid with the pagination extension passes the page length, the starting item number and the sort parameters in the `options` parameter of the store's `query` method.  In RQL, those parameters have to be passed in the query string as calls to the `limit` and `sort` operators.  In your testing, you should notice that the first page is actually showing all of the items from your store.  

You could write a query engine adapter that converts the `options` parameter dgrid creates into an RQL query string before passing it to the RQL query engine.

**Comment by kfranqueiro** [comment]
Given no further response, we're closing this issue.  If you still have questions in this area, it'd be a good idea to [ask for support](https://github.com/SitePen/dgrid#getting-support) on the mailing list, IRC, or SO.
