### ISSUE TITLE
Hiding disabled vertical scroll bar causing column resize issue

### ISSUE THREAD

**Issue by SrikanthDesu** [SitePen/dgrid#1008]
Hi,

We are using "overflow-y: auto" for the class ".dgrid-scroller" to hide disabled vertical scroll bar in dgrid.
The disabled scroll bar issue is fixed but when we resize the last column in the dgrid, it is partial hiding in the portion of hidden scroll bar.

Could you please help in fixing this issue?

Regards,
Srikanth.

**Comment by kfranqueiro** [comment]
Even if you hide the scrollbar, there is also an element with the class `dgrid-header-scroll` which typically occupies the top-right corner of the grid, to align with the scrollbar.  That's ending up covering the end of the final column, so you would probably want to hide that too.

It might help to look at the styles for `dgrid-autoheight` (which is a class you can apply for auto-height grids) for reference: https://github.com/SitePen/dgrid/blob/v0.4.0/css/dgrid.css#L182-L195
