### ISSUE TITLE
Set columns fails

### ISSUE THREAD

**Issue by IsraelLopezM** [SitePen/dgrid#1010]
I try to change dgrid's structure based of a query. I can make query but if query returns empty and try to change columns then an error occurs with parentNode is null

Same error is try to set a new store

I am using dojo store jsonrest 

Some example
var columns;
		    	
		    	if(tipo==1){
		    		 columns = [{field: "nombre",label: "Nombre"}];
		    	}else if(tipo==2){
		    		 columns = [{field: "form",label: "Nombre"}];
		    	}else{
		    		 columns = [{field: "test",label: "Nombre"}];
		    		
		    	}

 		var objgridCat=Registro.byId("grid_admin");
 		
	 		if(objgridCat!=null){

	 			//Filtrar los elementos necesarios
	 			objgridCat.set("query",{id_tipo:tipo,id_nivel:nivel})
	 			objgridCat.set("columns", columns); 				
	 		}else{
	 				//Crear objeto desde cero
	 				var SM=new StoreMemory();
    				var storeCat = StoreCache(JsonRest({target:"info_grid_admin.php/",sortParam:"sort",idProperty:"id"}), SM);
    				
    				
	 				objgridCat = Declaracion([Grid, GridSel,GridExt])({
	        		selectionMode: "single",
	        		store:storeCat,
	      		 	columns: columns,
	      		 	query:{id_tipo:tipo,id_nivel:nivel},
	      		 	noDataMessage:"<div class='nodatos'>No existen registros.</div>"
	    	}, "grid_admin");
	    	
	    	
	    		 objgridCat.startup();

**Comment by edhager** [comment]
Hi @IsraelLopezM,

In your code, which module corresponds to "GridExt"?

**Comment by kfranqueiro** [comment]
Given no further information, we're closing this issue.  If you are still experiencing this problem, it would be helpful to provide a reduced test case that can reproduce the issue.  Thanks!
