### ISSUE TITLE
Both deselect and select events are fired with extended selection mode

### ISSUE THREAD

**Issue by savola28** [SitePen/dgrid#1011]
If selection mode is extended and I click row that is already selected row stays selected like it should be. However I noticed that both deselect and select events are fired for that row. This is because _extendedSelectionHandler first clears selection and then calls _multipleSelectionHandler which reselects the row. Is this a bug or a feature?

**Comment by gerpres** [comment]
any plans to tackle this issue?

**Comment by fkranenburg** [comment]
Please fix this.
