### ISSUE TITLE
ColumnResizer and subRows

### ISSUE THREAD

**Issue by matejlednar** [SitePen/dgrid#1016]
I have an issues with ColumnResizer and subRows, where second row has colspan.
I get id error if subRows dgrid is used.

My fix.
I had to removed line number 18
//		numCols = subRows[0].length,

and add line number 32
numCols = subRow.length;

Now it works, doesn't crash, dgrid with subRows is resizeable.

**Comment by edhager** [comment]
Hi @matejlednar,

Can you provide a simple test case that demonstrates the problem?

Thanks!

**Comment by kfranqueiro** [comment]
Given no further information, we're closing this issue.  If the problem persists, a reduced test case would be very helpful, as I'm sure there are probably ways we can improve the reliability of ColumnResizer with complex column structures.  Thanks!
