### ISSUE TITLE
Last row hides below the bottom margin after update the value in the store

### ISSUE THREAD

**Issue by bogool** [SitePen/dgrid#1023]
Hi

Here is the problem:
After editing a cell value, the grid scrolls down, and last row hides below the bottom margin of the grid. This happens only when the last row is visible in the viewport.

Here is an working example that illustrates the problem: http://jsfiddle.net/svaq6Ly2/3/
And discussion about workaround: http://dojo-toolkit.33424.n3.nabble.com/Dgrid-last-row-gets-hidden-after-cell-edit-td4004014.html

I figured out why this happens.
In the most cases update of value works this way:
1. Outdated row is removed from the DOM structure
2. This causes that rows lying below moves upward to fill empty space
3. Updated row is inserted on his position
4. Rows below moves down to create space for inserted row.

But if there is no rows below bottom margin - last row is on the screen, the flow looks like this:

1. Outdated row is removed from DOM structure
2. This causes that *rows lying above moves down* to fill empty space
3. Updated row is inserted on his position
4. As previously: rows below moves down to create space for inserted row.

This causes last row slides below the bottom margin.

The above operation is performed in the List.js, in the renderArray method.

Best Regards
bogool

**Comment by kfranqueiro** [comment]
I believe #1148 is reporting the same issue as this (sorry that we haven't gotten around to addressing it yet).  I'm electing to close this and track the issue there, given that it provides an easily-reproducible test case (whereas I think the fiddle in this issue has fallen out of date and can no longer load).
