### ISSUE TITLE
Multiple grids on page. cell and row null onClick

### ISSUE THREAD

**Issue by ielattar** [SitePen/dgrid#1029]
I have multiple grids on the same page with the same column names. I am aware of the dgrid limitations here https://github.com/SitePen/dgrid/wiki/Limitations. I used a seperate getColumns method as recommended but this does not seem to work still

I did create a getColumns function. I still get this null column and cell object when the row or cell are clicked

getColumns: function (fieldAliases) {
var gridColumns = new Array();
for (var key in fieldAliases) {
if (key == "DOCUMENT_LINK" || key == "IMAGE_LINK") {
aGridField = { id: fieldAliases[key], 'label': fieldAliases[key], 'field': fieldAliases[key], 'formatter': this.formatHotlink };
} else {
aGridField = { id: fieldAliases[key], 'label': fieldAliases[key], 'field': fieldAliases[key] };
}
gridColumns.push(aGridField);
}
return gridColumns;
}

**Comment by edhager** [comment]
Hi @ielattar,

You are assigning the exact same thing to your `id`, `label` and `field` properties.  Is that correct? 
```javascript
{
	id: fieldAliases[key],
	'label': fieldAliases[key],
	'field': fieldAliases[key]
}
```
If it is, can you provide some sample code with a grid that demonstrates the problem?

Thanks!

**Comment by kfranqueiro** [comment]
Given no further information, we're closing this issue.  If you're still experiencing the problem, please provide a full reduced test case that we can use to reproduce the issue.  Thanks!
