### ISSUE TITLE
IE8 - onDemandGrid - Issue

### ISSUE THREAD

**Issue by Venkesh** [SitePen/dgrid#1032]
Hi,
I am using onDemandGrid, facing an issue only with IE8.
My dgrid column header and dgrid content is not getting aligned properly.

// I am using following styles
.dgrid-header {
	background-color: #C0C0C0;
	background: -moz-linear-gradient(top, #FEFEFE, #BCBCBB);
	background: -webkit-gradient(linear, left top, left bottom, from(#FEFEFE),
		to(#BCBCBB) );
	filter: progid : DXImageTransform.Microsoft.gradient ( startColorstr =
		#FFFEFEFE, endColorstr = #FFBCBCBB );
}

.dgrid-header .dgrid-cell {
	border: 1px solid #dddddd;
	border-top-style: none;
	border-bottom-style: none;
	box-sizing: border-box;
	-moz-box-sizing: border-box;
	-ms-box-sizing: border-box;
	-webkit-box-sizing: border-box;
	white-space: normal;
	word-wrap: break-word;
}

.dgrid-header .dgrid-cell:hover {
	background: #d0d0d0;
}

.dgrid-row-table {
	font-size: 11px;
	background-image: none;
}

.dgrid-row {
	background-color: #ffffff;
}

.dgrid-row .dgrid-row-table .dgrid-cell {
	
}

.dgrid-cell {
	text-overflow: ellipsis;
	white-space: nowrap;
	word-wrap: normal;
}

.dgrid-selected {
	background-image: none;
	background-color: #d0d0d0;
	border-top: 1px solid #d0d0d0;
	border-bottom: 1px solid #d0d0d0;
}

.dgrid-row:hover {
	background-color: #C0C0C0;
	background-image: none;
	border-right: 1px solid transparent;
	filter: alpha(opacity = 50);
	opacity: 0.5;
	-moz-opacity: 0.5;
}

.dgrid-row-odd {
	background-color: #FFF8E8;
}

.dgrid-focus {
	outline: none;
}

.dgrid a {
	color: #333333;
}

.dgrid a:hover {
	color: #666666;
}

.dgrid-header-scroll {
	background-color: #C0C0C0;
	background: -moz-linear-gradient(top, #FEFEFE, #BCBCBB);
	background: -webkit-gradient(linear, left top, left bottom, from(#FEFEFE),
		to(#BCBCBB) );
	filter: progid : DXImageTransform.Microsoft.gradient ( startColorstr =
		#FFFEFEFE, endColorstr = #FFBCBCBB );
}

.dgrid-header-scroll:hover {
	background: #d0d0d0;
}

.dgrid-header-scroll .ui-icon {
	background-image: none;
}

.claro .dojoDndItemOver {
	background-repeat: no-repeat;
	background-image: none;
	padding: 3px;
}

.dgrid-no-data,.dgrid-loading {
	text-align: center;
	padding: 16px;
}

.dgrid-content .dgrid-cell {
	border-color: transparent;
}

![ie8-ondemandgrid-alignment-issue](https://cloud.githubusercontent.com/assets/3873678/4897451/584fc628-6406-11e4-9a40-eeb90dd05f65.jpg)

**Comment by kfranqueiro** [comment]
I wasn't able to reproduce what your image displays, using the CSS you provided and data as close to what's displayed in your image as I could easily match.

The one thing I can suggest off the top of my head is to give each of your columns widths via CSS, which may resolve your issue.  This can be done most easily via the `.field-<fieldname>` classes (for example, assuming the CCY column refers to a `ccy` item property, `.field-ccy { width: 5em; }`).

If you continue to have problems with your code, please use one of the [recommended support channels](https://github.com/SitePen/dgrid#getting-support) and provide enough code to reproduce the issue.
