### ISSUE TITLE
I have a dGrid with 2 columns Col(x) and Col(y) on click of grid header of Col(y) I want to sort asc/desc Col(x)

### ISSUE THREAD

**Issue by itsjayraj** [SitePen/dgrid#1045]
I have a dGrid with 2 columns Col(x) and Col(y) on click of grid header of Col(y) I want to sort asc/desc Col(x). Or on click of Col(y) header I want sort a hidden column. How can I do this ?

**Comment by edhager** [comment]
Hi @itsjayraj,

You can change the sorting by setting your grid's "sort" property.  Here is an example that may help you:
```html
<!DOCTYPE html>
<html>
<head>
	<style>
		.dgrid {
			width: 600px;
		}
	</style>
</head>
<body>
<div id="grid"></div>
<script src='../dojo/dojo.js' data-dojo-config='async: true'></script>
<script>
require(['dojo/store/Memory', 'dgrid/OnDemandGrid', 'dojo/query'
], function (Memory, OnDemandGrid) {

	var store = new Memory({
		data: [
			{ id: 1, name: 'Ed', age: 47 },
			{ id: 2, name: 'Mike', age: 15 },
			{ id: 3, name: 'Joe', age: 12 }
		]
	});

	var grid = new OnDemandGrid({
		store: store,
		columns: [
			{label: 'ID', field: 'id', sortable: false, customSortOn: 'name'},
			{label: 'Name', field: 'name', sortable: false, customSortOn: 'age'}
		]
	}, 'grid');

	grid.on('.dgrid-header .dgrid-cell:click', function (event) {
		var column = grid.column(event);
		if (column.customSortOn) {
			grid.set('sort', column.customSortOn, false);
		}
	});
});
</script>
</body>
</html>
```
Here are some things I did:
* Set `sortable` to `false` in the column definitions to turn off the default sorting.
* Added a custom property to each column definition to indicate when a column's header is clicked, which field should be sorted.
* Used event delegation to create an event handler for all clicks on the grid's header cells.  The event handler modifies the grid's sort property based on the column's `customSortOn` property.

Notice in the example above, I am sorting on age when there isn't a column defined for age.

I hope this helps solve your problem.

**Comment by itsjayraj** [comment]
Hi Ed
I got the customesort ON and there u go I could now sort on a hidden col.. thanks for the help with super clear example code.

Jay
