### ISSUE TITLE
dstore/Rest error using dgrid/Grid

### ISSUE THREAD

**Issue by lbonhomme** [SitePen/dgrid#1055]
I have some troubles using dstore/Rest with dgrid/Grid

The following code works perfectly; my server sends JSON data which are well displayed and paginated :

require([
         'dojo/_base/declare',
         'dstore/RequestMemory',
         'dgrid/Grid',
         'dgrid/extensions/Pagination'
     ], function (declare, RequestMemory, Grid, Pagination) {
         var grid = new (declare([ Grid, Pagination ]))({
             collection: new RequestMemory({ target: '/restful/' }),
             columns: {
                 id: 'Id',
                 name: 'Name',
                 comment: 'Cmt'
             }  
         }, 'grid'); 
         grid.startup();
});

However, if I try to use dstore/Rest insead of dstore/RequestMemory, I get an error : 

 'TypeError: transform(...) is null' at http://opeweb.local/js/src/dojo/promise/instrumentation.js line 20

require([
         'dojo/_base/declare',
         'dstore/Rest',
         'dgrid/Grid',
         'dgrid/extensions/Pagination'
     ], function (declare, Rest, Grid, Pagination) {
         var grid = new (declare([ Grid, Pagination ]))({
             collection: new Rest({ target: '/restful/' }),
             columns: {
                 id: 'Id',
                 name: 'Name',
                 comment: 'Cmt'
             }  
         }, 'grid'); 
         grid.startup();
});

What am I doing wrong?
I really need to do some 'on demand' Rest because I have too many data to be put in memor at once.

Thanks for your help

**Comment by heathernicoale** [comment]
@lbinhomme - HOW exactly did you fix this error? I've been getting the same thing and have a similar setup. I'm also working with a very large data store and using Request Memory is not an option. 
You're the only one I can find who's had this same issue. 

Thanks!

**Comment by kfranqueiro** [comment]
If total is being reported as `null`, then your server is not reporting `total` the way that the store expects.  `dstore/Request` expects a `total` property (i.e. not `count`) if your server responds with an object.

**Comment by heathernicoale** [comment]
I don't think it's the total. That all looks good.  And data is displaying but I'm still getting an error.
