### ISSUE TITLE
How to place paginationNode in the top left and to the bottom left?

### ISSUE THREAD

**Issue by igilfanov** [SitePen/dgrid#1057]
How to place paginationNode in the top left and to the bottom left?

https://drive.google.com/file/d/0B3COHhlYWf-7eUpBUE1IZXFLeE0/view?usp=sharing

**Comment by kfranqueiro** [comment]
This is effectively a variant/subset of #629 and #211 which are open, so I'm closing this as a duplicate.  We're definitely interested in eventually making the layout more customizable.
