### ISSUE TITLE
Remove auto pulling of CSS from x-style

### ISSUE THREAD

**Issue by gaurav21r** [SitePen/dgrid#1072]
Subsequent to #1070 as mentioned We have a very **LARGE** Enterprise framework in [Dojo](https://github.com/dojo/dojo) / [dGrid](https://github.com/SitePen/dgrid) / [DijitX](https://github.com/rcorp/dijitx) and have large parallel teams working. 

There are a lot of issues where we would not want the JS part of the application to handle certain UI stuff. One fo them is this -> The base `dgrid.css` file is being auto pulled by x-style as given [here](https://github.com/SitePen/dgrid/blob/master/List.js#L9): 

````javascript
define([
	'dojo/_base/declare',
	'dojo/on',
	'dojo/has',
	'./util/misc',
	'xstyle/has-class',
	'put-selector/put',
	'dojo/_base/sniff',
	'xstyle/css!./css/dgrid.css'
], function (declare, listen, has, miscUtil, hasClass, put) {
```` 

Now our application has dgrid as a **git submodule**, so we can easily pull in new versions when required. I think this is a very common workflow. Therefore we can't make any changes to `dgrid.css` nor to `List.js`. The solution (for now) is to create another `dgrid.css` and **include** it in our html file and overwrite the CSS we don't want. Or copy & **include** a file from the `skins` folder and do the same.

The architecture seems to resemble that of the **Web Components** Implementation from Polymer (specifically [this](https://www.polymer-project.org/docs/polymer/styling.html#including-stylesheets-in-an-element) ) and Dojo2. But is this ready for primetime? Also, what about the complexities while running a dojo build?

If we have to anyway include a custom CSS file, why not let the user include `dgrid.css` on their own instead of using x-style? Or at least hide it behind an attribute of the `List` Class?

@dylans @SitePenKenFranqueiro I would be grateful if you could share your comments on this Engineering v Design point and any way this can be resolved. Happy to put resources for any contributions required as long as architecture is agreed upon.

**Comment by kfranqueiro** [comment]
I'm not sure I understand the problem you are attempting to describe.  You indeed shouldn't need to modify the base dgrid.css - any overrides or extensions should be in your own CSS, which in turn can import dgrid.css as a base.  dgrid.css includes a selector and rule at the end of the file which signals to xstyle that it is loaded, so if you load it yourself first and something requests it via xstyle later, it won't load it redundantly.

**Comment by mc007** [comment]
i agree with 'gaura', its really annoying that dgrid loads that css (same for extensions), i'd prefer to maintain my own version dgrid.css,.. too. please remove also xstyle from dgrid :-)

**Comment by mc007** [comment]
both are  btw. the main reason i need to work with a fork of dgrid and then i need to strip it always off with each update.

**Comment by gaurav21r** [comment]
@kfranqueiro I am lazy loading my own dgrid.css. x-style is running the moment the JS files are included. My point remains. Why even have dgrid.css auto pulled? Why not let the user decide? @mc007 will be first of many who will agree that this greatly disrupts workflow when updating dGrid.

**Comment by kfranqueiro** [comment]
A workaround for now would be to include [these lines](https://github.com/SitePen/dgrid/blob/v0.4.0/css/dgrid.css#L198-L200) in CSS that is present before dgrid is ever loaded.

I'm not really sure what to say if you're against xstyle, yet are lazy-loading CSS yourself.  Doesn't that mean you're basically "competing" with xstyle?

I will say that I started some investigation out of idle curiosity right before Christmas that may be relevant to your interests, but there's no chance that will land prior to the next major release.

**Comment by gaurav21r** [comment]
@kfranqueiro Thanks for the update. No I'm not really competing with x-style because I'm using a highly popular framework agnostic Lazy loading library to lazy load CSS & JS  & some assets not just CSS.

Can you shed some more light on your investigations? In the spirit of Open Source and the Dojo Foundation I'm sure the community can help out when SitePen is feeling squeezed?

**Comment by mc007** [comment]
@gaurav21r you can use this fork in the mean-time: https://github.com/mc007/dgrid
see https://github.com/mc007/dgrid#attention-this-is-a-fork what the fork does:

all xstyle removed and some goodies for having dgrid/put/dstore precompiled :-)

**Comment by kfranqueiro** [comment]
I've finally finished reviewing/tweaking the code I started in December.  put-selector and xstyle have now been removed in master (you just need to load dgrid.css yourself instead).

I don't plan to institute this in any 0.4.x release since it's kind of a major change, but you're welcome to try working against current master.  This is pretty much the first major change that has been introduced since 0.4 was released.

**Comment by mc007** [comment]
Horray! Thank you, Ken!

**Comment by gaurav21r** [comment]
+100 ! Thank You @kfranqueiro `put-selector` and `x-style` both were dependencies that one *doesn't feel to be right* or in *the spirit of Dojo* if you will! They seemed to introduce an architectural style that differs from one that DTK usually promotes.

I understand your reservations regarding 0.4.x. Do give us an idea of the type of workflows you guys follow. I would assume all future versions would be cut from `master` only?

**Comment by gaurav21r** [comment]
@SitePenKenFranqueiro ? Is this in 0.4 + ?

**Comment by kfranqueiro** [comment]
No.  As I mentioned in my last comment, this is not in 0.4.0 (which was released a month before I started working on this) nor do I plan to do it in 0.4.x because it would be a major change that technically breaks backcompat.

**Comment by gaurav21r** [comment]
@kfranqueiro Could you explain the rationale? I'm a very long term user / contributor to Dojo and with Dojo 2 coming up (especially with typescript) dGrid will certainly need to lose compatibility with > Dojo 1.8 some day.

Why do we need put-selector and x-style if we can do without them? I think they add no value and only bring down perf.

Could you explain how these changes are breaking backward compat? If dgrid loses dependency on these, I have trouble understanding how any old code requiring these would break? They would be unnecessary requires at best?

Finally, wasn't moving to dStore and getting rid of column plugins also breaking backward compat?

**Comment by kfranqueiro** [comment]
They break backwards compatibility because users may be expecting the current behavior of automatically including dgrid's structural CSS resources.  Those users will end up with broken-looking applications if we backport these changes to 0.4 and they update to 0.4.1 when it is released, which would be a pretty rude awakening and likely cause a lot of aggravation.

> Finally, wasn't moving to dStore and getting rid of column plugins also breaking backward compat?

Yes, but that was done in 0.4.0.  0.3 -> 0.4 = documented backcompat-breaking changes.  0.4.0 -> 0.4.1 should avoid that.  This is following the basic rules of semver (although technically semver doesn't impose itself on 0.* releases, but dgrid sees enough production use already that not following semver would be a very bad move.  Some have argued dgrid ought to be considered 1.x already.)

**Comment by mc007** [comment]
@gaurav21r just fork it and fix it; given the speed of updates i didn't had that much trouble. also, its better  to fork those column plugins since they are far from ideal anyways. and yes, after all, you can call it rc1 ;-)
