### ISSUE TITLE
Edit mode does not work when DnD is enabled

### ISSUE THREAD

**Issue by fbouchereau** [SitePen/dgrid#1073]
If I add a widget that contains an edit box so that it renders on a cell, I cannot focus the edit box by clicking on it as the mouse operations are taken over by drag and drop extension.

**Comment by kfranqueiro** [comment]
This sounds like it may be covered in #1020 - can you check whether that adequately describes your issue, or perhaps comment on it as it may be largely related?  Thanks.

**Comment by fbouchereau** [comment]
Hello, 
Yes, #1020 described the same issue. Thanks.

**Comment by kfranqueiro** [comment]
Thanks for confirming, in this case we'll track it there.  This is definitely something we have come across but unfortunately have not had time to diagnose yet.
