### ISSUE TITLE
Selection list is displayed outside an editable cell

### ISSUE THREAD

**Issue by fbouchereau** [SitePen/dgrid#1074]
When I try to render a widget containing a selection list on an editable cell, sometimes I see that the drop down list is shown completely outside the cell at the left top corner of the browser window. 

The list display persists even after the editable cell has lost focus and has gone back to normal mode.

**Comment by kfranqueiro** [comment]
When you say a selection list do you mean `dijit/form/Select`?  I haven't seen this happen.  Would you be able to provide details on your Dojo / dgrid versions and a test case that reproduces the issue?

**Comment by fbouchereau** [comment]
Hello,
Yes I meat dijit/form/Select.

I have tried to write test code to reproduce this but I am not able to see the issue. 
I guess this must be a combination of the content pane, plus container, plus dgrid table that I am using to build my application.

**Comment by kfranqueiro** [comment]
Given that we unfortunately haven't been able to reproduce this issue, I'm going to close it.  If at some point you are able to find a reduced case that reproduces it, we'd be interested in looking into it, whether the problem winds up in dgrid's court or dijit's.
