### ISSUE TITLE
Cells and rows render incorrectly when DnD is used

### ISSUE THREAD

**Issue by fbouchereau** [SitePen/dgrid#1075]
When I use DnD on my dgrid table:
1) I notice that row cells are not aligned (by a few pixels) with respect to the corresponding header cells. 

2) A space is added between each row (there are blank spaces between rows).

I have created a sandbox for this here:
http://dojo-sandbox.net/public/bffc4/3

Please run the code with and without adding DnD into the custom grid declaration and see the differences.

**Comment by kfranqueiro** [comment]
Unfortunately dojo-sandbox no longer seems to be operational, but my guess is that styles added by a dijit theme are causing this issue.  We have seen this happen and have had to work around it in cases where we use dgrid's DnD extension.

For example, the [DnD test page](http://dgrid.io/js/dgrid/test/extensions/DnD.html) adds the following to override dijit styles:

```css
.dojoDndItem { padding: 0; }
```

I suspect this is probably the issue you encountered.  If it's not, if you could re-post the test case, we can take another look.  Thanks!
