### ISSUE TITLE
OnDemandGrid does not update to changes in store with dstore/legacy/storeAdapter

### ISSUE THREAD

**Issue by Minganie** [SitePen/dgrid#1081]
Using these stores (oldStore worked as expected with grid 0.3):
```javascript
var oldStore = new Observable(new Cache(
    new JsonRest({ target: "exemple/" }),
    new Memory()
));
var store = new StoreAdapter({ objectStore: oldStore });
```
and this grid:
```javascript
var tablo = new declare([OnDemandGrid, Selection, Keyboard, DijitRegistry])({
    collection: store,
    sort: { attribute: 'nom' },
    noDataMessage: 'Aucun...',
    loadingMessage: 'Chargement...',
    selectionMode: 'single',
    cellNavigation: false
});
```
After a oldStore.put, the grid does not update to reflect the changes made to data, while it did with grid 0.3. This issue does not happen using a [Rest, SimpleQuery, Trackable] dstore (which however, is causing some issues with various dijit widgets, which makes me hesitate to migrate over to dstore completely). Am I using the store adapter improperly? Is it an issue with the cache?

**Comment by kfranqueiro** [comment]
Out of curiosity, have you tried making `store` trackable on the dstore end instead with `Trackable.create`?

**Comment by Minganie** [comment]
I tried with these stores:
```javascript
var oldStore = new Cache(
    new JsonRest({ target: "exemple/" }),
    new Memory()
);
var store = Trackable.create(new StoreAdapter({ objectStore: oldStore }));
```
The issue persists.

**Comment by kfranqueiro** [comment]
Unfortunately I think this may be due to a limitation currently in dstore: https://github.com/SitePen/dstore/issues/125

It probably makes more sense to track this there.
