### ISSUE TITLE
Added item in dstore is not sorted in dgrid

### ISSUE THREAD

**Issue by Minganie** [SitePen/dgrid#1084]
When adding an item to a Rest, SimpleQuery, Trackable dstore, the dgrid that uses the store does add a new row. However, the place the row appears in the grid does not respect the sort property of the grid. Clicking a column header to re-sort the data gets the new row placed in the good spot. So does calling refresh() on the dgrid. However, this seems like the sort of thing that should happen by itself in the process of adding the row rather than myself having to manually call sort on the grid once the item is added.

(In the Rest store, I am using rangeHeaders=true and overriding _renderFilterParams to remove the keyword "match" and just get a good old "=". The sort on the grid is: sort: [{ property: "nom", descending: true }],).

**Comment by akaJes** [comment]
does yours Rest server side return properly response status code 201?
it used to decide what event be used for grid rendering
look at https://github.com/SitePen/dstore/blob/master/Rest.js#L96
and use like php code <code>header("Content-Type: application/json ;charset=utf-8",true,201); //created.
</code>

**Comment by Minganie** [comment]
Yes, my Rest server returns 201 on creation.

**Comment by Minganie** [comment]
Turns out the problem is that _createSortQuerier in dstore/SimpleQuery is case-sensitive. So I was getting an order I perceived as random when it was in fact case-sensitively ordered. Adding 
```js
aValue = typeof aValue === 'string' ? aValue.toLowerCase() : aValue;
bValue = typeof bValue === 'string' ? bValue.toLowerCase() : bValue;
```
between lines 124 and 126 solved my issue.
