### ISSUE TITLE
After column reorder grid refreshes and moves all the to the left

### ISSUE THREAD

**Issue by rafalst** [SitePen/dgrid#1088]
Hello,

I have a large dgrid with 4 frozen columns on the left and about 20 or so columns that go off into the right.  The 20 columns have horizontal scroll bar in the dgrid.

Of the 20, only about 5 are visible at any time.

When I scroll to the right and by dragging change the order (position) of say, column 19 to column 17, by draging the column 19 to position 17, the grid refreshes and moves all the way to the left.

How can I keep the grid from scrolling left or move the grid back to the dragged column?

I managed to find that this event fires after dragging:

    		aspect.after(grid, 'renderHeader',function(){
    			console.log("aspect.after(grid, 'renderHeader', function(){...");
    		});	 		

Thanks

**Comment by billdwhite** [comment]
have you tried using the keepScrollPosition parameter in the table?

**Comment by rafalst** [comment]
Thanks that worked.
