### ISSUE TITLE
IE 11 Custom Sort not working correctly 

### ISSUE THREAD

**Issue by rafalst** [SitePen/dgrid#1089]
This works perfectly in Firefox

In IE 11 this does the sort with some items out of order, when more rows in dgrid than displayed.

Any help would be greatly appreciated.

The following is a cut/splice/paste, so I hope I got the brackets correct:

```js
define(["dojo/_base/array",
],function(array
){
	return {
grid: function(e, grid){
var	sort = e.sort[0];
if (sort.attribute === "columnName"){
	e.preventDefault();
	grid.set("sort", {});
					
	grid.store.data.sort( function(a, b){
						
		var aValue = a.dataStringA,
			bValue = b.dataStringB;
						
			if(aValue !== bValue){
				return !! sort.descending === (aValue === null || aValue > bValue) ? -1 : 1;
			}
						
			return 0;
	});
}
};
});
```

**Comment by kitsonk** [comment]
What version of dGrid were you using?

**Comment by kitsonk** [comment]
Closing due to lack of response of original poster, can re-open if still an issue and information provided.
