### ISSUE TITLE
chrome performance expand/collopse tree

### ISSUE THREAD

**Issue by jibtga** [SitePen/dgrid#1090]
Hi
Chrome performance with tree is very bad, I test dgrid demo Webs too. I check lastest version on Windows (Chrome) and on Debian (Chromium).  Otherwise firefox woks OK. 
Is it normal this behaviour?:

**Comment by kfranqueiro** [comment]
Can you provide a specific example (even if it's a URL to a test/demo)?  It doesn't sound normal to me. :)

**Comment by jibtga** [comment]
Now It works Ok, I am getting mad, sorry for the inconvenience
