### ISSUE TITLE
Why dgrid uses its own sort format instead of using standard dstore format?

### ISSUE THREAD

**Issue by anatoliyarkhipov** [SitePen/dgrid#1091]
`dgrid` sorts its `dstore` collection like this:
`collection.sort([{ attribute: column, descensing: descending }])`
Instead of using standard dstore format:
`collection.sort(column, 'DESC').sort(column2, 'ASC')`

Should I implement support for the `dgrid` sort format on the my custom store level, or this format will be changed and it is better to write an `DgridStore` proxy which will convert from the `dgrid` format to the `dstore` format before calling the original `.sort`?

**Comment by kfranqueiro** [comment]
dgrid 0.4 passes objects with `property` (not `attribute`) and `descending` properties.  This API is [documented by dstore](https://github.com/SitePen/dstore/blob/v1.0.1/docs/Collection.md#sorthighestsortorder-nextsortorder) and thus *should* be supported by any store implementing its APIs.

Ordinarily, normalization between these formats is taken care of by the `dstore/Store` base class: https://github.com/SitePen/dstore/blob/v1.0.1/Store.js#L259-L265

**Comment by anatoliyarkhipov** [comment]
Thanks, @kfranqueiro. I missed that my implementation should use `normalizedArguments` instead of `arguments`, my mistake.
