### ISSUE TITLE
Grunt does not build css files for extensions

### ISSUE THREAD

**Issue by aprilmay** [SitePen/dgrid#1094]
Stylus files in the css/extensions directory are not built. Using the current dgrid source.

Workaround: add the line below in Gruntfile.js, in the definition of stylusFiles:
'css/extensions/*.styl',

**Comment by kfranqueiro** [comment]
The individual components' structural styles are intentionally not built separately; they are included in dgrid.css which is built from dgrid.styl which references those components.

**Comment by aprilmay** [comment]
Thanks for this clarification, i missed that.
