### ISSUE TITLE
bad check on preload items in virtual scroll with OnDemandList when using custom renderRow() and dStore

### ISSUE THREAD

**Issue by denov** [SitePen/dgrid#1105]
I've been reading through the code hoping to be able to fix the bug on my own as this is a show stopper for me and I need this fixed asap.  But after a few hours I've decided that I could use a hand to get a quick understanding of what's going.  

This is with dGrid 0.4.0 / dStore 1.0.1 / dojo 1.10.1

The bug I've notice is that when extending renderRow() so I can have a list of Dijits that when I start to scroll this while loop https://github.com/SitePen/dgrid/blob/master/OnDemandList.js#L477 isn't completing as quickly as it should.  this causes renderRow() to be fired hundreds of times unnecessary and the browser to hang.  

I have notice that as we are looping that the conditional (// the preload is above the line of sight) is called when we are only scrolling down.  This doesn't seem right.

So my questions are how / where are we checking to see if we have gotten enough for are at the end of the items in the store.  It seems like the check to see if we are at the end isn't correct causing it to loop back around to the start. 

Some code.

```javascript
        this.contentList = new (declare([ OnDemandList, DijitRegistry ]))({
                                         minRowsPerPage: 10,
                                         maxRowsPerPage: 25,
                                         farOffRemoval: 1000,
                                         loadingMessage: i18n.loading,
                                         selectionMode: 'none',
                                         showFooter: true,
                                         pagingTextBox: true,
                                         firstLastArrows: true,
                                         rowsPerPage: 15,
                                         renderRow: function(object) {
                                             return lang.hitch(that, function() {
                                                 var domNode = that._buildContentItem(object).domNode;
                                                 var node = domConstruct.create("div");
                                                 domConstruct.place(domNode, node);
                                                 return node;
                                             })();
                                         },
                                         removeRow: function (rowElement, preserveDom) {
                                             this.inherited(arguments);
                                         }
                                     });
        domConstruct.place(this.contentList.domNode, 'contentGrid');
        this.own(this.contentList);
```

later on ...

```javascript
        this._results = results;
        this._store = new Memory({data: results, idProperty: viewingGuidelines() ? 'guidelineId' : 'evidenceSummaryId'});
        this.contentList.set('collection', this._store.filter(query));

```
the Dijit for the list

```javascript
    _buildContentItem: function(object) {
        console.info("Building *** ", object)
        var that = this;
        object.draftOfflineTime = this._isContentOffline(object.currentDraftId) ? getLastUpdateTime(object.currentDraftId) : null;
        object.pubOfflineTime = this._isContentOffline(object.currentPublishId) ? getLastUpdateTime(object.currentPublishId) : null;

        var contentItem = new ContentItem({'content': object, 'selectTab': selectTab});
        this.own(
            contentItem,
            aspect.after(contentItem, 'toggleDraftMode', lang.hitch(that, that._toggleOfflineMode)),
            aspect.after(contentItem, 'togglePublishMode', lang.hitch(that, that._toggleOfflineMode)),
            aspect.after(contentItem, 'createPDF', that.createPDF),
            aspect.after(contentItem, 'duplicateContent', that.duplicateContent),
            aspect.after(contentItem, 'updateOfflineCopy', lang.hitch(that, that.updateOffline))
        );
        contentItem.startup();

        this._widgets.push(contentItem);
        return contentItem;
    },
```

**Comment by kfranqueiro** [comment]
Regarding when OnDemandList stops querying for more data, it keeps track of how many rows each preload region (above and below the currently rendered data) represent based on the total number of items reported by the collection, and will naturally not try to load anything when that number is 0.  (https://github.com/SitePen/dgrid/blob/v0.4.0/OnDemandList.js#L488)

Would you be up for pulling the latest from the dev-0.4 branch?  I am wondering if you are running into a form of #965 which has been fixed post-0.4.0.  Though if you are running into that, I suspect you might want to do something about that, because OnDemandList can't really operate effectively (i.e. to estimate how tall the full height should be) if the rows are all 0 height.

**Comment by denov** [comment]
The problem is still in the dev-0.4.  I tried setting height on my rows in renderRow in 0.4.0 to see if that had any effect.  Nope..

I'm watching it load from fetchRangeSync in dStore with a pattern (start-end)  of something like 0-9,10-35,0-8,11-36,0-8,10-35.  My store has 48 items it in.

**Comment by denov** [comment]
here's what the stack looks like while it's stuck trying to sort itself out.

```
declare._processScroll (OnDemandList.js:325)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
(anonymous function) (OnDemandList.js:646)
signalListener (Deferred.js:37)
Deferred.then.promise.then (Deferred.js:258)
(anonymous function) (OnDemandList.js:586)
(anonymous function) (OnDemandList.js:652)
declare._trackError (_StoreMixin.js:376)
declare._processScroll (OnDemandList.js:580)
```

**Comment by kfranqueiro** [comment]
> Should it be calling https://github.com/SitePen/dgrid/blob/v0.4.0/OnDemandList.js#L463 if you are scrolling down?

Yes.

OnDemandList iterates through all of its preload nodes (2 of them for flat grids - one at the top and one at the bottom) to figure out if any are within the currently visible area of the grid after scrolling.  In simple terms, whenever the current viewport is completely occupied by already-rendered data, the first preload node will be above the current viewport (and hit the `else if`), and the second preload node will be below the current viewport (and hit the `if`).  The `else` is what's responsible for actually rendering data.

Here's a question...  how tall is your grid?  The only way I could really fathom this infinite recursion happening is if one or both preload nodes are constantly within the current viewport every time `_processScroll` checks (which it does again after rendering anything to make sure it rendered enough), and have a non-zero count (i.e. some items were unrendered).

Would you be able to reduce this to something you could toss into a gist or [fiddle](http://www.sitepen.com/blog/2014/10/15/dojo-faq-how-to-use-jsfiddle-to-provide-a-functioning-test-case/) so I could see it happen?

**Comment by denov** [comment]
The grid is almost the full page height. There is a header/menu on top and footer on bottom. Header and footer are fixed sized.

I'm getting to get a handle on what is going on in the code.  I get how `renderQueryResults()` calls _processScroll() at the end. It looks like to have `_proccessScroll()` stop being called that `this.preload` must be `null` or `undefined`.  If `this.preload` has a value then the 2nd while loop fires.  https://github.com/SitePen/dgrid/blob/v0.4.0/OnDemandList.js#L139 is the only spot I see where `this.preload` is set.  


I can try to do up a fiddle on this. I'll need to figure out how to include my custom Dijit.

**Comment by denov** [comment]
what's the correct RawGit urls to use for dGrid 0.4 and dStore?

**Comment by denov** [comment]
what's wrong here http://jsfiddle.net/denov/8ua7ze5v/2/ ?

**Comment by kfranqueiro** [comment]
Passing a string as the first parameter to `place` is only valid if it's recognizable as a string of HTML (i.e. starts with `<`).  Yours isn't/doesn't.  If you change `domNode` to `'<div>stuff goes here</div>'` it'll work.

**Comment by denov** [comment]
I think you may be on to something with the idea of having both the top and/or bottom preload in the viewport when `_processScroll()` happens as the loop starts when I scroll about half way done.

**Comment by kfranqueiro** [comment]
Generally you should be safe so long as your height doesn't surpass 2 * `farOffRemoval`, but if your height is higher than that, you may want to increase that value.

**Comment by denov** [comment]
And in the loop I see the `removeDistantNodes()` called a lot.

**Comment by denov** [comment]
height?  the height of the `div` that holds the grid or the total height of all the rows render?
 
and should `farOffRemoval` * 2 be more than `maxRowsPerPage` * Dijit height?

**Comment by denov** [comment]
YES!!! setting `farOffRemoval` to 2501 seems to fix it!  If you look at my first post I was trying to use 1000.  2000 causes the problem too.   2501 = `minRowsPerPage` (10) * Dijit Height (250).  I now seem to have smooth scrolling.

My thought about setting it to 1000 was it would remove any Dijits that was above or below the viewport by 1000px.

**Comment by kfranqueiro** [comment]
Heh.  Nope, `farOffRemoval` is an absolute value.  Which means it can lead to stuff like this.

I really want to overhaul OnDemandList for the next version of dgrid, whenever time permits, and part of that will definitely be to take a long hard look at the myriad properties that can be set, and see about reducing it down to a minimum set that makes sense (and is hopefully less prone to shooting oneself in the foot).

I'm going to close this since it sounds like you've solved your problem.  Thanks!

**Comment by denov** [comment]
Just some ideas - 

Couldn't `farOffRemoval` be calculated or a console warning thrown during the first call to `renderArray`  to warn about this?  Or not be static and calculated from `rowHeight` and `minRowsPerPage`?

Personally I see virtual scrolling in `OnDemandList` being super useful for dealing with screens that have a large list of complex Dijits in them.  Or for doing an infinite scroll.   But there needs to be a better way to destroy Dijits when `removeDistantNodes` calls `removeRow`.  The whole delaying of the destroy doesn't work if you extend `removeRow` to deal with destroying the Dijit as the DOM is already gone.

I do appropriate your work on dGrid.  Keep it up!!!
