### ISSUE TITLE
utils/misc => throttleDelayed and Juniper rewrites

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1108]
I have a very specific issue here.

I am using dgrid 1.3.15.

A customer is using Juniper which is rewriting app URLs, like this: https://mycompanyserver.com/,DanaInfo=www.msn.com,SSO=U+

The app relies on a huge dojo framework and loads fine except for one particular dgrid script (dgrid/utils/misc). It looks like it is appending things to the setTimeout functions (see screenshot). Have you come across this anywhere before?
![screenshot_69](https://cloud.githubusercontent.com/assets/1474114/6828608/1f56cdf0-d2e5-11e4-865a-1175c82d3891.png)
![screenshot_70](https://cloud.githubusercontent.com/assets/1474114/6828620/27e4b158-d2e5-11e4-907d-e23c73408991.png)

**Comment by kfranqueiro** [comment]
I've never seen this, but then I've never used Juniper products.  It does seem like [DanaSetTimeout is a thing](https://patentimages.storage.googleapis.com/US7873994B1/US07873994-20110118-D00005.png) that Juniper rewrites `setTimeout` calls with, seemingly with the intent of intercepting server polling operations (not that nearly every setTimeout involves a server request...).

It looks like one particular instance of Juniper's wrapping is tripping up in the throttle function, and I don't really have an explanation, given that the next one in the file is written in much the same manner and it's not tripping on that one.

I did some poking around but didn't find any clear indications of whether there's a way to tell Juniper not to wrap setTimeout, or any evidence of known bugs.

If you feel like messing around with the code in `throttle` to see if you can manage to get Juniper to play nice, I'd be curious as to your findings, but I'm not really sure if there's a solution.

**Comment by kfranqueiro** [comment]
Actually, I had forgotten you're dealing with 0.3.  One difference there is the `setTimeout` call in `throttle` is a one-liner, while the one in `throttleDelayed` is split to multiple lines.  (In 0.4, both are multiple lines.)  Maybe try adding newlines after the opening brace and before the closing brace and see if Juniper doesn't trip anymore?

**Comment by fredfortier** [comment]
Yes, it's kind of an obscure use case from a corporate customer. At the moment, they are exploring infrastructure approaches. I have minified dgrid and migrated to 0.4, but did not try yet. I will let you know what comes out of it.

**Comment by kitsonk** [comment]
I am assuming this is resolved... if the issue still persists in 0.4 then best to open a new issue.
