### ISSUE TITLE
Arrow keys expanding the selection

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1111]
I recently upgraded dGrid from 0.3 to 0.4.

I noticed that navigating through the grid using the arrow keys now expands the selection. I do not want that. I want the users to be able to scroll and page through the grid without changing the selection.

Other than mouse events on the row or selector cells, I would like them to be able to change the selection by hitting the space bar from a give position in the grid. But I do not want the arrows to affect the selection.

I tried the selectionMode "single" and "multiple", it does not make a difference (there is a multi-select even in "single" mode). I am using both the Selection and Selector mixins as described in the migration tutorial.

**Comment by fredfortier** [comment]
I removed the Selection mixin, as I see that Selector extends it. Now, arrows seem to be working correctly by changing the selection, at least in "single" selectionMode. However, clicking rows now augment the selection. I need to click the selector itself to correctly change the selection.

**Comment by kfranqueiro** [comment]
Simply pressing arrow keys and clicking rows should never add to the selection (at least in `single` or `extended` selection modes).  Are you sure your store items have unique identities and that `idProperty` is pointing to the correct property?  This sounds like #61.

**Comment by fredfortier** [comment]
I can confirm that my ids are unique. I this sort of verification in the fetch() method to make sure.
`console.log('unique ids?', _.uniq(_.pluck(this.results.items, 'id')).length, '=>', this.results.items.length);`
My id property is "id". I did set the idProperty explicitly to make sure.

My ids are rather long strings, for example: "HumanResources,{DDEC0CD1-4A43-45AB-9B9F-B34D02364E4A},{D0109814-DF91-45D9-A864-195415BC6E7B}". I am not sure if this could be a problem.

**Comment by kfranqueiro** [comment]
Can you narrow this down to a test case I'd be able to run?  I can't reproduce this problem in the [Selection](http://dgrid.io/js/dgrid/test/Selection.html) or [Selector](http://dgrid.io/js/dgrid/test/Selector.html) test pages.

**Comment by kitsonk** [comment]
Closing due to lack of response from the original poster.  Can re-open if information is provided.
