### ISSUE TITLE
Sorting a column with a custom formatter?

### ISSUE THREAD

**Issue by jpeterson** [SitePen/dgrid#1116]
When a column is defined as such:
```
column = {
  label: 'Percent Infants in Total Population',
  formatter = function(x, data) {
    return (data.infants / data.total_population);
  };
}
```

is there a way to make that column sortable? 

Setting sortable: true doesn't work (I'm guessing because the value I want to sort on is derived, so the underlying store cannot be sorted on it). Is there a workaround to get this to work (besides shoving that calculated value into my store)?

**Comment by fbcarter** [comment]
The workaround would be to use a calculated field if you can or have the
server side of the store do the calculation and return it as a field.

Farley

Farley

**Comment by kitsonk** [comment]
This question appears to be have answered.

**Comment by kvcrawford** [comment]
What is a "calculated field"?

I have a column with arrays for values, and would like to sort by the length of the arrays. Trying to figure out how to go about this.

**Comment by michaelgaigg** [comment]
wouldn't it be great if 'field' can be specified and used for sorting while formatter is being used to construct the label? Right now field and formatter cannot be used at the same time..
