### ISSUE TITLE
Column Reorder doesn't reorder the column contents

### ISSUE THREAD

**Issue by kasiwal123** [SitePen/dgrid#1117]
I am using the column reorder extension with dgrid/onDemandGrid. When I reorder the columns, only the column name(header) changes, the grid content remains same. Any particular reason why this could be happening?
I am using dgrid's tree plugin as well.

**Comment by kfranqueiro** [comment]
Please provide a runnable test case demonstrating your issue (via a gist or [JSFiddle](http://www.sitepen.com/blog/2014/10/15/dojo-faq-how-to-use-jsfiddle-to-provide-a-functioning-test-case/)).  As it is, ColumnReorder appears to work fine to me using dgrid's own [test page](http://dgrid.io/js/dgrid/test/extensions/ColumnReorder.html) or the [laboratory](http://dgrid.io/js/dgrid/demos/laboratory/).

**Comment by kitsonk** [comment]
Closing due to lack of response.  Can re-open if information requested is provided.
