### ISSUE TITLE
.dgrid-row-table row height 100%;

### ISSUE THREAD

**Issue by yipanbo** [SitePen/dgrid#1118]
为什么我的dgrid每一行的行高都是100%？
版本问题？还是什么？
我的dojo版本是：1.10.4，dgrid版本是最新的。
图片：
![1](https://cloud.githubusercontent.com/assets/8718011/7176855/aaa72b7c-e454-11e4-92d4-f31fde09b828.png)
![2](https://cloud.githubusercontent.com/assets/8718011/7176856/aaa8bf8c-e454-11e4-8fc9-f43575b3c1dd.png)
而我想要的效果是这样：
![3](https://cloud.githubusercontent.com/assets/8718011/7176857/aaa94a7e-e454-11e4-93da-545d9db96c24.png)

为什么每行的行高都是100%？
代码：
<link rel="stylesheet" href="js/dgrid/css/dgrid.css" />
	<link rel="stylesheet" href="js/dgrid/css/skins/claro.css" />
	
	<script type="text/javascript" src="js/dojo/dojo.js" djConfig="async: true"></script>
  	<script type="text/javascript">
  	require([
  	   	'dojo/_base/declare',
  	   	'dstore/Memory',
  	   	'dstore/Trackable',
  	   	'dgrid/Grid',
  	   	'dgrid/Selection',
  	   	'dgrid/extensions/Pagination',
  	   	'dgrid/extensions/ColumnResizer',
  	   	'dgrid/Selector'
  	   ], function (declare, Memory, Trackable, Grid, Selection, Pagination, ColumnResizer, Selector) {
  	   	var store = new (declare([Memory, Trackable]))({
  	   		data: createData()
  	   	});

  	   	// Instantiate grid
  	   	var grid = new (declare([Grid, Selection, Pagination, ColumnResizer, Selector]))({
  	   		collection: store,
  	   		selectionMode: 'single',
  	   		allowSelectAll: true,
  	   		columns: {
  	   			checkbox: {
  	   				label: 'checkbox',
  	   				selector: 'checkbox'
  	   			},
  	   			First_Name: {
  	   				label: 'First Name'
  	   			},
  	   			Last_Name: {
  	   				label: 'Last Name'
  	   			}
  	   		}
  	   	}, 'grid');

  	   	grid.startup();

  	   	function createData () {
  	   		var data = [];
  	   		var column;
  	   		var i;
  	   		for (i = 0; i < 50; i++) {
  	   			data.push({});
  	   			for (column in { checkbox: 1, First_Name: 1, Last_Name: 1 }) {
  	   				data[i].id = i;
  	   				data[i][column] = column + '_' + (i + 1);
  	   			}
  	   		}
  	   		return data;
  	   	}
  	   });
  	</script>
  </head>
  
  <body class="claro">
    <div id="grid"></div>
  </body>

**Comment by yipanbo** [comment]
求人不如求己，关键时刻还是自己靠得住！
dgrid github文档上说了：
Browser and Dojo Version Support

dgrid 0.4 works with Dojo 1.8 or higher, and supports the following browsers:

    IE 8+
    Firefox latest + ESR
    Chrome latest (desktop and mobile)
    Safari latest (desktop and mobile)
    Opera latest

dgrid 0.4 does not support quirks mode. You are heavily encouraged to include the HTML5 DOCTYPE (<!DOCTYPE html>) at the beginning of your pages.
其中DOCTYPE html>”很重要，不写成这样，效果可能会有偏差。
有人纪录过这个问题吗？我难道是一人？哈哈

**Comment by ebengtso** [comment]
I'm having the same problem, and I have <!DOCTYPE html> in my page. Did you find a workaround?

**Comment by ebengtso** [comment]
workaround is changing height to auto

.dgrid-row-table {
    border: medium none;
    border-collapse: collapse;
    empty-cells: show;
    height: auto;
    table-layout: fixed;
    width: 100%;
}
.dgrid-content {
    height: auto;
    position: relative;
}

**Comment by yipanbo** [comment]
我把 <!DOCTYPE html>添到页面上之后，样式就正确了。你这样改起作用了么？总感觉直接修改他的代码不是最好的办法。

**Comment by ebengtso** [comment]
I used google translate, but not sure I understand what you are saying...

Here the code snippet I used:

<link rel="stylesheet" type="text/css" href="./dgrid/css/dgrid.css"></link>
<style>
.dgrid-row-table {
border: medium none;
border-collapse: collapse;
empty-cells: show;
height: auto;
table-layout: fixed;
width: 100%;
}
.dgrid-content {
height: auto;
position: relative;
}
</style>

**Comment by ebengtso** [comment]
```
<link rel="stylesheet" type="text/css" href="./dojoRoot/dgrid/css/dgrid.css"></link>
<style>
.dgrid-row-table {
border: medium none;
border-collapse: collapse;
empty-cells: show;
height: auto;
table-layout: fixed;
width: 100%;
}
.dgrid-content {
height: auto;
position: relative;
}
</style>
```

**Comment by yipanbo** [comment]
my english is very poor~,i am chinese. where are you from? Github is so cool. 
when i changed my code to <!DOCTYPE HTML>, it worked.
Does your code work?
In my opinion, i don`t think change the source code of the dgrid is a good idea. Maybe you can find a better way to solve this question.

**Comment by kfranqueiro** [comment]
I just tested this too based on the code in the original post, and can confirm that adding a proper DOCTYPE resolves it.  Based on that I'm going to close this.  I'd suggest opening a question under [StackOverflow's dgrid tag](http://stackoverflow.com/questions/tagged/dgrid) with example JS and CSS if anyone still encounters an issue like this and the above doesn't work.
