### ISSUE TITLE
Prevent renderRow on store update

### ISSUE THREAD

**Issue by wshager** [SitePen/dgrid#1119]
Is there a standard way to incidentally prevent re-rendering a row when a an item in the store is updated?

**Comment by kfranqueiro** [comment]
If you're basically asking if you can turn store observation off, this is possible in 0.3.17 via the `shouldObserveStore` instance property and in 0.4.0 via the `shouldTrackCollection` property.

This might be a good FAQ to ask on StackOverflow's dgrid tag :)

**Comment by wshager** [comment]
I agree this was better asked on SO.
