### ISSUE TITLE
Toggle column hidden state fails with unhidable column

### ISSUE THREAD

**Issue by matheus-vieira** [SitePen/dgrid#1124]
I have a column that is unhidable and, programatically, it's shown or not.
But when I use the 'toggleColumnHiddenState' method it fails.

It says 'checked' is undefined which is correct, since the column is unhidable. I think is missing a check for unhidable columns. (Maybe it's a simple solution)

I'm using the method _updateColumnHiddenState(1, hidden); as work around.

**Comment by kfranqueiro** [comment]
Thanks for reporting this.  I've pushed a fix + unit test to master and dev-0.4, so this will be fixed for 0.4.1.
