### ISSUE TITLE
Request running twice with Pagination mixin

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1125]
I have an OnDemandGrid with the Pagination mixin.

I set the page size to 15. My store is an implementation of dstore/Store. I only implemented the Store#fetchRange(args) function.

I need to filter the grid often. Following the doc, I do something like this:
grid.set('collection', store.filter{'foo', 'bar});

This seems to work excepts that it invokes store.fetchRange(args) twice. The only difference between the two calls is the args.end parameter. The first call had it to 25, the second call has it to 15. I am not sure where the 25 would come from. Do you have any insights?

The paging functions (clicking on the page buttons) work correctly. This issue only seem to occur on when setting a filtered collection.

**Comment by kfranqueiro** [comment]
Incidentally, your first sentence describes what is likely the problem:  Don't use `OnDemandGrid` and `Pagination` together, mix `Pagination` into `Grid` instead.  There's a note in the [documentation](https://github.com/SitePen/dgrid/blob/v0.4.0/doc/components/extensions/Pagination.md) under the initial example about this.

**Comment by fredfortier** [comment]
That was it. Thanks!
