### ISSUE TITLE
Transfer box tutorial

### ISSUE THREAD

**Issue by bosticka** [SitePen/dgrid#1126]
The tutorial at: http://dgrid.io/tutorials/0.4/transferbox/

has an error in the html template.  Lines 5 and 8 which read:
data-dojo-attach-event="onClick: add"
data-dojo-attach-event="onClick: remove" 

should be instead:
data-dojo-attach-event="onClick: addSelectedItems"
data-dojo-attach-event="onClick: removeSelectedItems"

having the wrong click functions gives a strange lang.hitch scope error that would be hard to troubleshoot for most people I think.

Please update the tutorial.  Great tutorial btw!!!

Aaron

**Comment by kfranqueiro** [comment]
Thanks for reporting this.  @edhager committed a fix for this which was merged and pushed live about a week ago.
