### ISSUE TITLE
Clarify in the documentation which dgrid widgets support stores and which do not

### ISSUE THREAD

**Issue by edhager** [SitePen/dgrid#1133]
Update the documentation to make it clear that `dgrid/Grid` alone does not support stores.   Stores are supported in the following:

 * `dgrid/OnDemandList`
 * `dgrid/OnDemandGrid`
 * `dgrid/extensions/Pagination` 
 * `dgrid/_StoreMixin`

**Comment by kfranqueiro** [comment]
My initial thought would be to add a **Note:** somewhere near the top of the List and Grid documentation pages, in addition to potentially a callout in the stores tutorial.

**Comment by kfranqueiro** [comment]
This has been resolved in https://github.com/SitePen/dgrid/commit/fdaaa6d59d62a9fddf2d8be0bd2ad4738edc7506 (master), https://github.com/SitePen/dgrid/commit/98449465cf06174875c40e78168af3c0135aeeae (0.4), and https://github.com/SitePen/dgrid/commit/58d135fc85b3639ba49937867b0422816f5114c4 (0.3).
