### ISSUE TITLE
CSS class for expandable rows when using Tree

### ISSUE THREAD

**Issue by schallm** [SitePen/dgrid#1144]
I'm trying to style the expandable rows of a dgrid tree.  I would like the row to be a different color to allow the user to see them easier.

My current css looks like the following:

#existingItemsGrid  .dgrid-content > div.dgrid-row {
	background-color: #ddd; 
}

This works, but I have to add a rule for each grid. 

The dgrid/tree mixin could add a class to the entire grid allowing for something like:

.dgrid-tree .dgrid-content > div.dgrid-row {
	background-color: #ddd; 
}

Or the rows with expanders could have a class added similar to the dgrid-tree-container allowing something like:

.dgrid-tree-expandable {
	background-color: #ddd; 
}

or

.dgrid-tree-parent {
	background-color: #ddd; 
}

**Comment by kfranqueiro** [comment]
I pushed a branch with a commit that adds the `dgrid-row-expandable` class to parent rows.  If that looks like it'll serve your purpose, I'll merge it to master and dev-0.4 for 0.4.1.

**Comment by schallm** [comment]
That works awesome.  Thanks!
