### ISSUE TITLE
OnDemandGrid doesn't display data from table - but data shows up in Response headers

### ISSUE THREAD

**Issue by heathernicoale** [SitePen/dgrid#1145]
I am using Django 1.7 - Python 2.7, Dojo 1.8, dgrid .03. The Dgrid is pullig it's data from Django Rest Framework - which converts it into JSON.

The grid outline will display - but not populate with data. However in Firebug - you can go to the response headers - look at the JSON and the data is all there. I have used dstore and dgrid 0.4 - I have also tried DataGrid and the proper stores for that. I get the same issue no matter what I use. No error messages - nothing. 

Any pointers or advice would be helpful. Everything seems to be right. Not sure what else to try. 

![capture](https://cloud.githubusercontent.com/assets/10769123/8085516/94bc1414-0f5e-11e5-811b-dafa28a615f4.PNG)

**Comment by heathernicoale** [comment]
Have switched to dgrid 0.3.0 - still same issue at hand.

**Comment by kfranqueiro** [comment]
There isn't necessarily a lot of info to go on here, but this seems to be largely related to two StackOverflow questions ([here](http://stackoverflow.com/questions/30603306/how-do-i-connect-a-django-rest-framework-json-query-result-to-dgrid-ondemandgrid) and [here](http://stackoverflow.com/questions/30578854/dgrid-and-django-rest-framework-jsonrest)), which ultimately pointed to issues related to using a store implementation and server implementation that aren't fully compatible with each other.

StackOverflow is really a more appropriate place for such questions, but ultimately in this case the solution involves changing either the server API or client-side store implementation (or both, meeting somewhere in the middle) to adapt, and providing a complete custom store implementation would really be going above and beyond into territory better served by [commercial support](https://www.sitepen.com/support), and is certainly outside the scope of dgrid's issue tracker.

That being said, it hadn't occurred to me until now to look up Django Rest Framework, and I notice that version 3.1 supposedly [adds a limit/offset-based pagination scheme](http://www.django-rest-framework.org/topics/3.1-announcement/#pagination), which would go far towards resolving probably the biggest complication to using `dstore/Rest` (the fact that Django Rest Framework traditionally operates via pages while dojo/store and dstore use a start/count-based model).  You'll still presumably need to extend or create a custom store to process the response as needed though.

**Comment by heathernicoale** [comment]
This was MOST helpful!! Thank you!!

**Comment by heathernicoale** [comment]
Just to confirm (in case anyone else has this issue). The limit/offset pagination worked beautifully! After working on this for weeks, 9-10 hours a day I am happy to say that I have data displaying! :) However, I did not have to create a custom store, thankfully. I placed this setting globally in Django Res Framework settings in settings.py and it worked. Didn't even have to refresh the page. :)

# Django REST Framework configuration overrides
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination'
    
}

I know I've pestered you guys, but thank you so much for your help and advice! I'm new to all of this, so this was a huge deal. Thanks again!
