### ISSUE TITLE
selectAll skips rows in the middle

### ISSUE THREAD

**Issue by chr1st0scli** [SitePen/dgrid#1149]
Hi. 
I am referring to the closed issue #763, but not its original description but rather what the user allenerb reports. The call to selectAll skips some rows in the middle. I am attaching a screenshot and I am here for further details. The skipping rows pattern repeats again further down the grid (notice the scrollbar). Note that I have 137 rows loaded in my grid and approximately 5 are excluded. I am not using the latest version and I can't find which one I am using. The only thing I found in a README.md file is that I have the dgrid version which is recommended for use with Dojo 1.8.1. 
Thank you.

![skippingrows](https://cloud.githubusercontent.com/assets/5046010/8349029/1a1140a2-1b22-11e5-93c5-390b5cb57a89.png)

**Comment by chr1st0scli** [comment]
Please ignore, I downloaded the last version from the 0.3 branch and the issue does not occur anymore.

**Comment by tushkyparikh** [comment]
Hi chr1st0scli,

I am facing the same issue, So please let me know exactly what changes you have done to resolve this?
Any help would be greatly appreciated.

Thanks.
