### ISSUE TITLE
async mayHaveChildren support in Tree.js

### ISSUE THREAD

**Issue by ozdev** [SitePen/dgrid#115]
It'll be nice if store.mayHaveChildren() in Tree.js can return a Deferred like other methods. I've experimented with the idea by wrapping the part after getting mayHaveChildren in Deferred.when() and it seemed to be OK.

**Comment by kfranqueiro** [comment]
`mayHaveChildren` is still intended to be a synchronous API even in dstore.  Given that, it doesn't make much sense to add complexity to dgrid for an unintended use of the API.  (Again, if you omit `mayHaveChildren` entirely, you will just end up seeing expand icons on every row.)
