### ISSUE TITLE
Customize dstore/Request request method?

### ISSUE THREAD

**Issue by jpgtama** [SitePen/dgrid#1151]
Hi ,

Currently I found dstore/Request use 'GET' to do request. Is it good to customize this? So users can choose another method to use, say 'POST' in case of too many parameters when doing a listing? 

![image](https://cloud.githubusercontent.com/assets/1027605/8401893/142d8f26-1e68-11e5-975e-b522ecfed589.png)

**Comment by kitsonk** [comment]
@jpgtama I think the one "concern" about this is that it isn't very "RESTful" in that the `GET` is used for retrieval and `POST` is used for updating records.  Most services wouldn't handle this properly if it were post.

What specific use cases are you running into the limit.  [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) says that servers should not have a limit on the URI length, though in practice, some servers limit it to 2000 characters, but I would still question a scenario where your `GET` URI is > 2000 as a design issue.

**Comment by jpgtama** [comment]
Thanks for replying @kitsonk . I am working in a company and their back end service uses `POST` to do retrieval and they use dojox EnhancedGrid to display data before and EnhancedGrid can do `POST`. Recently they found EnhancedGrid was deprecated and so they switched to dgrid and then I need to either add a new `GET` method in back end or let dgrid support `POST`. I surely know we should use `GET` to do retrieval but I am not experienced at REST so I am not sure if I can persuade them. After posting this, I tried to use `GET` and our develop leader found it's better not to hack dgrid. So, yeah, we use `GET` now.
