### ISSUE TITLE
How to expand a particular row programmatically?

### ISSUE THREAD

**Issue by SamarthUpenn** [SitePen/dgrid#1153]

**Comment by kfranqueiro** [comment]
Call the grid's `expand` method.  It accepts 2 arguments:

* A dgrid row object, or something that can resolve to one (item, item ID, row element or child of a row element)
* A boolean indicating whether to expand or collapse.  The current state is toggled if this is not specified.

This is outlined in the [Tree documentation](https://github.com/SitePen/dgrid/blob/dev-0.4/doc/components/mixins/Tree.md#additional-grid-apis), and for future reference, questions like this would be better asked on [StackOverflow's dgrid tag](http://stackoverflow.com/questions/tagged/dgrid) or the [dojo-interest mailing list](http://mail.dojotoolkit.org/mailman/listinfo/dojo-interest).  This issue tracker is intended for dgrid issues, not usage questions.
