### ISSUE TITLE
Remove dependency to dStore

### ISSUE THREAD

**Issue by gaurav21r** [SitePen/dgrid#1155]
We've been using dGrid for a long time now almost since it replaced **dijit/Grid**. While **dojo/store** and **dStore** are both excellent concepts for a client side Datastore and we've been smoothly using them with dGrid, *in the spirit of* ***dojo 2*** ie the **componentization** of elements, may I suggest the **decoupling of dGrid from dStore**. http://dojotoolkit.org/community/roadmap/vision.html#modularity

DTK has always taken performance as a top priority and for many projects using dGrid I feel dStore is an overkill! A plain ol' JS Array / Object can also do the trick. Why wrap it around a `dstore/Memory` ? Many times we need dGrid just for a draggable list widget or to show a dgrid, where we'll be taking care of the communication via backend on our own!

Can't we give developers an option to use a plain JS Array or Object instead of dStore?

I'm sorry if this issue has been already posted and I'll request the dGrid collaborators for a healthy discussion on the merits / demerits of this rather than a *NO* :stuck_out_tongue: 

@dylans I'd like to hear your thoughts too!

**Comment by dylans** [comment]
The use of dgrid/List or dgrid/Grid works exactly this way, so I'm confused by the request. If you just need a simple List or Grid, then you don't pull in dstore at all, and just use an array of objects.

If you need to work with large data sets and need virtual scrolling, sorting, filtering, notification/updates when data changes, editing of fields, etc., then you need dgrid/OnDemandList or dgrid/OnDemandGrid, or the Pagination extension. In order to use these features, you could either rebuild dstore inside of dgrid, or you can pull in dstore.

Modularity does not mean to reinvent each feature within each package, so we would not want to reimplement the things dstore does, as that would just make dgrid larger. Regardless, I think your request is already handled in the way dgrid and dstore work...

**Comment by gaurav21r** [comment]
Alright I guess thats an oversight on my part. Aplogies. We've become so used to using `OnDemandGrid` that it didn't strike to use `Grid`. I understand the notification / updates part as why that would be inside dStore. Don;t you think Pagination / Virtual Scrolling are use cases that can be independent of dStore? Just conjecturing here, would like to hear your point of view.

True I agree we should not re implement functionalities. I think the `Grid` and `List` would serve well :+1:

**Comment by dylans** [comment]
> Don;t you think Pagination / Virtual Scrolling are use cases that can be independent of dStore?

The whole point of dstore is to implement a very light set of APIs to make it easy for dgrid to handle these scenarios. For example, a major part of virtual scrolling is to know which set of data to render, which is done by calling a filter on the collection of data. Keep in mind, a dstore Memory instance really is just an array of objects, with some extra methods added on top of it, so it's not really consuming much more in the way of resources, and for the simple cases, there's really not much more to do than working with an array of objects.

If you really don't want to use dstore, you could implement something that exposes the interface expected by https://github.com/SitePen/dgrid/blob/master/_StoreMixin.js , but I'd be hard pressed to make these capabilities all come together reliably with less code.

If the concern is that dstore is a big package in terms of number of files, perhaps it makes sense to have less store implementations in the main dstore package, and split it in two, but I'm not sure that adds more than complexity for end users that just want it be able to work with data.

**Comment by gaurav21r** [comment]
@dylans Ok Got it! I'll tell you the motivation behind this. We've been using `dStore` and `dojo\store\*` for a long time now and indeed the seamless integration with dGrid has been really really smooth.

To expand our project (which is actually a Platform) we have decided to go with **WebComponents / Polymer** in addition to **dijit** and we have a requirement to run everything collaboratively (with OT like Google Docs ) and offline.

The way I see Dojo's store architecture is for it to be a data backend for individual widgets. We've even created our own [dijitx](https://github.com/rcorp/dijitx) that extends this concept to `dijit/form/Form` and more interesting UI widgets. So if we have, say 10, grids on in our single page app, more often than not, 10 stores would be powering it. 

For the above requirements (collaboration & offline), we find it better to create a store structure mimicking our backend rather than being dependent on widgets. I know dStore has a **LocalDB** which we've tested and it works, but Syncing algorithms don't allow us for each widget to have a different store. So we are actively architecting a new kind of data store. One of our concerns was the breaking of all the things dStore does for dGrid *for free*.

**Comment by dylans** [comment]
Perhaps it's worth a look at Delite and Deliteful ( https://github.com/ibm-js/delite/ https://github.com/ibm-js/deliteful/ ) to see how they use dstore with their web components library.

I would think you could just specify dgrid points to your own custom dstore instance, which could implement a completely separate interface, as long as it exposes the same basic APIs, if you wanted, though I'm not sure why dstore couldn't be a foundation for solving what you are describing.

**Comment by kitsonk** [comment]
As @dylans the "dependency" is more of a set of consumable APIs versus a hard code dependency and is unlikely to change in the medium term.
