### ISSUE TITLE
Any plans to Webcomponentize?

### ISSUE THREAD

**Issue by gaurav21r** [SitePen/dgrid#1159]
With the advent of Polymer and WebComponents bursting into the scene. Is there a possibility where the core team would consider **"WebComponetizing"** dgrid?

A couple of points.

1. The process can be a simple wrapper around the element and doesn't need any core changes. Eg: They've done this for Hands on Table. http://handsontable.github.io/hot-table/.

  So the `DOMElement` will have a `this.grid` property referring to the created instance of dGrid.
But we would need to build the AMD dependencies into a single script file. Which I feel is anyway necessary for those not using Dojo for the rest of their project.

2. `GridFromHtml`**almost** does this! If only it conforms to the WebComponents standard, dGrid will become "interoperable" out of the box, one of the goals of WebComponents, apart from of course, the semantic HTML.

**Comment by dylans** [comment]
Web Components have a great vision, but they are not what I would consider done or production-ready at this time, and definitely not something I would move a stable grid to until that changes. As a developer, there are currently issues with:

* Managing parsing order of nested widgets/components when loading code asynchronously leads to race conditions when natively supported vs. when shimmed
* Custom elements are more widely supported, but features like shadow DOM are not
* Communication between components often results in the need for a lot of globals
* There's no namespacing or sandboxing of custom element names (e.g. if two things call themselves dgrid, good luck... and tags cannot use path identifiers like we do for Dojo).
* The way you style or theme web components is currently awkward

I'm not saying web components aren't a decent long term answer, but I strongly believe they are not yet ready for production usage.

**Comment by kitsonk** [comment]
As @dylans says, it is not on the near term roadmap for dgrid.  We could revisit when we believe WebComponents is ready for "prime time".

**Comment by gaurav21r** [comment]
Thanks @dylans and @kitsonk for your response :)

We will be making an experimental WebComponentized Grid based off of `dGrid` over at https://github.com/rcorp/superelements 

I hope our efforts would be useful for the SitePen team and the core dGrid contributors, at least in an academic way as to architecting dGrid as a WebComponent sometime in the future!
