### ISSUE TITLE
Grid Scroll Issue in Android , iPhone, iPad (touch devices)

### ISSUE THREAD

**Issue by BalajiV22** [SitePen/dgrid#1161]
When we are scrolling fast till the end or till to the top even though there is no data to be scrolled in the grid resulting in a crash issue, provided grid has sufficient data so that scroll bar appear in the grid.
![screenshot_dojo_grid](https://cloud.githubusercontent.com/assets/13414643/8772324/e4d309cc-2ee8-11e5-90c3-404df98d2b70.PNG)

**Comment by kfranqueiro** [comment]
It looks like this error is coming from the `TouchScroll` module.  On most modern mobile platforms, it is generally preferable to turn off that module's logic.

In recent versions of dgrid 0.3, this can be done by setting `useTouchScroll: false` on the dgrid instance.  In dgrid 0.4, TouchScroll is no longer incorporated by default.

Can you try disabling `TouchScroll` and see if behavior improves?

**Comment by kitsonk** [comment]
Closing due to lack of response from original poster, can re-open if information is provided.
