### ISSUE TITLE
dgrid column resize, hide, reorder properties gives an error if id of dgrid starts with a number

### ISSUE THREAD

**Issue by SamarthUpenn** [SitePen/dgrid#1162]
Following is the error: 
Uncaught SyntaxError: Failed to execute 'addRule' on 'CSSStyleSheet': Failed to parse the rule '#742grid__Search .dgrid-column-2 { display: none; }'.
This error arises when id of the dgrid starts with a number, here it starts with 742

The same error does not show incase I change the id of my dgrid to grid_742_Search.
I think this is a bug. Correct me if I am wrong.

![image](https://cloud.githubusercontent.com/assets/10647598/8959783/c9138e2a-35da-11e5-8dd3-3faacb1af2c9.png)

**Comment by CyrilCharlier** [comment]
Hi,

a class can't start with a number ;) (like XML)

**Comment by SamarthUpenn** [comment]
I figured out the following:
HTML IDs cannot start with a number, per the HTML 4.0 spec.

ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").
