### ISSUE TITLE
dgrid 0.4 - OnDemandList and Rest store do not fetch next result

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1165]
I have used OnDemandList before, mostly with my custom implementation of dstore/Store. It seems to work fine.

Now I am trying to use it with the built-in dstore/Rest store. I read this http://stackoverflow.com/questions/30603306/how-do-i-connect-a-django-rest-framework-json-query-result-to-dgrid-ondemandgrid/30606317#30606317 which seems to explain how to interface with the store. I am responding to the "target" operation request with an object which includes an items array and a total property.

Do you have any idea of where I should look for to resolve the issue?

Sample request: `http://localhost:4730/files/?offset=0&limit=25`
Sample response:
```json
{
    "total": 379,
    "items": [{
        "dev": 16777220,
        "mode": 33252,
        "nlink": 1,
        "uid": 502,
        "gid": 20,
        "rdev": 0,
        "blksize": 4096,
        "ino": 4112123,
        "size": 60728,
        "blocks": 120,
        "atime": "2015-07-29T23:01:53.000Z",
        "mtime": "2014-05-05T19:03:58.000Z",
        "ctime": "2015-03-26T14:12:47.000Z",
        "birthtime": "2014-05-05T19:03:58.000Z",
        "name": "1.jpg",
        "id": 0
    }, {
        "dev": 16777220,
        "mode": 33184,
        "nlink": 1,
        "uid": 502,
        "gid": 20,
        "rdev": 0,
        "blksize": 4096,
        "ino": 14951795,
        "size": 1059603295,
        "blocks": 2069544,
        "atime": "2015-07-01T14:47:02.000Z",
        "mtime": "2015-06-26T19:20:56.000Z",
        "ctime": "2015-06-26T19:21:05.000Z",
        "birthtime": "2015-06-26T19:08:29.000Z",
        "name": "2.0.3-ICN-FP003-WIN.zip",
        "id": 1
    }, {
        "dev": 16777220,
        "mode": 33184,
```

**Comment by dylans** [comment]
@fredfortier https://www.sitepen.com/blog/2015/07/07/javascript-support-in-action-using-dgrid-and-dstore-with-the-django-rest-framework/ is a more in-depth post on the same topic. If that doesn't help, I'm sure @kfranqueiro will be along soon to point you in the right direction. That said, we usually reserve the issue system for bugs, with the traditional support channels (StackOverflow, dojo-interest, or SitePen support) for questions until they are verified as bugs, to keep the issue system focused on the bugs we need to fix.

**Comment by fredfortier** [comment]
I did read this article. I cannot tell you for sure that it is a bug (I might be missing something). But after following the documentation, it does not work for me.

**Comment by dylans** [comment]
No problem @fredfortier, we'll take a look when we get a chance.

**Comment by kfranqueiro** [comment]
Does the grid immediately render as if its total number of items is only the amount of items received in the first request (i.e. you can't scroll further down)?  Or does it let you scroll but no requests happen?

**Comment by fredfortier** [comment]
The former. Thanks.

**Comment by kfranqueiro** [comment]
Hm.  That tends to indicate that it's not picking up the total correctly, but your response seems like it's in a format that dstore should pick up.

I would suggest breakpointing [here](https://github.com/SitePen/dstore/blob/v1.1.0/Request.js#L146) and seeing if that begins to shed any light.

**Comment by fredfortier** [comment]
Thanks. I will try that. You can close the issue of you want to clean up as I may not get back to you right away. I can open a new one with a more precise description if the issue persists and I can gather better context.

**Comment by voidstate** [comment]
I've been having the same issue. DStore/DGrid is not reading the total from my JSON response.

If I add a range header, such as `items 0-24/500`, it works, but this doesn't:

{
        "total": 1438,
        "items": [ ... ]
}

(Although the items are read ok)

Adding the breakpoint where @kfranqueiro suggests shows me that the total variable is not populated, and the response still seems to be a string rather than having been parsed into JSON. Is that why `response.data.total` returns `undefined`?

Here's a screenshot: ![dstore-bug](https://cloud.githubusercontent.com/assets/1204122/11090030/78614c7c-8866-11e5-9610-60635f89f62a.png)

**Comment by Newan** [comment]
`				total: response.then(function (response) {
					var total = collection.parse(response).total;
					if (total > -1) {
`
this fixed it for me
