### ISSUE TITLE
dgrid-scroller margin-top:0px;

### ISSUE THREAD

**Issue by bobmanc** [SitePen/dgrid#1170]
I am having a problem when I try to create an OnDemandGrid and attach it to a ContentPane. What happens is it sets the div with class dgrid-scroller margin-top:0px; which causes the first row of the grid to render directly over the labels. It's as basic as I could manage. Any ideas?

![grid](https://cloud.githubusercontent.com/assets/2130558/9363078/3b900814-4672-11e5-8327-3b1bf7e62f32.JPG)

This is what the code looks like.

<code>
define([
	"dojo/_base/declare",
	"dijit/layout/ContentPane",
	"dgrid/OnDemandGrid", "dstore/Memory"
], function (declare, ContentPane, Grid, Memory)
{
	return declare(ContentPane, {
		id: "MainView",

		constructor: function ()
		{
		},

		postCreate: function ()
		{
			var columns = {
				id: 'ID',
				firstName: 'First Name',
				lastName: 'Last Name',
				department: 'Department'
			};

			var data = [
				{id: 1, firstName: 'Conan', lastName: 'OBrien', department: 'accounting'},
				{id: 2, firstName: 'Dave', lastName: 'Letterman', department: 'sales'},
				{id: 3, firstName: 'Jon', lastName: 'Stewart', department: 'engineering'},
				{id: 4, firstName: 'Johnny', lastName: 'Carson', department: 'sales'}
			];
			var store =  new Memory({
				data: data
			});

			var grid = new Grid({
				collection: store,
				columns: columns
			});
			grid.startup();

			this.addChild(grid);

			this.inherited(arguments);
		}

	});
});
</code>

**Comment by shahzad31** [comment]
try this hack 
grid.on('dgrid-refresh-complete',function(){
grid.resize();
})

**Comment by bobmanc** [comment]
Works like a charm! Thanks.

I assume this is a bug.

**Comment by kfranqueiro** [comment]
Yes, that's a hack, and this is a bug...but not in dgrid.

You are calling `startup` before the grid is added to the document.  `startup` should only ever be called once a widget (whether dgrid or dijit) is already in document flow - that's the reason `startup` exists.

Moreover, since you are adding to a `ContentPane`, which is already capable of managing layout widgets, you shouldn't need to call `startup` yourself at all, but you probably want to mix in [`dgrid/extensions/DijitRegistry`](https://github.com/SitePen/dgrid/blob/v0.4.0/doc/components/extensions/DijitRegistry.md).

If this is being added to another layout container like a BorderContainer or TabContainer, you shouldn't even need an intermediary ContentPane between the layout container and the grid, as long as you're using `DijitRegistry`.

**Comment by bobmanc** [comment]
Ah..I see what you mean :)

I think this is the way to do it which works perfectly.
I will see if I can figure out a way to skip the ContentPanel in a simple way.

<code>
define([
	"dojo/_base/declare",
	"dijit/layout/ContentPane",
	"dgrid/OnDemandGrid", "dgrid/extensions/DijitRegistry", "dstore/Memory"
], function (declare, ContentPane, Grid, DijitRegistry, Memory)
{
	return declare(ContentPane, {

		constructor: function ()
		{
		},

		postCreate: function ()
		{
			var columns = {
				id: 'ID',
				firstName: 'First Name',
				lastName: 'Last Name',
				department: 'Department'
			};

			var data = [
				{id: 1, firstName: 'Conan', lastName: 'OBrien', department: 'accounting'},
				{id: 2, firstName: 'Dave', lastName: 'Letterman', department: 'sales'},
				{id: 3, firstName: 'Jon', lastName: 'Stewart', department: 'engineering'},
				{id: 4, firstName: 'Johnny', lastName: 'Carson', department: 'sales'}
			];
			var store = new Memory({
				data: data
			});

			var grid = new (declare([Grid, DijitRegistry]))({
				collection: store,
				columns: columns
			});

			this.addChild(grid);

			this.inherited(arguments);
		}
	});
});
</code>

**Comment by kfranqueiro** [comment]
It sounds like you've got this resolved, so I'm going to close this.

It may also help to look at the layout test pages, e.g. http://dgrid.io/js/dgrid/test/dijit_layout.html and http://dgrid.io/js/dgrid/test/dijit_layout_programmatic.html.

If you need further assistance, I'd suggest asking in one of the channels recommended for [Getting Support](https://github.com/SitePen/dgrid#getting-support).

**Comment by bobmanc** [comment]
Thanks. I meant to do that.

**Comment by max4ever** [comment]
the bug also presents itself when you create a table in a dom element  with `display:none`

```javascript

var gridTable = new (declare([ Grid, ColumnResizer, ColumnReorder, ColumnHider, Pagination ]))({
    columns: columns,
    store: memoryStore,
    //className: 'dgrid-autoheight',
    loadingMessage: this.nls.loadingData,
    noDataMessage: this.nls.noDataMessage,
    sort: [ { attribute: 'id', 'descending' : true}]
}, this.id + serviceConfig.idGrid);

gridTable.startup();

```

**Comment by kfranqueiro** [comment]
As I mentioned in an earlier comment, `startup` should not be called when the grid's `domNode` is not in document flow, which would be the case if it is inside an element with `display: none`.  This applies not only to dgrid but Dijit widgets as well.
