### ISSUE TITLE
Fetch all Item of Select All with dgrid

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1198]
Since I am unsure whether I am asking for a usage recommendation or reporting a bug, I initially asked this on StackOverflow: http://stackoverflow.com/questions/33339665/fetch-all-item-of-select-all-with-dgrid. Since it has been a few days, I am asking here again as it generally seems to receive more attention. I apologize for the redundancy.

---

I have a OnDemandGrid 0.4 instance with a custom dstore/Store collection. I use the Pagination and Selection mixins with allowSelectAll switched on.

Everything seems to behave except that, when I click the "select all" option, it only includes pages already rendered in the selection.

For example, assume that my results include 20 pages. When clicking the first page only, my selection contains only the rows in the first page. When clearing my selection, manually clicking all 20 pages, then clicking the "select all" again, I get all rows as I would expect.

Now, this may be working as designed (or not?), but I need to find a way to change this behavior so that clicking the "select all" options fetches all pages.

I can probably figure this out by drawing inspiration from this: http://dgrid.io/tutorials/0.4/single_query/. However, I want to check here first to make sure that I am doing this in the most efficient manner.

**Comment by fredfortier** [comment]
Here is how I implemented this. Please let me know if you have any feedback.

```javascript
        selectAll: function () {
            var originalArguments = arguments;
            if (!this.collection.isComplete()) {
                this.renderQueryResults(this.collection.fetch()).then(lang.hitch(this, function () {
                    this.inherited(originalArguments);
                }));
            } else {
                this.inherited(arguments);
            }
        },
```

**Comment by TimSchnCoding** [comment]
Same problem for me! Can you please explain your workaround fredforier? Or can the dgrid team help us to find a suitable solution? Thanks.

**Comment by fredfortier** [comment]
@TimSchnCoding `!this.collection.isComplete()` checks whether the collection currently contain the entire result set. If not, it renders the query results again using the entire result set. According to the "dstore" specs `this.collection.fetch()` should fetch the entire result set. Then, `this.inherited(originalArguments)` calls the original "selectAll" method.

I am not sure whether this is the most elegant or optimal solution.

**Comment by Venkesh** [comment]
Hi - I am also facing same issue.  I am using ondemandgrid selector/selection - When selectAll from header column selected - The grid is not fetching all total items.
-venkat

**Comment by edhager** [comment]
`OnDemandGrid` and `Pagination` have never been compatible.  They might appear to work together but there are scenarios that cause errors and cannot be resolved.  If you mix the two with the current version of dgrid, you will see an error message in the console and the grid will not render any rows.  

Here are combinations of Grid classes and mixins that are supported:

- `Selection` + `Selector` + `OnDemandGrid`.  You can see examples of that in action in the dgrid test pages: http://dgrid.io/js/dgrid/test/Selector.html
- `Selection` + `Selector` + `Grid` + 'Pagination'.

dgrid does not support fetching all items from the store when the select-all checkbox is checked.  The grid code keeps track of selected rows and evaluates whether or not an inserted row should be marked as selected.  You can see that here: 

https://github.com/SitePen/dgrid/blob/746ce2a9263ce330e64fb491f9511f0de6adf621/Selection.js#L681-L684

When a user clicks the select-all checkbox, `grid.allSelected` is set to true.

When a user selects individual rows, the `grid.selection` object will be populated with data.  The object keys are the item ids from the store.  The values will be `true` when the corresponding row is selected and either `false` or missing if a corresponding row is not selected.

Here is some sample code that demonstrates how to get a list of store items that correspond to selected rows in the grid.

```javascript
function selectedItemsDemo (grid) {
	var selection = grid.selection;
	var allSelected = grid.allSelected;
	var collection = grid.collection;

	var getSelectedItemsPromise;
	if (allSelected) {
		// The select-all checkbox is checked.
		// Use the grid.isSelected() to determine which store items should be selected.
		getSelectedItemsPromise = collection.filter(function (item) {
			return grid.isSelected(item);
		}).fetch();
	} else {
		// Use the grid.selection map to determine which store items, if any, are selected.
		getSelectedItemsPromise = collection.filter(function (item) {
			return !!selection[item[collection.idProperty]];
		}).fetch();
	}

	getSelectedItemsPromise.then(function (items) {
		// TODO: do something with the selected items here.
		console.log("Selected items:", items);
	})
};
```
