### ISSUE TITLE
Header overlaps rows with cactus, slate, and sage skins in Edge

### ISSUE THREAD

**Issue by maier49** [SitePen/dgrid#1204]
This image illustrates the issue. This is with the cactus skin but it looks the same for the other two.

![skinissue](https://cloud.githubusercontent.com/assets/5474358/11152689/072d0aa8-8a02-11e5-8f22-516f1106b455.png)

**Comment by kitsonk** [comment]
The current version of dgrid wasn't designed to work with Microsoft Edge, so labelling this as an enhancement.
