### ISSUE TITLE
dgrid/List options documentation

### ISSUE THREAD

**Issue by dylans** [SitePen/dgrid#1206]
In https://github.com/SitePen/dgrid/blob/master/doc/components/core-components/List.md , the renderArray, renderRow, removeRow and scrollToRow methods all contain an options object, but we don't explain where the options object comes from or what is contained within options.

**Comment by kfranqueiro** [comment]
I assume by `scrollToRow` you mean `scrollTo`, and its options are documented.  The others aren't though, and their `options` bags have long been problematically nebulous.  It'd probably be a good idea to get this documented even if just to inform future revisions to APIs, but it's probably going to be an easter egg hunt.

**Comment by kfranqueiro** [comment]
I did a scan through the various insert/render/remove methods that involve `options` objects last month, and indeed, they are predominantly used internally and generally aren't of interest to external use.  I'm planning to largely remove their mentions.
