### ISSUE TITLE
dstore 1.1.0 support?

### ISSUE THREAD

**Issue by jamime** [SitePen/dgrid#1208]
Do we know if dgrid works with the latest dstore? `bower.json` states ~1.0 which only resolves to 1.0.2.

**Comment by dylans** [comment]
Yes, dgrid 0.4 and newer work with dstore. dgrid just hasn't had a release recently, but should get one in the next 1-3 months.

**Comment by kfranqueiro** [comment]
bower.json has been updated to reflect this in dgrid 1.0.
