### ISSUE TITLE
dgrid without xstyle

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1219]
I see that you are removing the xstyle dependency from the grid. I assume that you are moving towards a more standard way to load the stylesheets. This is great. When do you expect to release a sans-xstyle version of dgrid? Will it work with dojo 1.10?

**Comment by fredfortier** [comment]
@dylans would you mind commenting on this quickly? I see that you have a note about a new dgrid release on issue #1208. I also see that you guys are hard at work based on the checkins. It would really help to have more details about dgrid.next and an estimated release date.

**Comment by dylans** [comment]
@fredfortier yes, as noted in the dstore ticket, we're hoping to wrap up the next dgrid release soon. Our goal is January, assuming things go according to plan.

**Comment by fredfortier** [comment]
@dylans thanks for the update. Can you confirm that the new dgrid will be compatible with dojo 1.10 (i.e. that it does not depend on dojo 2.0)?

Btw - I have been using dstore and dgrid pretty heavily. I like the architecture of those components and I appreciate the continuous refinement.

**Comment by kfranqueiro** [comment]
Yes, the forthcoming dgrid release still targets Dojo 1.8+.  We won't be targeting Dojo 2 until after this one's out the door (hopefully in January).

**Comment by fredfortier** [comment]
Thanks @kfranqueiro  and @dylans!
