### ISSUE TITLE
Using Dgrid.on together with ColumnReorder doesn't work properly.

### ISSUE THREAD

**Issue by Viliami** [SitePen/dgrid#1234]
After a column reorder, it says the error: t is not defined.
t is referring to the id of the column, and while re-ordering it doesn't exist for a short while.
Putting that snippet of code in a try and catch should fix it, otherwise it never calls on again.

**Comment by kfranqueiro** [comment]
Do you have a code example you can show here (or via gist.github.com or jsfiddle) to reproduce your issue?

**Comment by Viliami** [comment]
this.grid = new CustomGrid({
		        collection: this.my_store,
		        columns: {
		            name: "Name",
		            date: "Date",
		            uid: "User ID"
		        }
     }, 'grid');    
    on(dom.byId("dgrid-column-date"), "click", function(event){
			    //do something
    });

Sorry, I don't have a full code example, only a short snippet, if you reorder the columns, you will get TypeError: t is undefined at 417:24 in Source.js file.

**Comment by Viliami** [comment]
Now that I think of it, I think the reason is the use of 'byClass()' function.
It is only called once and that is before linking the events with the on() function.
Then when it is linked it is linked by Id instead, when the grid DOM is reconstructed by columnReorder, it no longer has the id assigned to it by the byClass() function.
