### ISSUE TITLE
Selection Mode single allows multiple selection on Selector Checkbox

### ISSUE THREAD

**Issue by pukhrajbal** [SitePen/dgrid#1243]
https://github.com/SitePen/dgrid/blob/master/test/Selector.html

If you turn selection mode to single in first grid in above test page, you would still be able to select multiple rows by clicking on the checkbox selector input.

**Comment by kfranqueiro** [comment]
This is intended behavior.

As stated in the [docs](https://github.com/SitePen/dgrid/blob/v1.0.0/doc/components/mixins/Selection.md#property-summary), `selectionMode` indicates "how selection should behave in response to direct user interaction."  It does not affect direct programmatic usage of the `select` API, thus it does not affect settings you apply to a selector column for `Selector`.

For consistent user interaction, if you're using `selectionMode: 'single'`, you would most likely also want to set `selector: 'radio'` on your selector column.
