### ISSUE TITLE
dont auto-startup in create

### ISSUE THREAD

**Issue by gbaumgart** [SitePen/dgrid#1246]
just to let you know: when using lazy rendering techniques(create and warm-up grids in multiple tabs for instance), the auto-startup in grid::create becomes really a problem and you can only prevent it from starting up by setting the grids target domNode to a 0 size which creates a number of other problems. i think, startup should be done explicitly, i know you don´t like it but its way more clean. there are of course ´more ´ways around´ but none of them will end up in clean or logical code. 
just saying. close this on dislike but please think about. it doesn´t feels right, don´t you think?

**Comment by kfranqueiro** [comment]
Can you provide an example?  If you are referring to grids that are hidden (e.g. in inactive tabs), they should effectively skip the auto-startup code.

I have always wondered if the auto-startup "feature" would present a problem, but to this point hadn't seen that happen.

**Comment by gbaumgart** [comment]
ups, didn't notice you answered. Code example: not really (too big non-dijit framework around) but I think it's actually not needed because you said it already: *if hidden* ! 

The very *if* requires already some extra code to prevent the startup in create. I actually don't want to care about being hidden or not, and simply hand over the startup call to a container API, ie: onShow:

container:onShow
-->checkWidgetsForBeingStarted. 
-->resizeWidgedsIfNeeded

Btw. there is also another issue regarding this: dgrid renders the column header without prior startup. Its no big deal but makes it harder to implement a grid.set('loading',true) method which should use the entire dom node to display some progress indicator, til data arrives.

Anyway, its fixed in my fork and pretty happy about

I close this; seems i hit some edge case only.
