### ISSUE TITLE
Using Flexbox in OnDemandList tile view

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1247]
I have been following this example to create a "tile" presentation using OnDemandList: http://dgrid.io/js/dgrid/test/OnDemand_tile.html. It works great when I stick to the exact conditions in this unit test.

Since my tiles have variable width, I would like to use the flexbox to put space around items in the view.

I tried something like this
.dgrid-content {
   display: flex;
   flex-direction: row;
   flex-wrap: wrap;
   justify-content: space-around;
}

This does the job except that "lazy loading" no longer works. It does not attempt the next page when reaching the scroller end. Please let me know if you have any idea or suggestion.

**Comment by synycboom** [comment]
Did you solve that ?

**Comment by msssk** [comment]
dgrid was created before flexbox existed. The virtual scrolling provided by `OnDemandList` in particular relies on precise DOM geometry calculations that make it incompatible with flexbox.
