### ISSUE TITLE
Pagination - get current page number?

### ISSUE THREAD

**Issue by storecat** [SitePen/dgrid#1254]
I need to get index of selected row (number of row not id of record). At now I am using jQuery function index(), which works good without pagination, but with pagination it became unusable and turns into something like this:
Once selected row has index 150 and when pagination start works index is changing to 70.
Is it possible to get current page number with dynamic pagination?
For eg. if I set 200 records per page, and I know current page number I could calc correct row index.

**Comment by kfranqueiro** [comment]
A couple of ideas:

You should be able to retrieve the current page from `_currentPage` on the instance. I had thought we might've exposed this via a getter, but it looks like that isn't the case at this point.

Meanwhile, dgrid also adds a 0-based `rowIndex` to each row's `div` element, so you might be able to make use of that directly.

**Comment by storecat** [comment]
Finally I used a little hack by doing simple loop on all grid elements, comparing if row id is selected row id and incrementing counter on every loop step which at end gives me rowIndex.

**Comment by websoftix** [comment]
> Meanwhile, dgrid also adds a 0-based rowIndex to each row's div element, so you might be able to make use of that directly.

This would be helpful but I cannot find the rowIndex in the generated html. Is there something required to have it added?

**Comment by kfranqueiro** [comment]
You won't see it visibly in HTML in dev tools; it is a property, not an attribute.  If you do e.g. `console.log(grid.row(...).element.rowIndex)` you should get a value.

**Comment by websoftix** [comment]
Thank you!

**Comment by storecat** [comment]
Big thanks - it worked also for me.
