### ISSUE TITLE
Tree stops functioning after calling `grid.set('columns', columns)` with previous columns

### ISSUE THREAD

**Issue by kriszyp** [SitePen/dgrid#1255]
This is very easy to reproduce, once you have created a tree grid, simply set the columns again with the same columns:
```
treeGrid.set('columns', treeGrid.columns)
```
And you will no longer be able to expand nodes. I reproduced it on common_cases.html with the tree grid there.

The cause of the issue is that the tree column will set `_isConfiguredTreeColumn` to true. When you later reset the columns, `_destroyColumns` will remove the expando listener. When the columns are reconfigured, `_configureTreeColumn` will be properly called, but will immediately return because `_isConfiguredTreeColumn` is still true, so the listener will never be re-added. Also, `_treeColumn` is nulled in `_destroyColumns`, and won't get reset by `_configureTreeColumn`, so even if `expand` does get called, it will immediately return as well because `_treeColumn` isn't set.

This is actually a regression due to:
https://github.com/SitePen/dgrid/commit/26a6d00932a1af23a318bd4fafe280e0aa4b31a0

Prior to that commit, `_configureTreeColumn` properly scoped the column configuration code inside the conditionally branch of `_isConfiguredTreeColumn`, and properly re-added the listener and `_treeColumn` when tree columns were reconfigured.

I could put together a pull request, but clearly the regression commit was trying to accomplish something, so I thought I would start by just identifying the exact cause.

**Comment by kfranqueiro** [comment]
Thanks for reporting this, Kris.  In 0.4.1 / 1.0.0, we had a couple of fixes in that area having to do with avoiding redundantly hooking up renderCell and event handlers, but it looks like at some point we oversimplified.  I think it slipped my mind that those event handlers were in fact being removed in `_destroyColumns`
