### ISSUE TITLE
dgrid-row-odd & dgrid-row-even wrong in trees

### ISSUE THREAD

**Issue by gbaumgart** [SitePen/dgrid#1258]
this two classes are not added correctly in trees (see test/index-1-1.css & PowerOn/Set Variable):

![image](https://cloud.githubusercontent.com/assets/1205100/13569656/954d78b0-e469-11e5-8c8b-3cba1a44d4d6.png)

dgrid-1.0

**Comment by kfranqueiro** [comment]
This is a known issue that will likely require rethinking how Tree renders children.  Currently it renders children in their own container node, which effectively resets odd/even tracking (same for if CSS3 `:nth-child` were to be used).

This is effectively a duplicate to #155, so closing.
