### ISSUE TITLE
refreshCell has no way to preserve level information for Tree

### ISSUE THREAD

**Issue by kfranqueiro** [SitePen/dgrid#1260]
If you call `refreshCell` on a child cell in a tree column, it is always rendered with no indent (as if it were top-level).

This issue comes down to the fact that there is no `options` object passed along when re-rendering cells via `refreshCell`.  There might be other instances outside of `Tree` where this could also be problematic.

Manual reproduction steps:

1. Open http://dgrid.io/js/dgrid/test/Tree.html
1. Expand a row in the first grid, then right-click/inspect the tree cell in one of the child rows
1. `treeGrid.refreshCell(treeGrid.cell($0))`

Expected: Re-renders child at appropriate level of indentation
Actual: Re-renders as if the child is root-level

**Comment by kfranqueiro** [comment]
I've pushed a potential fix to a branch for this, but a couple of things are bugging me:

* Technically, the `renderCell` implementation in `Tree` has a side effect of setting `this._currentLevel`, which is normally looked at by `insertRow`.  I'm not sure if there's a valid reason for that to exist - it seems like a hacky shortcut just so that `insertRow` doesn't have to potentially resolve `options.queryLevel` again itself.  I suspect the side-effect is harmless (since `renderCell` would always happen before that code in `insertRow`), but I also suspect we could re-engineer the hack out of existence.
* I debated making `_refreshCellFromItem` public, since it could be useful in cases where you already know the item, to avoid a superfluous trip to the store.  We could, but we might want to then add the grid duck-type check to it as well (or have the collection check in one and the grid check in the other, but that could lead to a potentially confusing error message from `refreshCell` if you call it on a not-grid).

Also, there's no unit test on the branch yet.

**Comment by gbaumgart** [comment]
the fix worked except that it sometimes crashes here because there is no collection yet:
https://github.com/kfranqueiro/dgrid/blob/69bc3c3da571fa1cabd06b1ca973ce7f164bbb9e/Tree.js#L347

**Comment by kfranqueiro** [comment]
Can you clarify how you reached that problem and whether it directly relates to this `refreshCell` issue?  That line of code is in an event handler for when the user initiates an expand or collapse, and ordinarily it shouldn't be possible for there to not be a collection at that time.

**Comment by msssk** [comment]
There are a few issues with this:

* When `refreshCell` is called on a cell created by `dgrid/Selector` it loses its selector widget (gets re-rendered as an empty cell)
    * Suggestion: don't re-render `Selector` cells - any downsides to this?
    * Fix: [ade82389](https://github.com/msssk/dgrid/commit/ade82389b65decc3c611ffb364c01a073d4a5aa8)
* Fails on child rows in `treeTopHeavy`
    * The store created in `test/data/testTopHeavyHierarchicalStore.js` seems like a bad hack. It creates child items that are ostensibly store items, but they exist only in the `children` array of objects that are actual store items. Then the tree methods are hacked to make the store kind of work like a tree store. Would this ever actually be a good idea? The child items, although they have ids assigned, can never be accessed by `store.get(id)`. I updated that module to create a store that actually uses `dgrid/Tree` (with no hacks) and structures the data appropriately.
    * Fix: [95ccde26](https://github.com/msssk/dgrid/commit/95ccde26b0e4b6b5532fa6558dea5e4c7cc541d3)
* If the target cell is `document.activeElement` and contains an editor, `document.activeElement`reverts to `document.body` after calling `refreshCell`
    * Fix: don't actually re-render editor cells, just set value from data [c966e2f9](https://github.com/msssk/dgrid/commit/c966e2f990cc2f5c9fdaa9a88b51c732c3f1714c)

**Comment by kfranqueiro** [comment]
Thanks for looking into this, Mangala.

>* When `refreshCell` is called on a cell created by `dgrid/Selector` it loses its selector widget (gets re-rendered as an empty cell)
>    * Suggestion: don't re-render `Selector` cells - any downsides to this?
>    * Fix: [ade82389](https://github.com/msssk/dgrid/commit/ade82389b65decc3c611ffb364c01a073d4a5aa8)

This generally sounds reasonable since selectors aren't expected to be influenced by data.  Not sure if anyone has custom cases where they'd want this to work based on data though.  Were you able to figure out why it loses the checkbox/radio?

Also, if we do fix it like this, I think the fix should go in Selector, not _StoreMixin.

>* Fails on child rows in `treeTopHeavy`
>    * The store created in `test/data/testTopHeavyHierarchicalStore.js` seems like a bad hack. It creates child items that are ostensibly store items, but they exist only in the `children` array of objects that are actual store items. Then the tree methods are hacked to make the store kind of work like a tree store. Would this ever actually be a good idea? The child items, although they have ids assigned, can never be accessed by `store.get(id)`. I updated that module to create a store that actually uses `dgrid/Tree` (with no hacks) and structures the data appropriately.
>    * Fix: [95ccde26](https://github.com/msssk/dgrid/commit/95ccde26b0e4b6b5532fa6558dea5e4c7cc541d3)

I poked around the commit history and looked at the original bug this was added in reference to, and...yeah I have no idea if there was a particular reason I did it that way.  I'm fine with us updating that.

> * If the target cell is `document.activeElement` and contains an editor, `document.activeElement`reverts to `document.body` after calling `refreshCell`
>     * Fix: don't actually re-render editor cells, just set value from data [c966e2f9](https://github.com/msssk/dgrid/commit/c966e2f990cc2f5c9fdaa9a88b51c732c3f1714c)

This has me worrying whether there are any edge cases where this won't work, though if there are, I think it'd come down to widgets with wonky value setter logic.

I can test this some more later today, but meanwhile, is there other stuff you are still looking into in this area?

**Comment by kfranqueiro** [comment]
@msssk, I've pushed a commit to `1260-tree-refreshCell-updates` on my fork that fixes some issues I found in the `Editor#refreshCell` changes.  I tested with both `editOn` and always-on textbox editors in the Editor.html test page and they seem to work.

We should probably really add unit or functional tests for this though:

* Test various types of inputs/widgets
* Test both with `editOn` set and not set
* Test both while actively editing the cell being refreshed, and while editing a completely different cell (e.g. I think the original commit for `Editor#refreshCell` would have entirely failed to refresh an inactive cell in an `editOn` column)

**Comment by msssk** [comment]
> Were you able to figure out why it loses the checkbox/radio?

Because there's no item in the collection for the `Selector` column: [`_StoreMixin#refreshCell`](https://github.com/kfranqueiro/dgrid/blob/69bc3c3da571fa1cabd06b1ca973ce7f164bbb9e/_StoreMixin.js#L234)

> I think the fix should go in Selector, not _StoreMixin.

Thanks, good call! Updated.

Working on tests.

**Comment by kfranqueiro** [comment]
> Because there's no item in the collection for the Selector column: _StoreMixin#refreshCell

I'm not sure I buy that argument.  I just tested against `master` and it is most certainly receiving/resolving an item fine - the real issue is that `_defaultRenderSelectorInput` is attempting to reuse the checkbox hung off of the cell element's `input` property, without realizing that that's already been nuked from the DOM (via `domConstruct.empty` in `_StoreMixin#refreshCell`, which likely makes it unsafe to reuse at least in IE).

I imagine we might be able to get by if we remove that input element prior to calling `inherited` in Selector's own `refreshCell`, then re-add it after it's done.

**Comment by kfranqueiro** [comment]
I didn't see any new commits on your fork, @msssk, so I've gone ahead and force-pushed a new `1260-tree-refreshCell-updates` branch which replaces the old commit attempting to address Selector with a new simpler one, which simply removes a spurious bit of logic that existed since pre-0.3, but was never actually being invoked before AFAICT - until `refreshCell` entered the mix in 1.0.0 and tripped over it.

**Comment by kfranqueiro** [comment]
This might already be known but I just noticed that one of the `_StoreMixin#refreshCell` tests (widget destruction) is currently failing with this branch.  Not sure if this is because of how I changed Editor in my last commit.

**Comment by msssk** [comment]
Tests [pushed](https://github.com/msssk/dgrid/tree/1260-tree-refreshCell-updates)
