### ISSUE TITLE
reset columns for Tree

### ISSUE THREAD

**Issue by riaeasy** [SitePen/dgrid#1261]
When reset columns mixed Tree, somethings need reset.
Here are the codes modified:

	Tree.extend({
		_destroyColumns: function () {
			this.inherited(arguments);
			var listeners = this._treeColumnListeners;

			for (var i = listeners.length; i--;) {
				listeners[i].remove();
			}
			this._treeColumnListeners = [];

			///begin================================///
			///需要重置，以能够重新处理（生成） treeColumn
			///reset somethings
			this._treeColumn._isConfiguredTreeColumn = undefined;
			this._treeColumn.renderCell = this._originalRenderCell;
			this._originalRenderCell = undefined;
			///end=================================///

			this._treeColumn = null;
		},

		_configureTreeColumn: function (column) {
			// summary:
			//		Adds tree navigation capability to a column.
			if (column._isConfiguredTreeColumn) {
				return;
			}

			var originalRenderCell = column.renderCell || this._defaultRenderCell;
			///begin================================///
			///保存，以在 _destroyColumns 中重置
			///save the original renderCell call
			column._originalRenderCell = originalRenderCell;
			///end=================================///

			column._isConfiguredTreeColumn = true;
			column.renderCell = function (object, value, td, options) {
				// summary:
				//		Renders a cell that can be expanded, creating more rows

				var grid = column.grid,
					level = Number(options && options.queryLevel) + 1,
					mayHaveChildren = !grid.collection.mayHaveChildren || grid.collection.mayHaveChildren(object),
					expando, node;

				level = grid._currentLevel = isNaN(level) ? 0 : level;
				expando = column.renderExpando(level, mayHaveChildren,
					grid._expanded[grid.collection.getIdentity(object)], object);
				expando.level = level;
				expando.mayHaveChildren = mayHaveChildren;

				node = originalRenderCell.call(column, object, value, td, options);
				if (node && node.nodeType) {
					td.appendChild(expando);
					td.appendChild(node);
				}
				else {
					td.insertBefore(expando, td.firstChild);
				}
			};

			var clicked; // tracks row that was clicked (for expand dblclick event handling)

			this._treeColumn = column;

			var grid = this,
				colSelector = '.dgrid-content .dgrid-column-' + column.id;

			if (typeof column.renderExpando !== 'function') {
				column.renderExpando = this._defaultRenderExpando;
			}

			// Set up the event listener once and use event delegation for better memory use.
			this._treeColumnListeners.push(this.on(column.expandOn ||
				'.dgrid-expando-icon:click,' + colSelector + ':dblclick,' + colSelector + ':keydown',
				function (event) {
					var row = grid.row(event);
					if ((!grid.collection.mayHaveChildren || grid.collection.mayHaveChildren(row.data)) &&
						(event.type !== 'keydown' || event.keyCode === 32) && !(event.type === 'dblclick' &&
						clicked && clicked.count > 1 && row.id === clicked.id &&
						event.target.className.indexOf('dgrid-expando-icon') > -1)) {
						grid.expand(row);
					}

					// If the expando icon was clicked, update clicked object to prevent
					// potential over-triggering on dblclick (all tested browsers but IE < 9).
					if (event.target.className.indexOf('dgrid-expando-icon') > -1) {
						if (clicked && clicked.id === grid.row(event).id) {
							clicked.count++;
						}
						else {
							clicked = {
								id: grid.row(event).id,
								count: 1
							};
						}
					}
				})
			);

			if (has('touch')) {
				// Also listen on double-taps of the cell.
				this._treeColumnListeners.push(this.on(touchUtil.selector(colSelector, touchUtil.dbltap),
					function () {
						grid.expand(this);
					}));
			}

		}

	});

**Comment by kfranqueiro** [comment]
Thanks for reporting this.  I believe this is already partially fixed on master and the dev-1.0 and dev-0.4 branches since #1255 was fixed.

I also notice you're restoring the original `renderCell`; I suppose I'm wondering what kind of use case you have that calls for reusing the same column in a non-tree scenario?  Otherwise the code in `Tree` in 0.4.1 and 1.0.0 already avoids repeatedly wrapping it.

**Comment by riaeasy** [comment]
Thanks for reply!
We are developing the RIAEasy need to dynamically reconstruct at runtime, i.e., the presence of the treeGrid.set ('columns', treeGrid.columns) application scenarios although the columns has not changed.
In addition, we change the dgrid.List inheritance chain so that it inherits from dijit._WidgetBase. In List.create,the _applyAttributes is called.

**Comment by kfranqueiro** [comment]
That sounds like the sort of case that #1255 concerned.  Can you try running from dgrid's master branch (or dev-0.4, if you're currently using 0.4.x) and see if that resolves your issue?

**Comment by riaeasy** [comment]
thanks a lot.
This issue has been solved.
