### ISSUE TITLE
column.formatter called for hidden columns

### ISSUE THREAD

**Issue by gbaumgart** [SitePen/dgrid#1263]
Hi,
just noticed that today by random. This can have performance impacts....

**Comment by kfranqueiro** [comment]
This is a necessary evil; columns hidden by the ColumnHider extension aren't actually outright removed from the DOM, and data isn't refreshed when columns are hidden/unhidden using the extension.  Cell rendering still happens at the same time for all columns present in the structure passed to the grid, so it's necessary to call all formatters/etc. for consistency.

ColumnHider is definitely a feature more focused on cosmetics and UX than performance.  If you really don't want to incur the rendering expense for unused columns, you're better off stripping them from the column structure completely (but remember that resetting the column structure _will_ incur a refresh).

**Comment by gbaumgart** [comment]
allright, thanks Ken.
