### ISSUE TITLE
About ColumnSet.postCreate

### ISSUE THREAD

**Issue by riaeasy** [SitePen/dgrid#1267]
Hi!
I have a doubt, In ColumnSet.postCreate, line 202, 
aspect.after(this, 'expand', function (promise, args){}
can release properly when destroy?

**Comment by kfranqueiro** [comment]
This aspect doesn't need to be explicitly removed upon destruction since it is self-referencing - if the grid is destroyed and no references to it exist any longer, it will be GC'd regardless.

[dijit/_WidgetBase](https://github.com/dojo/dijit/blob/1.10.4/_WidgetBase.js#L953) has a similar pattern.
