### ISSUE TITLE
OnDemandList: Row ends up in wrong place (after last preload node) when re-inserted

### ISSUE THREAD

**Issue by kfranqueiro** [SitePen/dgrid#1277]
This can be reproduced via unit test in one of two ways:

* Add a `noDataMessage` to the `widget` instance created in `itemAddEmptyStoreTest` in `test/intern/core/trackable.js` (i.e. add `widget.noDataMessage = 'test';` after [L187](https://github.com/SitePen/dgrid/blob/e7f42519ff965c90596ae6b821785f69695f3c49/test/intern/core/trackable.js#L187)
* Checkout my `1275-singlequery-tree` branch and run the `trackable` unit test module, which now always runs into this issue because I changed OnDemandList to consistently always add `noDataNode` even if there is no message

Manual repro steps using `test/OnDemand.html`:

1. Click the "Set to empty store" button under the first grid
1. In console, run `grid.collection.put({ id: 42, col1: 'foo' })` twice
1. After the first run, the row is properly placed in between the two preload nodes.  However, on the second run, it's after the second preload node.

**Comment by msssk** [comment]
This is fixed in all 3 described cases by ensuring consistent placement of the `noDataNode`.

* [fix branched off master](https://github.com/msssk/dgrid/commit/46efdeb3901d2a4e4d16462e28114d751487002d)
* [merged into 1275-singlequery-tree](https://github.com/msssk/dgrid/commit/c0b4e1ba1f5b5b680aa75dc5c4d60d774bd7583f)

The `noDataNode` was sometimes being placed after the preload nodes (instead of between them), and that was in turn leading to misplacement of the newly inserted row. Unfortunately, I can't say I've figured out the intended pattern for preload node creation and placement for all scenarios, so it's possible there is some reason that the `noDataNode` was not being placed consistently.

With this fix we have 3 or more places that duplicate the not-quite-trivial logic:

```javascript
this.contentNode.insertBefore(this._createNoDataNode(), this._getFirstRowSibling(this.contentNode))
```

It seems like we should try to encapsulate that somewhere - but where? Any reason it shouldn't be in [`_createNoDataNode`](https://github.com/kfranqueiro/dgrid/blob/05896570cd1a0e70cf2f3299149baf9f9783ec89/_StoreMixin.js#L209-L218)? The existing code follows the pattern of simply creating the node and requiring the caller to place it, but if they all do the same placement, maybe placement should be captured within that method as well?

**Comment by kfranqueiro** [comment]
Have you tested this fix in environments other than `OnDemandList`?  Pretty sure that is the only thing that actually *defines* `_getFirstRowSibling`, so this would cause errors elsewhere.

Meanwhile, the reason that `_createNoDataNode` only creates and doesn't place is precisely because `OnDemandList` has more specific logic about where `noDataNode` gets placed.  What you may have uncovered, though, is that there are cases where `_StoreMixin` is handling this centrally but that ends up placing it inappropriately in the case of `OnDemandList`, so this is still a good catch.

**Comment by kfranqueiro** [comment]
I've managed to fix this based on what @msssk narrowed down, and I was also able to centralize more of the logic like he suggested.  I'll likely end up squashing this into my SingleQuery commit where the rest of the refactoring took place and add a note to its commit message, but here's the direct diff between what was on the 1275 branch and what it looks like after fixing it:

```diff
commit 75074e5f12bc332cea931b39ae7bdfcac060ed52
Author: Kenneth G. Franqueiro <kfranqueiro@sitepen.com>
Date:   Thu Apr 28 12:01:29 2016 -0400

    Fix and further centralize noDataNode placement behavior

diff --git a/OnDemandList.js b/OnDemandList.js
index 4d2e9f3..7eabb53 100644
--- a/OnDemandList.js
+++ b/OnDemandList.js
@@ -164,9 +164,8 @@ define([
 				// Render the result set
 				return self.renderQueryResults(results, preloadNode, options).then(function (trs) {
 					return results.totalLength.then(function (total) {
-						var trCount = trs.length,
-							parentNode = preloadNode.parentNode,
-							noDataNode = self.noDataNode;
+						var trCount = trs.length;
+						var parentNode = preloadNode.parentNode;
 
 						if (self._rows) {
 							self._rows.min = 0;
@@ -179,12 +178,10 @@ define([
 						}
 						// now we need to adjust the height and total count based on the first result set
 						if (total === 0 && parentNode) {
-							if (noDataNode) {
-								domConstruct.destroy(noDataNode);
-								delete self.noDataNode;
+							if (self.noDataNode) {
+								domConstruct.destroy(self.noDataNode);
 							}
-							noDataNode = self._createNoDataNode();
-							parentNode.insertBefore(noDataNode, self._getFirstRowSibling(parentNode));
+							self._insertNoDataNode(parentNode);
 						}
 						self._calcAverageRowHeight(trs);
 
diff --git a/_StoreMixin.js b/_StoreMixin.js
index d4062b3..8c1e405 100644
--- a/_StoreMixin.js
+++ b/_StoreMixin.js
@@ -206,15 +206,18 @@ define([
 			}
 		},
 
-		_createNoDataNode: function () {
+		_insertNoDataNode: function (parentNode) {
 			// summary:
 			//		Creates a node displaying noDataMessage.
 
-			this.noDataNode = domConstruct.create('div', {
+			parentNode = parentNode || this.contentNode;
+			var noDataNode = this.noDataNode = domConstruct.create('div', {
 				className: 'dgrid-no-data',
 				innerHTML: this.noDataMessage
 			});
-			return this.noDataNode;
+
+			parentNode.insertBefore(noDataNode, this._getFirstRowSibling && this._getFirstRowSibling(parentNode));
+			return noDataNode;
 		},
 
 		_emitRefreshComplete: function () {
@@ -247,7 +250,7 @@ define([
 			var result = this.inherited(arguments);
 
 			if (!this.collection) {
-				this.contentNode.appendChild(this._createNoDataNode());
+				this._insertNoDataNode();
 			}
 
 			return result;
@@ -459,7 +462,7 @@ define([
 			// Check to see if we are now empty...
 			if (!preserveDom && (this.up(row).element === rowElement) && (this.down(row).element === rowElement)) {
 				// ...we are empty, so show the no data message.
-				this.contentNode.appendChild(this._createNoDataNode());
+				this._insertNoDataNode();
 			}
 
 			var rows = (options && options.rows) || this._rows;
diff --git a/extensions/Pagination.js b/extensions/Pagination.js
index c89f787..e6e86cb 100644
--- a/extensions/Pagination.js
+++ b/extensions/Pagination.js
@@ -572,7 +572,7 @@ define([
 								domConstruct.destroy(grid.noDataNode);
 								delete grid.noDataNode;
 							}
-							grid.contentNode.appendChild(grid._createNoDataNode());
+							grid._insertNoDataNode();
 						}
 
 						// Update status text based on now-current page and total.
diff --git a/extensions/SingleQuery.js b/extensions/SingleQuery.js
index 2ff7314..a2d4cd3 100644
--- a/extensions/SingleQuery.js
+++ b/extensions/SingleQuery.js
@@ -35,7 +35,7 @@ define([
 					self._total = total;
 
 					if (!total) {
-						self.contentNode.appendChild(self._createNoDataNode());
+						self._insertNoDataNode();
 					}
 				});
 
```
