### ISSUE TITLE
Add function to focus (possibly not rendered at the moment) row in OnDemandList

### ISSUE THREAD

**Issue by zub2** [SitePen/dgrid#1279]
AFAIK OnDemandList does not have a function to scroll to and focus a row that might not be rendered at the moment because it's outside of the rendered area.

It can be implemented by calculating the y offset where the row should be rendered, scrolling to that offset, and focusing the row once rendering is finished.

Implementing this from the outside requires using quite some internal knowledge of the list (e.g. iterating the list of preload nodes, hooking to after-_processScroll, doing calculations with rowHeight). So it would be best implemented in the List.

**Comment by kfranqueiro** [comment]
This assumes that you already know the index and thus can compute the Y offset of the item you want to focus...  but how do you know that if the item has never been loaded/rendered?  That's generally why this hasn't been implemented.

If you're talking purely in terms of indices, you can call `grid.scrollTo({ y: index * grid.rowHeight })` to perform the operation you're describing.  (This is also generally assuming that all rows are the same height, which is another assumption that such an API would need to make without having already rendered all items.)

**Comment by zub2** [comment]
You're right - passing row ID into the call would not be good. The list would have to search through the collection to find the index, which is something one would not want to do in many stores. (It's something I'm OK with in my specific store though.) What if the row index was passed instead?

I thought both List and OnDemandList know the row indices. What is row.node.rowIndex? My understanding was that generally for OnDemandList there is a "top" preload, then there are rows, and there is a bottom preload. And the code knows how many rows do the top and bottom preload elements represent - in my understanding this is what preload.count is. (I also see in the code that there can be more preloads though I don't understand when does this happen. Either way, still each preload represents a known number of rows.)

As for row heights: The OnDemandList does display a scroll bar. Looking at the code my understanding was that it always calculates the average row height of the currently rendered rows and then uses these to scale the preloads. So it's approximate but the assumption that using average height sort-of works is already being made.

As for your suggestion: I thought one could find the preload inside of which the given row would be rendered, then scroll to y = preload.node.offsetTop + (rowIndex - rowIndexPreloadStart)*rowHeight [this is the average height of the currently rendered rows]. This triggers row rendering at the new position. The newly-rendered row is certainly not guaranteed to appear at the calculated position and OnDemandList._processScroll() is quite complex, so I'm not sure where are the newly created rows placed, but there is a specific number of rows which are created, regardless of their actual heights. (What is the y offset of the first created row? If I read the code correctly, the preload elements are eventually resized to match the new average rowHeight. If this is done after the row indices to be rendered are determined then I think the above-calculated scroll position should ensure the requested row will be created too.) If the requested row is created in OnDemandList._processScroll(), one could then focus it (and potentially scroll again, which is a bit ugly).

If there was a way how to trigger row rendering around given y-offset (w/o doing a scroll first), one could avoid the double scrolling issue.

**Comment by msssk** [comment]
>  one could find the preload inside of which the given row would be rendered, then scroll to y = preload.node.offsetTop + (rowIndex - rowIndexPreloadStart)*rowHeight [this is the average height of the currently rendered rows]. This triggers row rendering at the new position. The newly-rendered row is certainly not guaranteed to appear at the calculated position [...] the preload elements are eventually resized to match the new average rowHeight. [...] If the requested row is created in OnDemandList._processScroll(), one could then focus it (and potentially scroll again, which is a bit ugly).

This is about the best that can be done, and it has been done, and it's never provided an experience that is reliable and pleasant enough for the end-user to be included in dgrid.
