### ISSUE TITLE
Why doesn't the destroy() function in List.js call this.inherited(arguments) ?

### ISSUE THREAD

**Issue by ghost** [SitePen/dgrid#1282]
The destroy() function in dgrid/List.js doesn't call this.inherited(arguments), which is breaking the inheritance chain for me when I mix it in with other files.  For example, if I return this:
dojo_declare("myWidget", [_Destroyable, List, OnDemandList], { ... })
then OnDemandList and List's destroy() functions will be called, but _Destroyable's destroy() function won't, because List.js breaks the inheritance.

Any idea why its like this, is it a bug?

Thanks

**Comment by msssk** [comment]
dgrid is not part of Dijit, and it is not a Dijit widget. `dgrid/List` is a top-level module, not a mixin. If you want to augment `List` behavior, you need to mix another module into it.

Correct:
```javascript
declare(List, [Mixin1, Mixin2], { ... })
```

Incorrect:
```javascript
declare(MyBaseClass, [List, Mixin1], { ... })
````

Additionally, `OnDemandList` already inherits from `List`, so mixing `List` and `OnDemandList` together is not a correct approach.
