### ISSUE TITLE
Is it possible to drag and drop from an external source onto dgrid? 

### ISSUE THREAD

**Issue by kvenkataMathworks** [SitePen/dgrid#1286]
I am using dgrid to display the file system. I wanted to know if there was a way to be able to drag a file onto a dgrid row and upload it there. 

Thanks.

**Comment by msssk** [comment]
dgrid DnD demos:
https://dgrid.io/js/dgrid/test/extensions/DnD.html

Please direct support and usage questions to the [appropriate channels](https://dojotoolkit.org/community/).
