### ISSUE TITLE
Is there a way to prevent the column header from getting wider than the parent container?

### ISSUE THREAD

**Issue by kvenkataMathworks** [SitePen/dgrid#1287]
In dgrid laboratory, I can resize the column to go longer than the parent which results in a horizontal scroll bar. Is there a way to disable this from happening i.e. disallowing the table to exceed it's parent width and hence not showing a horizontal scroll bar? 
For e.g.
div.dgrid-header-row has width 100px
But th.dgrid-column-First_Name can have width 120px which results in a horizontal scroll bar because the total width of the table is longer than the parent div.

Is there a way to limit the total header width to a maximum value?

**Comment by msssk** [comment]
There is no built-in support for this behavior, but the `dgrid-columnresize` event is [cancelable](https://github.com/SitePen/dgrid/blob/master/doc/components/extensions/ColumnResizer.md#events).

Please keep support-related questions in the appropriate channels:

* [StackOverflow](http://stackoverflow.com/questions/tagged/dgrid)
* [#dojo on freenode IRC](http://dojotoolkit.org/chat)
* [dojo mailing list](http://dojotoolkit.org/community/)
