### ISSUE TITLE
Adding ColumnResizer and ColumnHider messes with minWidth

### ISSUE THREAD

**Issue by kvenkataMathworks** [SitePen/dgrid#1288]
Reproduction steps:
1. Enable ColumnHider and ColumnResizer
2. Hide "Last Name" column.
3. Expand "First Name" column.
4. Show "Last Name" Column.

Last Name column now can be resized to 0 px.

**Comment by msssk** [comment]
Can you provide some more details on how to reproduce this issue?

Following the provided directions in the [dgrid Laboratory](http://dgrid.io/js/dgrid/demos/laboratory/) I am not able to reproduce it. Resizing the "Last Name" column always results in it respecting the minimum width. If I increase the width of the "First Name" column, I can increase it enough that "Last Name" is no longer immediately visible, but in that case the column content exceeds the grid's width and a horizontal scrollbar is provided to scroll to the right and see the "Last Name" column.

**Comment by msssk** [comment]
Closing due to age and inactivity. Please provide a reproducible test case if you continue to experience the problem.
