### ISSUE TITLE
Rest useRangeHeaders not working with Trackable & cachingStore

### ISSUE THREAD

**Issue by lethevimlet** [SitePen/dgrid#1289]
I'm trying to create a realtime fetching Grid with pagination using Rest store, Trackable, and a cachingStore, the idea is to give the grid the capability to fetch new data each 'x' seconds without making the grid blink on each refresh.

I managed to do so by using Trackable and calling fetch on a setTimeout, the only problem is pagination with range headers is not working as expected.

The server is responding with a list of 5 items and a "Content-Range: items 0-5/20". I expect the grid to display 4 pages since I'm telling dgrid they are 20 items, and on pagination click to send the usual range params, instead pagination only displays one page and shows a total of 5 items.

No matter what I do I cant manage to make it display the correct pagination and I'm wondering if this could be a unexpected behaviour when using trackable or cachingStore in conjunction with Rest store.

Here is the grid code:

```
  require([
        'dojo/_base/declare',
        'dstore/Rest',
        'dstore/Memory',
        'dstore/Trackable',
        'dstore/Cache',
        'dgrid/Grid',
        'dgrid/extensions/Pagination',
        "dgrid/extensions/CompoundColumns",
        "dgrid/extensions/ColumnResizer",
        "dgrid/Keyboard",
        "dgrid/Selection",
        'dojo/domReady!'
      ], function (declare, Rest, Memory, Trackable, Cache, Grid, Pagination, CompoundColumns, ColumnResizer, Keyboard, Selection) {
        var restStore = new Rest({
          useRangeHeaders: true,
          target: '/rest/example/'
        });

        var store = Cache.create(restStore, {
          cachingStore: new (Memory.createSubclass(Trackable))({})
        });

        var grid = (declare([Grid, Pagination, Keyboard, Selection, CompoundColumns, ColumnResizer]))({
          collection: store.cachingStore,
          columns: {
            id: 'ID',
            name: 'Name',
            description: 'Description'
          },
          loadingMessage: 'Loading...',
          // pageSizeOptions: [ 10, 15, 20, 25 ],
          // pagingLinks: 1,
          rowsPerPage: 5,
          pagingTextBox: true,
          firstLastArrows: true
        }, 'grid');

        grid.startup();
        store.fetch();

        // To test query real time modification
        // var flag = true;
        //
        // setInterval(function () {
        //   if (flag) {
        //     restStore.target = "/rest/example";
        //   } else {
        //     restStore.target = "/rest/example/test";
        //   }
        //   flag = !flag;
        //   store.fetch();
        // }, 2000);
      });

```

Here is the server response:

[{"id": "1", "name": "Sergio", "description": "one"},{"id": "2", "name": "Jesus", "description": "three"},{"id": "3", "name": "Jesus", "description": "three"},{"id": "4", "name": "Sergio", "description": "three"},{"id": "5", "name": "Sergio", "description": "two"}]

with the following response headers:

```
Connection:keep-alive
Content-Length:260
Content-Range:items 0-5/20
Content-Type:text/html

```

And this is the grid that should display 4 pages but instead shows 1:

![image](https://cloud.githubusercontent.com/assets/2963923/15655856/598946ae-26a1-11e6-9e15-ff6d82fdf474.png)

Am I missing something here, or this is how is supposed to behave. 

Thanks for your time.

**Comment by msssk** [comment]
Closing this due to age and inactivity. With the current versions of dgrid and dstore and this code I get expected behavior - 5 rows rendered per page, 4 pages available for navigation.
