### ISSUE TITLE
dgrid 4.0 checkbox issue

### ISSUE THREAD

**Issue by mforbes5** [SitePen/dgrid#1290]
Issue with dgrid 4.0 with Checkbox and receiving data from the server.
I have the current grid:
var CustomGrid = declare([OnDemandGrid, DijitRegistry, Selection, Selector]);
var self = this;
this.grid = new CustomGrid({
collection: this.store,
columns:
{
bValue: { label: "", sortable: false, selector: "checkbox"},
name: self._createCell({ label: i18n.selectAll, sortable: false})},
selectionMode: "single",
allowSelectAll: true
}, this.gridNode);
this.grid.startup();
JSON:
{bValue: true, name: “Alex”, id: index++}
{bValue: false, name: “Marc”, id: index++}
{bValue: true, name: “Stella”, id: index++}
For some reason the checkbox in the grid remain unchecked for the data with the value of “true”. Is there something missing?

**Comment by msssk** [comment]
dgrid's selection functionality is designed for temporary tracking of selection state. It neither loads nor stores selection state to the data store.
