### ISSUE TITLE
columnresizer in edge browser

### ISSUE THREAD

**Issue by gerpres** [SitePen/dgrid#1293]
the column-resizer-icon seems to be too large for the edge-scrollbar - the header overlaps the icon a few px.

**Comment by msssk** [comment]
I'm not seeing any issues with `ColumnResizer` - are you referring to the `ColumnHider` "plus" icon that appears above the scrollbar?

**Comment by gerpres** [comment]
yes, exactly - see

http://dgrid.io/demos/dTuned/

the icon is too large
