### ISSUE TITLE
Editor.js method refresh() does not return value from this.inherited(arguments);

### ISSUE THREAD

**Issue by eniewold** [SitePen/dgrid#1299]
The Editor.js extension method refresh() does not return the value as returned from calling this.inherited(arguments) base class.

This causes problems when declaring classes using the Editor and the OnDemandGrid using the promise returned from the latter.

**Comment by edhager** [comment]
Landed in master, commit 83e58c45fd1783b9197d11d5a26e7308f74321ad.  Thanks!
