### ISSUE TITLE
OndemandGrid not removing all items from trackable store

### ISSUE THREAD

**Issue by wildcatcs** [SitePen/dgrid#1305]
When an OnDemandGrid is given a trackable store with a moderate number of items, when all of the items are removed and a new set added not all of the original rows are deleted.  This only happens if one of the columns is sorted.

Code simply removes all items from a trackable gird, than adds a new 200 items to the collection each time the refresh button is pressed.  It works fine unless the grid is sorted on the Integer column.  Then the grid's sort gets messed up and items that were  removed from the collection are not removed from the grid.  Changing the sort cleans up the bad rows.

Realize this would probably be a case for just setting a new collection, but this problem also happens if you are removing a large portion of the overall set of data.

Sample code attached (warning not pretty, just hacked up performance.html)
[performance.txt](https://github.com/SitePen/dgrid/files/438515/performance.txt)

**Comment by msssk** [comment]
Can you provide some more details on the bug you are observing?

1. What actions are you performing?
1. What are you expecting to happen?
1. What are you observing happening?

I don't see any problem that matches what you are describing, but I am looking into this issue:

1. Load the test page
1. Click the "integer" column header to sort (ascending)
1. Click the "refresh" button
    1. Result: table rows are rendered
1. Click the "integer" column header to sort (descending)
1. Click the "refresh" button
    1. Expected: the table rows should render
    1. Result: the table has no rows rendered

**Comment by wildcatcs** [comment]
1. Downloaded performance.txt renamed it and dropped into test folder of latest dgrid (replacing existing file)
2. Open the file via double clicking on it
3. Press the refresh button a few times fairly rapidly (everything works fine)
4. Sort the grid by the integer column and scroll through the list (should be sorted nicely)
5. press refresh again 
6. The sort order is not the same as before the refesh was pressed even though the column is still sorted.
7. Press refresh again
8. Scroll through the list, you will start to see duplicate integers showing up even though they have all been removed
9. Resort the grid and everything will be correct again, until refresh is pressed.

This is on Chrome (52) safari and I do believe we've seen it on firefox but haven't personally tried it.

Let me know if there is anything I can help you with.

**Comment by msssk** [comment]
@wildcatcs Following your instructions in Chrome 52 I don't see any issues. The ids will change each time you press refresh, but I'm seeing consistently correct sorting and no duplicate values in the integer column.

**Comment by wildcatcs** [comment]
I've played some more with the example and realized I wasn't testing with the version I thought I was.  I was using version 0.4.0 of dgrid with dstore 1.0.3.  I upgraded to dgrid 1.1 and the behavior is definitely different but not bug free.

I can sort ascending  and press refresh tell my heart is content and all is well (the original issue).  However if I sort descending and press refresh the grid goes blank.  There are no exceptions.  Pressing to change the sort direction causes the grid to repopulate.

Attaching some screen shots:
Loaded the page, pressed refresh , sorted descending (screen shot1), pressed refresh (screen shot2), resorted (screen shot3) 
![screen shot1](https://cloud.githubusercontent.com/assets/2798513/18154835/f4e03b08-6fbc-11e6-8f22-591ea2ab7874.png)
![screen shot2](https://cloud.githubusercontent.com/assets/2798513/18154836/f4e39db6-6fbc-11e6-9c41-2ecda1ee44ca.png)
![screen shot3](https://cloud.githubusercontent.com/assets/2798513/18154837/f4e4586e-6fbc-11e6-9906-b25c84cc74c9.png)

Again, sorry about my confusion on the version.

**Comment by msssk** [comment]
When the "integer" column is sorted ascending, the test page's "Refresh" button removes rows from top to bottom. When the "integer" column is sorted descending the rows are removed from bottom to top. `OnDemandList#_processScroll` handles row removal differently depending on whether or not the rows are visible, and in the case of bottom to top removal a number of non-visible rows are removed. This is the reason that "sort ascending -> refresh" works while "sort descending -> refresh" fails. If you reverse the order of the `col.remove` loop in the `go` function invoked by the "Refresh" button then you see the opposite: "sort ascending -> refresh" _fails_ while "sort descending -> refresh" succeeds.

When `rows.max` is set to less than 0 [this check](https://github.com/SitePen/dgrid/blob/f9f73caaf70b457e1ac43e7efcad30e5c531822b/_StoreMixin.js#L569) always fails, preventing addition of new items to the store from [inserting new rows](https://github.com/SitePen/dgrid/blob/f9f73caaf70b457e1ac43e7efcad30e5c531822b/_StoreMixin.js#L601).
