### ISSUE TITLE
Keyboard module - dgrid 0.3

### ISSUE THREAD

**Issue by matejlednar** [SitePen/dgrid#1311]
If I have dijit/form/Select as content of the row, I am losing focus. I am not able to open popup menu over label, only down icon is working.

postCreate() - handleEvents() is problem

current statement
return target.type && (!delegatingInputTypes[target.type] || event.keyCode == 32);

my suggestion
var DijitFormSelect = query(event.target).parents(".dijitSelect")[0];
return  (target.type && (!delegatingInputTypes[target.type] || event.keyCode == 32) || **DijitFormSelect**);

The row structure is below.

![image](https://cloud.githubusercontent.com/assets/2221688/18433960/afebb20c-78ea-11e6-994b-420de0344084.png)

**Comment by msssk** [comment]
I'm not sure exactly what scenario you're describing, but in investigating I did observe a bug in using `dijit/form/Select` with `editOn`. That issue is fixed in #1465. If you continue to experience problems please file an issue with a test case so we can investigate.
