### ISSUE TITLE
Is it possible to sort a column which contains nested object properties?

### ISSUE THREAD

**Issue by mykhet** [SitePen/dgrid#1317]
```javascript
someObj = {
   "name": "John",
   "basicInfo": {
        "dateOfArrival": 1475482400000
   }
}
```

I have two columns in my grid: Name & Date of Arrival. I am not able to sort by dateOfArrival. If I pull DOA out of basicInfo as direct property of someObj, the sort works fine. 

my sort query looks like:
```javascript
sortByDOA: [
  {
    "attribute": "basicInfo.dateOfArrival",
    "descending": true
  }
]
```
Is it possible to sort nested objects in dgrid.

Thanks in advance.

**Comment by msssk** [comment]
Sort logic has been encapsulated in the [`List#_applySort`](https://github.com/SitePen/dgrid/blob/adf4d5923465af92387db0c1ee170c974800f964/List.js#L806-L833) method to allow for custom sort behavior by overriding this method.
