### ISSUE TITLE
dgrid in dijit/layout/stackcontainer not being properly destroyed - possible memoryleak

### ISSUE THREAD

**Issue by gerpres** [SitePen/dgrid#1318]
if the StackContainer is being destroyed, it tries to destroy it's children too - unfortunately it calls 'removeChild(child)' before destroying it - the dgrid cleanup mechanism doesn't work any more, because 

`document.getElementById(id)`

doesn't find the row, because it's not part of the DOM anymore. 
therefore removeRow() is not called and if you use widgets in your rows, those widgets may not be destroyed.

any ideas how to solve this?

**Comment by gerpres** [comment]
I replaced the

`byId(id)`

in

`List.cleanup()`

with following code

```
query("[id="+miscUtil.escapeCssIdentifier(i)+"]",this.domNode).forEach(function(rowElement) {
	if(rowElement){
		self.removeRow(rowElement, true);
	}
});
```

to make destroy work again.
I couldn't use CSS's  #id selector - may access the document-id-mapping too 👎

**Comment by kfranqueiro** [comment]
Interesting. Example repro from test page:

1. Load http://dgrid.io/js/dgrid/test/dijit_layout.html
2. `require('dojo/aspect').before(require('dgrid/List').prototype, 'removeRow', function(){ console.log('removeRow'); })`
3. `dijit.byId('tc').destroyRecursive()`

OTOH, if you were to call `destroyRecursive` on the BorderContainer (`bc`) instead, you'd see 25 `removeRow` calls logged for the grid in the left sidebar.

**Comment by gerpres** [comment]
that's the problematic code...

dijit/layout/StackContainer

```
destroyDescendants: function(/*Boolean*/ preserveDom){
			this._descendantsBeingDestroyed = true;
			this.selectedChildWidget = undefined;
			array.forEach(this.getChildren(), function(child){
				if(!preserveDom){
					this.removeChild(child);
				}
				child.destroyRecursive(preserveDom);
			}, this);
			this._descendantsBeingDestroyed = false;
		}
```

it removes the children before destroying them
