### ISSUE TITLE
Header checkbox disabled not allowing to select all

### ISSUE THREAD

**Issue by cgaeking** [SitePen/dgrid#1322]
If my allowSelect function returns a false on the FIRST row, the header checkbox is disabled although I have set allowSelectAll to true.
If at the first row the allowSelect returns true, the header checkbox is enabled. It should be always enabled, or if at least one enabled checkbox is in the data.

**Comment by msssk** [comment]
There is no logic enforcing this in `dgrid/Selector.js`. It is more likely that your `allowSelect` function is returning `false`. The `allowSelect` function is evaluated for each row, including the header row. The `allowSelect` function will receive an empty object for the row data when rendering the header row and should respond appropriately.
