### ISSUE TITLE
OnDemandGrid with indefinite totalLength

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1323]
My app uses OnDemandGrid with a custom dstore implementation.

I've implemented the fetch() and fetchAll() methods of the store to retrieve data. All is well insofar as I can return an accurate totalCount along with the data.

However, I just came across a edge case where the server is just unable to give me a total count. This means that I cannot return an accurate totalLength when calling fetch() or fetchAll(). I tried assigning null to totalLength but dgrid stops looking after the first page.

Is there provision for infinite scrolling with unknown totalLength within dgrid? If not, my first thought is to re-calculate totalLength during each fetch() call by adding the page size to the number of rows retrieved so far. Would this be the recommended approach or I am missing a better solution?

**Comment by msssk** [comment]
dgrid only supports rendering known datasets, and as such is not suitable for endless scrolling. In order to provide virtual scrolling dgrid **must** know the total number of records.
