### ISSUE TITLE
Custom Sort with "dgrid-sort" and OnDemandGrid

### ISSUE THREAD

**Issue by phil0135** [SitePen/dgrid#1330]
Hi, 

I found an issue with using a custom sort function on an OnDemandGrid.
I am defining the custom sort in the way:

`this.grid.on("dgrid-sort", lang.hitch(this, function(grid, parentEvent, data){
/* Sorting is done here */
}))`

This works perfectly fine, as long as the number of rows does not exceed minRowsPerpage. In this case as soon as the second rendering phase starts, sorting does not work any more. 

I am using a 0.3.17 and dojo/store/Memory.
I would appreciate any kind of help to solve this problem.

Best regards, 

Philipp

**Comment by dylans** [comment]
@phil0135 it would help to know if you see the same issue with dgrid 0.4.x, 1.0.x, or 1.1.x?

**Comment by phil0135** [comment]
Hello @dylans ,
thanks for the reply. Seems to be fixed (at least in 1.1, see http://jsfiddle.net/gcp0s6h4/6/).
Unfortunately I cannot migrate to "dgrid" >= 0.4.x that easily, it's planned for next year. 
Does somone know a workaround for this problem in 0.3.17?

Best regards, Philipp

**Comment by phil0135** [comment]
Hello, 

here is a workaround for everyone that cannot update "DGrid" for the moment. 
You can extend dojo/store/Memory do get the correct behaviour.
`
var CustomMemory = declare(Memory, {
    query: function (query, queryOptions) {
        var sort = queryOptions && queryOptions.sort;
        sort = (sort!==undefined&&sort[0]!==undefined)?sort[0]:sort;
        /* Replace sort array with a function that performs custom sorting for column   "special_col" */
        if (sort && sort.attribute == "special_col") {
            queryOptions.sort = function (a, b) {
	        var result = function(a, b){
                    /* Do your custom sort */
                 };
                 if(sort.descending)
                     result = result * -1;
                 return result;
              }
        }
        return this.inherited(arguments);
    }
});
`

HTH, Philipp
