### ISSUE TITLE
DOM getting too large for Dgrid tables....

### ISSUE THREAD

**Issue by malliky** [SitePen/dgrid#1331]
We are having issues with DOM on IE 11 getting too large and too fast for our NxM Dgrid tables (with N about 100, and M about 200), causing the rendering and scrolling to be extremely slow; and almost crippling IE. Is this a known issue? And if so, are there any remedies/fixes that we can use? Thanx.

**Comment by dylans** [comment]
What are your various settings for virtual scrolling? You may want to be very aggressive and only render the rows actually shown on the screen, to limit yourself to say 100x25 or 100x50 maybe? There may be some other tricks to be employed perhaps.

In general 100 column grids on IE are particularly problematic as we don't have horizontal virtual scrolling, only vertical virtual scrolling. That is something we're aiming to make better with dgrid 2 with our efforts to switch to a vdom approach...

**Comment by msssk** [comment]
IE is known to have issues with heavy DOM structures. The solution is to simplify the DOM or use a better browser. As mentioned, dgrid does not support horizontal virtual scrolling, so excessive columns and complicated cell contents unavoidably create heavy DOM.
