### ISSUE TITLE
IE8 Does not support getElementsByClassName

### ISSUE THREAD

**Issue by yohanleafheart** [SitePen/dgrid#1336]
Unfortunately, due to a couple of clients I still have to support IE8, I'm using now a Grid (dGrid 1.1) with the tree mixin. Backed by a dstore/Request with a dstore/Tree mixin. On IE8 the tree does not load. I got a couple of bugs related to it:

 - OnDemandList.js:259 - It uses **getElementsByClassName** which is not supported on IE8 so it breaks with "document does not have method or property". It should be replaced by this.contentNode.querySelectorAll('dgrid-row') which is crossbrowser

**Comment by edhager** [comment]
We stopped testing IE8 in v1.0 so fixing this in the next version will probably lead to more IE8 bugs.  But, this is also an issue in 0.4.2 which is supposed to support IE8.

**Comment by yohanleafheart** [comment]
So, since I accidentally opened another ticket with this same issue, and I'm not good with Pull Requests the fix is to change line OnDemandList:259 

`- this._calcAverageRowHeight(this.contentNode.getElementsByClassName('dgrid-row'));`
`+ this._calcAverageRowHeight(this.contentNode.querySelectorAll('.dgrid-row'));`

This is back compatible to IE8

**Comment by dylans** [comment]
PR at #1344

**Comment by edhager** [comment]
Fixes landed in the master and dev-0.4 branches.
