### ISSUE TITLE
Long header names are cut off.

### ISSUE THREAD

**Issue by Sluimers** [SitePen/dgrid#1338]
Dgrid works fine for me, except for the headers. I've got lots of headers and long headers. 
And what happens is that they get cut off like so:

![capture](https://cloud.githubusercontent.com/assets/235767/21684577/727245a2-d35e-11e6-944d-0f6178f102cc.PNG)

**Comment by edhager** [comment]
You can control the width of the columns using CSS.  Take a look at the last grid on this test page:  http://dgrid.io/js/dgrid/test/common_cases.html

Notice the CSS class "field-col1" has a width of 500px.  

dgrid generates class names using the format "field-[property name]"  where "property name" is the name of a property from the source objects you used in the column configuration.

If you don't set the column widths, then dgrid evenly distributes the columns across the width of the grid.  So a combination of setting the grid's width and setting the column widths will determine whether or not horizontal scrollbars appear.

**Comment by dylans** [comment]
Could also probably set text-overflow: ellipsis; on the various columns once the width is set...

**Comment by Sluimers** [comment]
No, setting the correct width of the column was what I wanted.
I have been able to get that right with a for loop and dojoxStyle.insertCssRule.
