### ISSUE TITLE
dGrid 1.1 does not work with IE8 due to getElementsByClassName

### ISSUE THREAD

**Issue by yohanleafheart** [SitePen/dgrid#1343]
Grettings all,

I know dGrid is not longer officially compatible with IE8 but there is a bug happening now which is probably easy to fix (it does not happen on 0.3). The .resize() function on OnDemandList uses getElementsByClassName which is not available on IE8, so it fails.

**Comment by dylans** [comment]
@yohanleafheart ok, fair enough... do you want to create a PR to speed that up? If not, no worries, we'll get to it for the next release.

**Comment by yohanleafheart** [comment]
Hey Dylans, by the way, I just realized I opened this same ticket 25 days ago, I'm sorry, I completely forgot about it. That issue is https://github.com/SitePen/dgrid/issues/1336#issuecomment-270705194 So I think it is probably better to close this as duplicate and use that one. 

I have never done a PR on Github so not sure how to proceed on it, but the fix is on that other issue Just with a typo, it should be _this.contentNode.querySelectorAll('.dgrid-row')_

**Comment by dylans** [comment]
Thanks, will close this in favor of the other ticket.
