### ISSUE TITLE
How do I prevent a row from getting selected on right click? 

### ISSUE THREAD

**Issue by kruthikavenkatathri** [SitePen/dgrid#1354]

**Comment by eQuorumRayNewman** [comment]
I disagree with this change. It broke our user's prior experience with our product. We present a context menu on selected items in a grid (behavior users are accustom to in Windows File Explorer for example). A right mouse click selects the item and presents a context menu for the item. With this release users must now right mouse click and then left mouse click to get the context menu. At a minimum the change should include a property to provide the desired behavior while retaining the previous behavior.
