### ISSUE TITLE
bug? rowHeight not set 

### ISSUE THREAD

**Issue by Jens-dojo** [SitePen/dgrid#1355]
Hi all,

according to some discussions here (#1279), the OnDemandGrid should have a rowHeight property that reflects the average height of all rendered rows.

But the value seems to be always 0.
I checked the source code and I couldn't find a place where it gets set?
Only preload.rowHeight gets set.

Bug ?

**Comment by dylans** [comment]
@Jens-dojo could you share an example for how this is happening? It doesn't sound correct (could be a bug, or could be something in your use cases, etc.).

**Comment by msssk** [comment]
The value is set in the [`_updatePreloadRowHeights`](https://github.com/SitePen/dgrid/blob/59b1a3e1f6bfa6a18b09dad84aa40f86de293af3/OnDemandList.js#L414) method and exposed as a grid property so that extensions can make use of it.
