### ISSUE TITLE
When dragging multiple rows with the DnD extension dgrid can sometimes "lose" a row

### ISSUE THREAD

**Issue by maier49** [SitePen/dgrid#1365]
In the linked JSFiddle, highlight rows 1 and 3, and then drag them below row 2. Row 3 will disappear

https://jsfiddle.net/46qL8ozo/1/

**Comment by edhager** [comment]
This turned out to be a dstore bug:  SitePen/dstore#207.

**Comment by edhager** [comment]
I created a dstore ticket to fix the issue in dstore but I also added a fix to dgrid.  The dgrid fix will improve efficiency.
