### ISSUE TITLE
Column hider button is not displayed on platforms with no scrollbar

### ISSUE THREAD

**Issue by edhager** [SitePen/dgrid#1371]
The fix for #1293 is causing the column hider button to not be visible on platforms like iOS that do not display scrollbars.

**Comment by eQuorumRayNewman** [comment]
The problem that I'm having is when dgrid is constructed without a reference to a domNode and is appended to a node later.  To duplicate the problem change the ColumnHider.html test case like this;
``					grid = window.grid = new (declare([Grid, Keyboard, Selection, ColumnHider]))({
						collection: testStore,
						columns: getColumns()
					});
//					}, "grid");
					document.getElementById("grid").appendChild(grid.domNode);
