### ISSUE TITLE
dgrid 1.2.0 breaks OnDemandGrid with more than 25 items in store

### ISSUE THREAD

**Issue by baraclese** [SitePen/dgrid#1382]
I tested this in Firefox 54 and Chrome 59.
I upgraded from 1.1.0 to 1.2.0 and all my OnDemandGrids break if they contain more than 25 items. For example I have a grid with a button to add new rows, as I add them to the collection they are rendered fine, but then I change the sort order on a column and only 25 rows will be rendered (although the grid is larger than 25 rows). I logged the fetchRangeSync calls to dstore/Memory and see that it only requests the first 25 items. I switch back to dgrid-1.1.0 and see two fetchRangeSync calls for the first 25 and then for the rest.

Reverting commit 8b5594807171a0fb73fde04fc8ae4c550fdf773d fixes the issue.

**Comment by TiBeN** [comment]
I was on the way to post the same issue! Tests availables at this page <http://dgrid.io/js/dgrid/test/OnDemand_promises.html> are broken with firefox 54 and google chrome 59.0.3071.109-1. There is any loading triggers to occurs after the initial 25 rows set.

**Comment by edhager** [comment]
A change was landed that fixes an issue with calculating the average row height.

**Comment by TiBeN** [comment]
Thanks for your work on this issue. I've tested today and confirm it has been fixed.
