### ISSUE TITLE
dgrid 1.2.0: OnDemandGrid pagingDelay/paginMethod options have no effect on Chrome

### ISSUE THREAD

**Issue by TiBeN** [SitePen/dgrid#1383]
After reverting the commit 8b55948, which fixes the issue #1382, dgrid v1.2.0 reveals the following issue, which affects Chrome 59 but not Firefox 54:

The options "pagingDelay" and/or "pagingMethod"  have no effects. This triggers far too many "fetchRange" calls when scrolling quickly using the scrollbar. 

**EDIT**: Seems to be introduced by commit ccfcbc1995f05ccddbbc8443c4380af57605f85b

**Comment by edhager** [comment]
A fix was landed in 13697495fd5e2f6c5cbfb71d4eeeef5fd7b231e1.

I disabled the use of `requestIdleCallback`.  We will need to take another look at the original issue.
