### ISSUE TITLE
Tree Grid initially shows child rows alongside parent rows when used with SingleQuery

### ISSUE THREAD

**Issue by MarvDann** [SitePen/dgrid#1386]
OK I'm using dgrid 1.2 in a simple fashion with the Tree module, a memory dstore and the SingleQuery extension. The problem is the initial load - the child rows are showing alongside the parent rows.
When I click an expander icon, the child rows are removed from the top level and correctly displayed as children of the parent node.

Here is my code:
`<body class="claro">
    <div id="app"></div>
    <script src='dojo/dojo.js'></script>
    <script>
        require([
            "dojo/_base/declare",
            "dojo/dom",
            "dgrid/Grid",
            "dgrid/Tree",
            "dgrid/extensions/SingleQuery",
            "dstore/Memory",
            "dojo/domReady!"
        ], function(declare, dom, Grid, Tree, SingleQuery, Memory) {

            var container = dom.byId("app");

            var data = [{
                id: 0,
                name: "Parent 1",
                hasChildren: true
            }, {
                id: 1,
                name: "Parent 2"
            }, {
                id: 2,
                name: "Child 1",
                parent: 0
            }];

            var columns = {
                name: {
                    label: "Name",
                    renderExpando: true,
                    field: "name"
                }
            };

            var store = new Memory({
                data: data,
                getChildren: function(parent) {
                    return this.filter({
                        parent: parent.id
                    });
                },
                mayHaveChildren: function(object) {
                    return object.hasChildren;
                }
            });

            var treeGrid = declare([Grid, SingleQuery, Tree]);

            var grid = new treeGrid({
                className: "dgrid-autoheight",
                collection: store,
                columns: columns
            }, container);

            grid.startup();
        });
    </script>
</body>`

Initial Load:
![image](https://user-images.githubusercontent.com/14371546/27549264-590ee694-5a93-11e7-85c0-37ff8ec37ad1.png)

After clicking expand icon:
![image](https://user-images.githubusercontent.com/14371546/27549340-8d02847e-5a93-11e7-8a63-fe1b32c98182.png)

**Comment by edhager** [comment]
Hi @MarvDann,

Normally when using the `Tree` extension with `OnDemandGrid`, there are a couple things you must do:

1. When initializing the grid, apply a filter to the store that only returns the parent rows.  In your case that would be `store.filter({parent: undefined})`. 
2. The store's `getChildren` method must apply a filter to the original store, not the filtered collection.

There is a dstore mixin that makes a store class compatible with dgrid's `Tree` extension: https://github.com/SitePen/dstore/blob/master/Tree.js

I updated your example:

```javascript
require([
	"dojo/_base/declare",
	"dojo/dom",
	"dgrid/OnDemandGrid",
	"dgrid/Tree",
	"dgrid/extensions/SingleQuery",
	"dstore/Memory",
	"dstore/Tree",
	"dojo/domReady!"
], function (declare, dom, Grid, Tree, SingleQuery, Memory, TreeStore) {
	var container = dom.byId("app");

	var data = [{
		id: 0,
		name: "Parent 1",
		hasChildren: true
	}, {
		id: 1,
		name: "Parent 2"
	}, {
		id: 2,
		name: "Child 1",
		parent: 0
	}];

	var columns = {
		name: {
			label: "Name",
			renderExpando: true,
			field: "name"
		}
	};

	// ****Updated****  Use the dstore/Tree mixin.
	var store = new (declare([Memory, TreeStore]))({
		data: data,
		mayHaveChildren: function (object) {
			return object.hasChildren;
		}
	});

	var treeGrid = declare([Grid, SingleQuery, Tree]);

	var grid = new treeGrid({
		className: "dgrid-autoheight",
		// ****Updated****  Apply a filter that returns only the parent rows.
		collection: store.filter({parent: undefined}),
		columns: columns
	}, container);

	grid.startup();
});
```

If your reason for using `dgrid\SingleQuery` is to avoid using `OnDemandGrid`, then the example does that.  If you are looking for a solution that applies only one query to a store, then this solution does not achieve that.  This solution applies a query each time a parent row is expanded.  I think you would need to create a custom store implementation to achieve that goal.

**Comment by MarvDann** [comment]
Hi Ed. Thanks for your help.
I understand it now. I added the TreeStore dependency and that seemed to fix things up for me.

I'll show what I ended up with. I had some helper methods on the TreeStore class for getting the root collection and getting the children but I had to reference this.root.filter rather than this.filter for it to work correctly.
`<body class="claro">
    <div id="app"></div>
    <script src='dojo/dojo.js'></script>
    <script>
        require([
            "dojo/_base/declare",
            "dojo/dom",
            "dgrid/Grid",
            "dgrid/Tree",
            "dgrid/extensions/SingleQuery",
            "dstore/Memory",
            "dstore/Tree",
            "dojo/domReady!"
        ], function(declare, dom, Grid, Tree, SingleQuery, Memory, TreeStore) {

            var container = dom.byId("app");

            var data = [{
                id: 0,
                name: "Parent 1",
                hasChildren: true
            }, {
                id: 1,
                name: "Parent 2"
            }, {
                id: 2,
                name: "Child 1",
                parent: 0
            }];

            var columns = {
                name: {
                    label: "Name",
                    renderExpando: true,
                    field: "name"
                }
            };

            var store = new(declare([Memory, TreeStore]))({
                data: data,
                getChildren: function(parent) {
                    return this.root.filter({
                        parent: parent.id
                    });
                },
                mayHaveChildren: function(object) {
                    return object.hasChildren;
                },
                getRootCollection: function() {
                    return this.root.filter({
                        parent: undefined
                    });
                }
            });

            var treeGrid = declare([Grid, SingleQuery, Tree]);

            var grid = new treeGrid({
                className: "dgrid-autoheight",
                collection: store.getRootCollection(),
                columns: columns
            }, container);

            grid.startup();
        });
    </script>
</body>`
