### ISSUE TITLE
Using Grids and Stores examples have errors

### ISSUE THREAD

**Issue by 1758973467** [SitePen/dgrid#1391]
``require([`
    'dstore/RequestMemory',
    'dgrid/OnDemandGrid'
], function (RequestMemory, OnDemandGrid) {
    // Create an instance of OnDemandGrid referencing the store
    var grid = new OnDemandGrid({
        collection: new RequestMemory({ target: 'hof-batting.json' }),
        columns: {
            first: 'First Name',
            last: 'Last Name',
            totalG: 'Games Played'
        }
    }, 'grid');
    grid.startup();
});
``
in the page http://dgrid.io/tutorials/1.0/grids_and_stores/ , I find OnDemandGrid don't have startup method ,this caused misleading

**Comment by jsonn** [comment]
Which version are you using?

**Comment by 1758973467** [comment]
arcgis javascript api 4.4 ,it use dojo 1.12

**Comment by edhager** [comment]
Are you sure your modules are loading correctly?  

Below is the dgrid tutorial modified to use arcgis 4.4 API and it works fine.  `OnDemandList` inherits from `dojo/List` which has a startup method: https://github.com/edhager/dgrid/blob/master/List.js#L298-L311

You can download the hof-batting.json file [here](http://dgrid.io/tutorials/1.0/grids_and_stores/demo/hof-batting.json).

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>dgrid test</title>

	<link rel="stylesheet" href="https://js.arcgis.com/4.6/dojo/resources/dojo.css">
	<link rel="stylesheet" href="https://js.arcgis.com/4.6/dgrid/css/dgrid.css">
	<link rel="stylesheet" href="https://js.arcgis.com/4.6/dgrid/css/skins/claro.css">
	<style>
		.dgrid {
			margin: 2em;
		}

		body {
			padding-left: 20px;
			padding-right: 20px;
		}

		.half {
			/* used for displaying grids side-by-side */
			display: inline-block;
			margin-left: 2.5%;
			margin-right: 2.5%;
			width: 44%;
			vertical-align: top;
		}

		form {
			padding: 1em 2em;
		}
	</style>
	<script src="https://js.arcgis.com/4.4/"></script>
</head>
<body class="claro">
<div id="grid"></div>
<script>
require([
	'dstore/RequestMemory',
	'dgrid/OnDemandGrid'
], function (RequestMemory, OnDemandGrid) {
	// Create an instance of OnDemandGrid referencing the store
	var grid = new OnDemandGrid({
		collection: new RequestMemory({ target: 'hof-batting.json' }),
		columns: {
			first: 'First Name',
			last: 'Last Name',
			totalG: 'Games Played'
		}
	}, 'grid');

	grid.startup();
});
</script>
</body>
</html>
```
