### ISSUE TITLE
Empty Grid having Selector and Keyboard

### ISSUE THREAD

**Issue by sawantjayesh** [SitePen/dgrid#1392]
The empty Grid (no records) having Selector and Keyboard gets the "undefined" target.column @ line number 447 of Keyboard.js file, when up or down arrow button on keyboard is press after clicking the grid area.
Steps
1. Display Empty Grid with Selector and Keyboard
2. Click on Empty Grid area
3. Press Up or Down arrow button on keyboard
4. "undefined" target.column @ line number 447 of Keyboard.js file, which can't access the ".id"

**Comment by msssk** [comment]
I tested this with dgrid 1.3.1 and cannot reproduce. If you still encounter this problem please provide a test case and specify the dgrid version.
