### ISSUE TITLE
"dgrid-select" not firing on unrendered row selection

### ISSUE THREAD

**Issue by Jking-GIS** [SitePen/dgrid#1394]
I don't know if this is intended in the logic of dgrid, but for something I am currently implementing, I need to be able to listen for selection on rows that are paged out and unrendered in an ondemand grid. If the logic isn't there in the current dgrid implementation, is there something simple I could do to remedy this?

**Comment by msssk** [comment]
dgrid's `dgrid-select` event is a UI-driven event, and as you cannot select a row which has no UI, there is no `dgrid-select` triggered on un-rendered rows. To customize handling of "select all" you can extend the `selectAll` method.
