### ISSUE TITLE
dgrid unable to scroll to bottom when updating rows

### ISSUE THREAD

**Issue by weifhu0124** [SitePen/dgrid#1395]
I have it reproduced using the jsfiddle below. (Open with Microsoft Internet Explorer) 

https:/​/​jsfiddle.net/​pcuuvdpL/​13/​

Notice that if you change line 52 var item = this._store.get(2); to var item = this._store.get(25),​ the problem disappears. It appears that if you are updating rows outside of the current view,​ the dgrid cannot scroll to the bottom.

**Comment by dylans** [comment]
Is this an issue or not? Not sure why you'd close it without explanation?

**Comment by weifhu0124** [comment]
I noticed that the link is not working. I am trying to get the link fixed and reopen it afterwards.
