### ISSUE TITLE
"Defining Grid Structures" Tutorial has screenshot mismatch

### ISSUE THREAD

**Issue by shenningsgard** [SitePen/dgrid#1396]
In the "[Defining Grid Structures](http://dgrid.io/tutorials/1.0/defining_grid_structures/)" tutorial, under the "Defining Sub-rows" section, there is a viewable demo showing an example of how sub-rows can be used. Although it is not explicitly mentioned, because the same data set is used as in the previous "Parts of the Grid" section, it is implied that the "Defining Sub-rows" code should match the screenshots shown in the "Parts of the Grid" section. However, this is not the case:

"Parts of the Grid" screenshot:
![image](https://user-images.githubusercontent.com/4022650/29275727-addaa424-80d1-11e7-82bb-803db142283b.png)

"Defining Sub-rows" screenshot:
![dgrid_demo](https://user-images.githubusercontent.com/4022650/29275758-cc5b40e8-80d1-11e7-8b57-b91ff0838a53.png)

It would be nice if these matched, so that users may review the code and look at the previous screenshots to compare, since they use the same data set.

**Comment by edhager** [comment]
I pushed a fix to the website that makes the subrows demo look more like the screenshot.  It is not an exact match because the screenshot includes the column set definition which has not been added to the subrows demo.
