### ISSUE TITLE
The .ai file content significantly differs from Compilation

### ISSUE THREAD

**Issue by ElenaVi** [SitePen/dgrid#1399]
1. Draw a mapboard and add the following layers: 
NaturalEarth https://www.arcgis.com/home/item.html?id=4a70abf57bd5429aae2ce1302dc51051
USA Surface Water  https://www.arcgis.com/home/item.html?id=33509270162844e5ac323a5857c4fa2f
USA Wildland Fire Potential https://www.arcgis.com/home/item.html?id=4d63f7de557c4a69bab44c376c0d3565
World Urban Areas https://www.arcgis.com/home/item.html?id=2853306e11b2467ba0458bf667e1c584
USA Counties (Generalized) https://www.arcgis.com/home/item.html?id=7566e0221e5646f99ea249a197116605
USA Senate https://www.arcgis.com/home/item.html?id=873e1ae7fd7c4ce8a435638f831e0ca8 
USA Wildfire Activity https://www.arcgis.com/home/item.html?id=4d63f7de557c4a69bab44c376c0d3565
The Compilation will look like:
![image](https://user-images.githubusercontent.com/10720844/31819679-eeb7a098-b5c7-11e7-8b9f-a3d6cc8f5b3e.png)

2. Sync the map to .ai. The result will differes from Compilation:
 - labeling appears in .ai
 - the layers content is other
![image](https://user-images.githubusercontent.com/10720844/31819796-703bd742-b5c8-11e7-8619-30da351a32a7.png)

**Comment by dylans** [comment]
Given that this is an issue with the Esri API and .ai integration, I'm not sure what here is a specific problem with dgrid. I would report the issue directly to Esri. Thanks
