### ISSUE TITLE
exceptions not being logged

### ISSUE THREAD

**Issue by gerpres** [SitePen/dgrid#1400]
today I traced a strange behavior that I could track down to a custom insertRow-statement that caused an exception.
the insertRow-call has been triggered by updates on a tracked-collection.
I took me hours to figure out where the problem was, because the exception got somehow swallowed!?
any ideas? I think I had similar behavior with ancient dojo-versions. IMO it got better in the more recent versions.

I'm using the latest dgrid/dojo/dstore

**Comment by msssk** [comment]
Probably fixed in SitePen/dstore#187. If you continue to experience issues with dgrid please provide clear instructions to reproduce.
