### ISSUE TITLE
DGrid does not get value upon notification of change from custom dijit

### ISSUE THREAD

**Issue by matthiaspalmer** [SitePen/dgrid#1404]
The problem is simply that the dijit instance is not sent along in the callback and "this" is scoped to the event objects this, i.e. the dom element.
I forked and [fixed the problem at Bitbucket](https://bitbucket.org/metasolutions/dgrid/commits/50b2db2b883f25352316ecaf12d54c8fbaaf87e8?at=editupdatefix) as we needed a fix ASAP.

**Comment by dylans** [comment]
thanks @matthiaspalmer . Do you care to create a PR with the fix?

**Comment by matthiaspalmer** [comment]
Sure, here it is:
[https://github.com/SitePen/dgrid/pull/1405](https://github.com/SitePen/dgrid/pull/1405)

**Comment by dylans** [comment]
Thanks! Closed via 7f676bb.
