### ISSUE TITLE
this.grid inside column functions points to last grid created instead of current instance

### ISSUE THREAD

**Issue by schallm** [SitePen/dgrid#1410]
We are using the renderCell function of columns to create elements that allow users to edit items.  Once the edit is complete, we may need to refresh the grid that the data came from.  We do this by holding on to this.grid and refreshing.  

If you have multiple grids on the screen that are created from the created class, the this.grid is the last grid created from that class.  I have a fiddle created [here](https://jsfiddle.net/schallm/5ncvps14/) showing the issue.  Just click on the button and see that all buttons point to the second grid.

My column definition looks like the following:

```js
{
  label: "Actions",
  renderCell: function(object, value, node, options) {
    var grid = this.grid;
    var button = new Button({
      label: "Click Me",
      onClick: function() {
        alert("hello from grid: " + grid.id);
      }
    });
    button.placeAt(node).startup();
  }
}
```

I believe this is setup as part of the column configuration [here](https://github.com/SitePen/dgrid/blob/7f676bb0c1e16b8e60bbd96167ca27d6822b7b6d/Grid.js#L479)?

Can this be changed to be the correct instance of the grid?

**Comment by dylans** [comment]
I think the issue is that you have a singleton for the column definition, so the local variable grid is updated to point to the current grid. So you would need to do something to preserve the context. Alternatively (and perhaps better) would be to add the event listener using event delegation for all buttons across all grids external to the column definition.

JSFiddle's access to rawcdn is incredibly slow this morning which is preventing me from quickly providing a better working example, but hopefully this makes sense.

**Comment by schallm** [comment]
Looking at this a little further, I think it would actually be a better idea to inject the grid/this inside of Grid.js instead of List.js.  List's don't need the additional property as they don't have columns.  I also don't really like the property name of "parent" as it is ambiguous.  If we make the following change, the property could actually be named "grid" and only affect Grid and it's descendants...

```patch
Index: Grid.js
===================================================================
--- Grid.js	(revision 6021)
+++ Grid.js	(working copy)
@@ -99,6 +99,12 @@
 			}
 		},
 
+		renderArray: function (results, beforeNode, options) {
+			options = options || {};
+			options.grid = this;
+			return this.inherited(arguments);
+		},
+
 		createRowCells: function (tag, createCell, subRows, item, options) {
 			// summary:
 			//		Generates the grid for each row (used by renderHeader and and renderRow)
```

**Comment by edhager** [comment]
dgrid is not designed to share column definitions across grids. It is listed as a [limitation in the wiki.](https://github.com/SitePen/dgrid/blob/master/doc/usage/Limitations.md#reuse-of-column-definitions)

**Comment by edhager** [comment]
I pushed a change to commit 2d0e895d499a1386fa82dc924007e0ab1c9b1b27 that will cause the grid to produce a console warning if a column definition object is shared between grids.

**Comment by schallm** [comment]
Thanks for the pointer Ed.  I did not see that limitation.  Since I missed it, could I also suggest this be mentioned in the column definition [documentation ](https://github.com/SitePen/dgrid/blob/v1.2.1/doc/components/core-components/Grid.md#specifying-grid-columns)?

**Comment by edhager** [comment]
I added the column definition limitations to the `Grid` documentation: https://github.com/SitePen/dgrid/blob/master/doc/components/core-components/Grid.md#column-definition-limitations

**Comment by schallm** [comment]
That looks great.  Thanks!  

I don't know the actual/full reason for the limitation, but this could be closed unless dylans still wants to add the grid property to the options object for the next release.

**Comment by dylans** [comment]
@schallm After thinking about it more, it is probably safer, simpler, and cleaner to employ some sort of factory pattern if you want to reuse column definitions across dgrid instances without side effects. The factory pattern would return a column definition instance that would then get returned to be used in the constructor for each dgrid instance. This would probably be cleaner than trying to track down all the possible side effects of sharing a column definition across dgrid instances. I'm thinking the column definition should really be a separate instance per dgrid to prevent unintended side effects in your codebase.

**Comment by schallm** [comment]
@dylans Agreed.  We are now just passing a "new" columns array/object when calling new.  Rather than creating a new type with columns array "baked in".
