### ISSUE TITLE
dgrid/Grid updateSortArrow failing on IE caused by parentNode is null

### ISSUE THREAD

**Issue by rmadiwalid** [SitePen/dgrid#1413]
in dgrid/Grid class, when sorting on the dgrid on IE browser it's failing because of parentNode is null.
I can see that there was a change when migrated to dgrid 1.2.1.

```
if (this._lastSortedArrow) {
// Remove the sort classes from the parent node
domClass.remove(this._lastSortedArrow.parentNode, 'dgrid-sort-up dgrid-sort-down');
// Destroy the lastSortedArrow node
domConstruct.destroy(this._lastSortedArrow);
delete this._lastSortedArrow;
}
```
so I think we need a test on this line( in Grid.js class updateSortArrow method) to test that parentNode not null

```
domClass.remove(this._lastSortedArrow.parentNode

```

**Comment by msssk** [comment]
Closing this as it was fixed in #1430
