### ISSUE TITLE
memory leak in Keyboard.js

### ISSUE THREAD

**Issue by kalthoff** [SitePen/dgrid#1414]
In afterContentAdded() there are aspect.after() calls where the handles are never remov()ed. A few lines later other handles with on() are push()ed to grid._listeners grid._listeners.push(). What about push()ing the aspect.after handles there, too, to get them remove()d when the list is destroy()ed.

**Comment by dylans** [comment]
@kalthoff seems reasonable... do you have interest in creating a PR per the [contributing guidelines](https://github.com/SitePen/dgrid/blob/master/CONTRIBUTING.md)?

**Comment by edhager** [comment]
Landed in commit 8af200e89fade841f3864df28a1b24499268270a.
