### ISSUE TITLE
dgrid error parentNode is null

### ISSUE THREAD

**Issue by thejedi** [SitePen/dgrid#1416]
Recently we have upgraded our version of the API to version 1.2.1 and now get this error when clicking on the column header twice in a row when using a REST dstore.  

The error comes from line 222 in the OnDemandList.js 
if (self._previousScrollPosition && parentNode.offsetHeight) {
// Restore position after a refresh operation w/ keepScrollPosition but only
// if the rows have been inserted into the DOM.
self.scrollTo(self._previousScrollPosition);
delete self._previousScrollPosition;
}

The added check of parentNode.offsetHeight is returning null in some cases.  This check was not there is earlier versions and I am not sure why it is there now as it is not used inside the if.

**Comment by dylans** [comment]
Thanks for the regression report @thejedi . https://github.com/SitePen/dgrid/commit/2ae74378bff7ef0c46d82732a52e5f5cc55666ed is when it was added (2 years ago).

**Comment by edhager** [comment]
If a node has not been inserted into the DOM or is in a fragment that has not been inserted into the DOM, then `offsetHeight` will be zero.  `parentNode.offsetHeight` is checking if `parentNode` is in the DOM or not.  I added an additional check for `parentNode` in that `if` statement.

**Comment by thejedi** [comment]
@edhager the error was seen after clicking on the column header of a OnDemandGrid that was using a  rest dstore so the DOM has to be rendered.  Ideas?

**Comment by fkranenburg** [comment]
Setting `keepScrollPosition:false` prevents this issue. Waiting for a new release where this is fixed in.
