### ISSUE TITLE
Refreshing a grid sometimes causes a "this._editorFocusoutHandle is undefined error"

### ISSUE THREAD

**Issue by yohanleafheart** [SitePen/dgrid#1421]
I couldn't pinpoint exactly why it happens only in some cases, the grid that was breaking for me had 3 columns. A TextBox, a SimpleTextarea and one with a custom renderCell. And it is inside a Tab on a form.

The error happens on line [`dgrid/Editor.js:104`](https://github.com/SitePen/dgrid/blob/master/Editor.js)

`this._editorFocusoutHandle.pause();` fails because the handle is null. Wrapping it on a check solves the issue

**Comment by edhager** [comment]
@yohanleafheart Which version of dgrid are you using?  Could you give us a code sample that constructs the grid and demonstrates the problem?

**Comment by msssk** [comment]
Closing this issue as it lacks sufficient information to reproduce and has been inactive for a long time. If you continue to experience problems please open a new issue and provide a test case.
