### ISSUE TITLE
CDN for dgrid

### ISSUE THREAD

**Issue by denglerj** [SitePen/dgrid#1431]
Will there be a new CDN location for dgrid and dstore? The rawgit location is not operational any more.

**Comment by dylans** [comment]
We recommend using https://unpkg.com/ which works quite well.

**Comment by dylans** [comment]
unpkg should work for everything on npm, including dstore, you just need to work with its npm name which is dojo-dstore as someone beat us to that name. Details are at https://github.com/SitePen/dgrid/blob/master/doc/usage/npm.md .
