### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by fkranenburg** [SitePen/dgrid#1442]
The latest release is more than two years ago and there are a lot of issues still open. Is this project still maintained? It currently belongs to a critical part of our application and I would like to know if we need to worry 😊

**Comment by dylans** [comment]
@fkranenburg yes, we know it's been a while, and we've been pretty heads down on modern Dojo ( https://dojo.io/ ), but we were just talking about giving dgrid, dstore and Dojo 1.x a much needed round of updated releases, so that should happen relatively soon.

**Comment by fkranenburg** [comment]
That is very good to know! I personally can't wait until we can use modern Dojo but we have like 200+ custom Dojo 1.x widgets to convert first... So thanks for the quick reply @dylans !
