### ISSUE TITLE
CheckBox Editor does not work as expected in Safari

### ISSUE THREAD

**Issue by Mak006** [SitePen/dgrid#1458]
Using Safari 13, the checkbox is not clickable when editOn = click.  To reproduce this issue, navigate to the editor tests:

https://dgrid.io/js/dgrid/test/Editor.html

Select:
- Component Type = checkbox
- editon = click

Press the "Recreate Grid" button.  

You will notice that when selecting the text (true/false) on the rendered cell, the checkbox will show up.  However, if you try to toggle the checkbox, the grid is blurred and the value never changes.

**Comment by Mak006** [comment]
Is it also possible to have this fix applied to dgrid 0.3.16?

**Comment by msssk** [comment]
@Mak006 This fix is backported to the 0.3 branch in 65aad0b. Please test with the [dev-0.3](https://github.com/SitePen/dgrid/tree/dev-0.3) branch and let us know you encounter issues.

**Comment by msssk** [comment]
Released in [v0.3.21](https://github.com/SitePen/dgrid/releases/tag/v0.3.21), [v0.4.6](https://github.com/SitePen/dgrid/releases/tag/v0.4.6), and [v1.3.2](https://github.com/SitePen/dgrid/releases/tag/v1.3.2).
