### ISSUE TITLE
dgrid version 1.3.3 is breaking formatter function in dgrid

### ISSUE THREAD

**Issue by pnaqati** [SitePen/dgrid#1477]
columns:{
					col1: { selector: 'checkbox',  label:''} ,					
					id: { hidden :true ,unhidable: true},
					content:{label:'Photo',field:"_item",
						formatter: function(item){							
							if(!item){								 
								return;
							}else							
	                    	{ 		
								
								 return "<div id=\"productImageDiv\"><img src=\"/getProductImage/" + item.id +','+1+ "\"  width=\"100%\" height=\"100%\" style=\"vertical-align: middle\" alt="+ item.typeName +" /> </div> ";                                                     
	                    	}
	                    	}                       
	                },
				    description: {label:'Description', field:"description",formatter: function (value) {				    	
			             return '<div id="shopProductDescription">'+value+'</div>'; 
			        }} , 
			        sdescription: {label:'Description', field:"sdescription",formatter: function (value) {				    	
			             return '<div id="shopsProductDescription">'+value+'</div>'; 
			        }} , 			        
			        companyname: { label: 'Supplier',id: 'companyid',renderCell: contactSupplier}, 
					discount : {label:'Discount', field:"discount",formatter: function (value) { 
	                	 var num=number.format(value, {places:0});
	                	 if (num > 0 )
			             return '<div id="discountCurrency">'+num+'%<span>&nbsp;</span> </div>';
	                	 else
	                     return '<div id="discountCurrency"> </div>';	 
			        }} ,
			        cost : {label:'Price (CAD)', field:"cost",formatter: function (value) { 
	                	 var num=number.format(value, {places:2,pattern:'########.##'});	
			             return '<div id="productCurrency">$<span>&nbsp;</span>'+num+'</div>';
			        }} ,
			        
![Capture](https://user-images.githubusercontent.com/71416543/93411846-05750b80-f86a-11ea-8869-86f664c49d32.PNG)
![Capture](https://user-images.githubusercontent.com/71416543/93411895-1d4c8f80-f86a-11ea-9973-f088beb31338.PNG)

**Comment by pnaqati** [comment]
I changed formatter with renderCell function and this issue is resolved

**Comment by msssk** [comment]
This is a documented breaking change in [1.3.0](https://github.com/SitePen/dgrid/releases/tag/v1.3.0) aimed at making dgrid more secure by default and reducing the chance of accidental XSS. `formatter` can still be used with HTML strings by providing an object with an `html` property ([see documentation](https://github.com/SitePen/dgrid/blob/master/doc/components/core-components/Grid.md#column-definition-properties)).
