### ISSUE TITLE
refresh row

### ISSUE THREAD

**Issue by oyaaraas** [SitePen/dgrid#168]
In the grid, there are times when I want to update data in grid rows. There are two scenarios I can think of:

1) If I do a get or a query on a single row (i.e. by using JsonRestStore), the row should be updated according to the data returned from the server (as the grid-store is wrapped in a Observable store).

2) If I wan't to cancel some editing on a grid cell (discard dirty data on a row) I should be able to do this without reverting and refreshing the entire grid.

**Comment by kfranqueiro** [comment]
RE question 1:

You can use [`store.notify`](http://dojotoolkit.org/reference-guide/1.10/dojo/store/Observable.html#triggering-notification-events) in dojo/store (for dgrid 0.3) or [`store.emit`](https://github.com/SitePen/dstore/blob/v1.0.1/docs/Store.md#method-summary) in dstore (for dgrid 0.4) to make the store notify observers (such as dgrid instances) of updated data without actually modifying data in the store (or sending a write request to a server, in JsonRest's case).  If you're performing individual queries of your own and want to notify consumers of updates, this would be a likely course of action.

RE question 2:

There isn't really a direct API for this at the moment, but what you essentially need to do is clear the `grid.dirty` hash's entry for the specific item/field, then cause the row to re-render (potentially using the same tactic mentioned above).

The `grid.dirty` hash is keyed by items' identifiers, and each value is a hash containing any updated field values.  To remove one field from the dirty state, you'd `delete this.dirty[id][field]`; to remove an entire item from the dirty state, you'd just `delete this.dirty[id]`.
