### ISSUE TITLE
renderArray() does not clear old data

### ISSUE THREAD

**Issue by Leftium** [SitePen/dgrid#170]
`renderArray()` does not seem to [clear the old data](http://dojofoundation.org/packages/dgrid/tutorials/hello_dgrid/). For example, calling `renderArray([])` on a simple grid with existing rows does not clear the rows. Even  worse, if the passed array has data, the resulting rows seem to be a corrupted mix of the old and new rows.

**Work-around:** call `refresh()` before `renderArray()`

**Comment by vxpert** [comment]
how can we dynamically generate id of each row.... by default it is taking as 0,1,2,3.. i have to select the row dynmically so needed that

grid.select(grid.row(rowid));
