### ISSUE TITLE
Do not use for-in loops for arrays

### ISSUE THREAD

**Issue by priyajeet** [SitePen/dgrid#200]
Many places in the grid there are uses for for-in loops for iterating over arrays.
This is generally a bad practice. Should be using forEach or regular for loops.
If for-in has to be used, then there should be a check of hasOwnProperty()

**Comment by kfranqueiro** [comment]
I did a quick audit of the code in dgrid 0.4 and I'm pretty sure there are no spurious for...in cases left.
