### ISSUE TITLE
tree column plugin and Pagination ext

### ISSUE THREAD

**Issue by dredzone** [SitePen/dgrid#230]
Unable to use pagination extension with tree, error in gotoPage when attempts to remove nodes grid.row(r.substr(substrLen)).remove();

possible workaround:

var row = grid.row(r.substr(substrLen));
// tree plugin holds reference to children node via connected
// node will be removed by a plugin.  
if(row.element && !row.element.connected) {
        row.remove();
}

**Comment by kfranqueiro** [comment]
I'm not able to reproduce an error by removing rows; it's possible this was already resolved.

FWIW though, generally you'd want to actually remove items from an observable store and have the grid reflect the removal of the item, rather than removing the grid row directly.
