### ISSUE TITLE
new event dgrid-autoSaveOk  _StoreMixin.js editor.js

### ISSUE THREAD

**Issue by hvierendeels** [SitePen/dgrid#245]
To update some totals in another part of my application , i need to be informed when autoSave fields have been
successfully saved to store.

I achieved this by following updates:

editor.js:
  function setProperty(grid, cellElement, oldValue, value){
   ...
   column.autoSave && setTimeout(function(){ grid._trackError("autoSave"); }, 0);
   ...
 }//setProperty

_StoreMixin.js:
function autoSaveCallback(idObj){
        var mySelf=this;
	var dummy=listen.emit(this.domNode,"dgrid-autoSaveOk",{idObj:idObj,grid:mySelf,cancelable:true,bubbles:true});
}//autoSaveCallback

save: function() {
    ....
   function putter(id, dirtyObj) {
    ...
   //maybe it could also be interessant to pass on response,result from store
    return Deferred.when(store.put(object), function(storeResponse) {
						// Clear the item now that it's been confirmed updated
						delete dirty[id];
						delete updating[id];
                        return({id:id,dirtyObj:dirtyObj,storeResponse:storeResponse});
					});
    .....
  }//putter
 ....
}//save

_trackError: function(func){
			var result;
			var callBack=null;
			if(typeof func=="string"){if(func=='autoSave'){func='save';callBack=lang.hitch(this,autoSaveCallback);};func=lang.hitch(this,func);}			
			try{
				result = func();
			}catch(err){
				// report sync error
				emitError.call(this, err);
			}			
			// wrap in when call to handle reporting of potential async error
			//return Deferred.when(result, null, lang.hitch(this, emitError));//tshvr4
            return Deferred.when(result,callBack,lang.hitch(this,emitError));
}//_trackError

and in user code:
grid.on("dgrid-autoSaveOk",function(msg){
 var grid=msg.grid;
 var idObj=msg.idObj;
 var id=idObj.id;
 var dirtyObj=idObj.dirtyObj;
});

**Comment by kfranqueiro** [comment]
If you're looking to respond to when items are saved to the store, the proper way to do this would generally be through [`queryResults.observe`](http://dojotoolkit.org/reference-guide/1.10/dojo/store.html#observing-result-sets) (for dojo/store) or [`collection.on`](https://github.com/SitePen/dstore/blob/v1.0.1/docs/Collection.md#ontype-listener) (for dstore).

For future reference, it would be helpful if any code suggestions were at the very least [formatted](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks), or even pull-requested.  The code above was very hard to make heads or tails of.
