### ISSUE TITLE
Feature Request: Custom Sorting of a column

### ISSUE THREAD

**Issue by thiswayup** [SitePen/dgrid#276]
I've been looking at how to implement a custom sort on a Dgrid by passing it a enumerated object/hash. In the old dataGrid using he data api store, there was a comparatorMap property which you could set a custom sorter function in which I would create the custom sort.

It appears that there has been a recent change in the SimpleQueryEngine.js which could help but I think the "sort" property could be extended beyond the currentaccepted asc/desc to accept a function?

**Comment by karthik-srinivasan** [comment]
@kfranqueiro I'm trying to do what you have suggested. It works but not as expected. Details are here - http://stackoverflow.com/questions/32197919/dgrid-custom-sort-issue. It still does some kind of sorting even though I call preventDefault(). DO you have any suggestions?
