### ISSUE TITLE
Dgrid tree column expand/collapse with multiple on clicks (IE 8 Performance)

### ISSUE THREAD

**Issue by cgodfrey** [SitePen/dgrid#288]
I have a dgrid with a tree column and multple other columns where I am using dojo/on to handle click events

In IE Compatibility mode, we are seeing slow performance (error showing slow running script) when expanding or collapsing tree nodes

I created a gist https://gist.github.com/3750004 which demonstrates this issue

When I remove/coment all of the hierarchyTree.on handlers the performance is ok in IE 8

As a workaround, I created a general on handler and I check inside specifics for the column that is clicked - I'd prefer to have separate on hanlders as I would like to have links in the grid and be very specific about the handling

 hierarchyTree.on(".dgrid-content:click", function(evt) {

				        var cell = hierarchyTree.cell(evt);
				        var row = cell.row;
...

				    });

Do you have any suggestions on what I might be doing incorrectly or a better way to workaround this issue?

Thanks In Advance

**Comment by kfranqueiro** [comment]
It sounds like this is specifically referring to IE8 in compatibility mode (i.e. IE8 running in an older document mode).  As of 0.4, dgrid no longer supports IE < 8 modes, as the time involved in addressing issues has become prohibitively expensive in comparison to the dwindling number of IE < 8 users in the wild.
