### ISSUE TITLE
Difficulty to automate in Selenium

### ISSUE THREAD

**Issue by kdillon** [SitePen/dgrid#296]
Hi guys,

I'm using Selenium Webdriver to create tests for my company's product, and we are using dGrid as part of our application. The way webdriver usually works is that page elements are found either by id, xpath, or CSS path and then actions are applied to them. The problem here is that many of dGrid's functions are on the javascript object. So, if I want to use the full scope of dGrid's functions, I must keep track of the js object as well as the DOM object. Exacerbating this is that I only have direct access to javascript objects that are public to a browser's console, so any dGrids that are instantiated in onLoad or Require functions are inaccessible.

Selenium is one of the most widely-used web GUI automation tools, and I think that it would be a win for you guys if it was fully supported.

Here are a couple suggestions for making it work fully...

1. Have a valid path to the javascript var somewhere in the DOM that we can query at runtime. This might be a little flaky because one could change the var without updating the DOM and make the link invalid, and it might not solve the scoping issue.

2. Another possibility would be to register dGrid js objects in a known location, like what Dojo does with its Dijit repository.

Anyway - thanks for reading my post. Hope it helps!

-Kevin

**Comment by kfranqueiro** [comment]
We use [Intern](http://theintern.io/) for testing both dgrid and web applications that use it.  Intern (and more specifically, Leadfoot) makes use of Selenium (either locally or via a service such as BrowserStack) for its functional tests.

Functional tests operate through Selenium APIs to reference the DOM, as you said.  However, functional tests ideally aren't expected to directly interact with widget APIs; instead, they're expected to interact with the DOM which may in turn trigger widget logic.  If you absolutely need to reference an instance programmatically in a functional test, piggybacking off of `dijit/registry` by mixing in `DijitRegistry` is one option as Ben stated.  Another thing you might be able to do depending on your case is to use `require` to access modules that give you access to the dgrid instances in question.

On the other hand, unit tests deal directly with JavaScript APIs and so we expect to call APIs on dgrid instances in this case.  Generally we architect our applications such that it is always possible to reference any widget instances (whether dijit or dgrid) programmatically - for example, we don't rely on `dojo/parser` to parse the entire document body; instead, we only parse widget templates, which can assign child nodes and widgets to instance properties via `data-dojo-attach-point` attributes.

Hope this helps at least a bit.  For future reference, questions like this would be best asked via one of the [suggested free support options](https://github.com/SitePen/dgrid/tree/v0.4.0#getting-support).
