### ISSUE TITLE
OnDemandGrid (used with JsonRest) doen't retrieve data in Internet Exploder 8

### ISSUE THREAD

**Issue by naris** [SitePen/dgrid#315]
I have a simple OnDemandGrid used in conjunction with a JsonRest store. When I view the page using Internet Exploder 8, the grid is rendered but there is no data. However, when I view the same page using either Firefox 15 or Chrome 22 the data is there and everything works:

	<body class="claro">
		<h1>Hourly MTD Sales</h1>
		<div id="grid"></div>
		<script>
			var salesStore;

			require(["dojo/_base/declare", "dojo/store/JsonRest", "dgrid/OnDemandGrid", "dgrid/Selection", "dgrid/Keyboard", "dojo/domReady!"],
		       	function(declare, JsonRest, OnDemandGrid, Selection, Keyboard)
			{
			    var salesStore = new JsonRest({target:"http://<server>/cgi-bin/<script>"});

			    // create the columns
			    var gridColumns = [
				{ label: 'Country', field: 'cnty'},
				{ label: 'Division', field: 'div'}];

			    var grid = new (declare([OnDemandGrid, Selection, Keyboard]))({
				    store: salesStore,
			            columns:gridColumns 
			    }, "grid");
	    	});
		</script>
</body>

**Comment by kfranqueiro** [comment]
If I try using a Memory store with the data you specified (without the trailing comma), it works fine for me in IE8.

Given that it's unlikely this is a dgrid issue, if you have further difficulties, I'd suggest asking via one of the [recommended free support options](https://github.com/SitePen/dgrid/tree/v0.4.0#getting-support).
