### ISSUE TITLE
Feature Request: A layout (responsive!) system - like YUI's

### ISSUE THREAD

**Issue by ColemanTO** [SitePen/dgrid#330]
Layouts please!

[YUI Grids](http://yuilibrary.com/yui/docs/cssgrids/)

**Comment by goldsky** [comment]
I would like to raise this issue back to the surface.
It's true that dgrid is about displaying "data" in tabular view for certain purpose, but doesn't mean dgrid's Grid holds itself only in 1 (one) kind of common grid.
May be by some manipulation we can switch the header to the left side or right side (for RTL), like [some available plugins](http://exisweb.net/responsive-table-plugins-and-patterns).

**Comment by ColemanTO** [comment]
Bootstrap does almost everything I need for layout. 

dGrid probably doesn't need layout grids, but some Dojo-supported layout (Bootstrap?) would make Dojo _perfect_. For instance, Angular.js has good Bootstrap support.

**Comment by goldsky** [comment]
I am not sure we are at the same topic?

The idea is how to make dgrid fits well into a small device, eg smartphones.
Even TW Bootstrap doesn't support this.

**Comment by ColemanTO** [comment]
Oh, right - a responsive dGrid. Good idea!

I would still like to see some (responsive!) page layout grids in Dojo as well.
