### ISSUE TITLE
ColumnSet horizontal scrolling

### ISSUE THREAD

**Issue by ghost** [SitePen/dgrid#359]
In Safari, it is very hard to scroll the scrolling columns horizontally - most of the time the page tries going forward or back to the previous page, as the two finger scrolling does that in Safari.  Sometimes it does work fine - it's hard to know what the differences are.

The second grid in complex_column.html demonstrates this.

On an iPad, it seems very difficult to do any scrolling.  I have sometimes managed to vertically scroll, but never horizontally scroll.  Most of the time the surrounding page scrolls.  complex_columns.html is broken for me on iPads (data isn't shown), so I'm only testing on my app's grid (which is inside a dijit tabcontainer).

I hope these bugs can be fixed as I'm desperate to move off DataGrids - they've got their own set of problems!!!  Thanks!

**Comment by buggedcom** [comment]
This issue is still a problem. We are just converting all old `dojox/grid` to `dGrid` and are experiencing massive issues with this. The dojox/grid tables did not experience this at all, however the newly converted tables all do.

**Comment by dylans** [comment]
@buggedcom we would gladly review and land a pull request that solves this issue, or we would be happy to prioritize digging into under a [professional support plan](http://sitepen.com/support/). It's a complex enough problem that there's not an easy solution and it will take a fair amount of work to come up with the least bad option. :)

**Comment by buggedcom** [comment]
This isn't a perfect solution, but it partially fixes some of the issue. I am leaving here in case future readers of this issue need it.

Add this to stop back and fourth scrolling if y movement is detected.
```js
var pathClasses = function(event) {
    var path = [];
    var node = event.target || event.src;
    while(node != document.body) {
        path.push(node.className);
        node = node.parentNode;
    }
    return path;
};

On(window, "mousewheel", function(event) {
    var stop_event = false;
    var classes = pathClasses(event);
    for(var i=0, l=classes.length; i<l; i++) {
       if(classes[i].indexOf('dgrid') >= 0) {
           console.log('stopping event');
           stop_event = true;
           break;
       }
    }

    if(stop_event === true) {
        if(Math.abs(event.deltaY) < 1 || Math.abs(event.deltaX) > 20) {
            // stop event if they are only scrolling horizontally (deltaY < 1) or if they're really quickly swiping horizontally (as that isn't always caught in dgrids, it seems)
            event.preventDefault();
        }
    }
});

```

In dgrid/ColumnSet.js around line 160, after :
```js
// only respond to horizontal movement
listener.call(null, grid, node, deltaX);
```
add:
```js
if (Math.abs(event.deltaY) < 1) {
     // no vertical movement so safe to stop event here to help reduce
     // chance of back/forward navigation swipes being caught by the window
     event.preventDefault();
}
```
