### ISSUE TITLE
Styling Rows depends on a column value

### ISSUE THREAD

**Issue by itdpong** [SitePen/dgrid#380]
the following in my data store.

var data = [
    {order: 1, name:"A", deleted:"Y"},
    {order: 2, name:"B", deleted:"N"},
    {order: 3, name:"C", deleted:"Y"},
    {order: 4, name:"D", deleted:"N"},
];

What should I do if I want to change the row's background color to red if the deleted value is 'Y' only???

**Comment by jvegaseg** [comment]
It does not work if you use Tree mixin!!!

**Comment by kfranqueiro** [comment]
If you are having issues with this, please ask a question on StackOverflow, IRC, or the mailing list (with enough code for someone to reproduce the issue and help), [as suggested in the README](https://github.com/SitePen/dgrid#getting-support).

**Comment by jvegaseg** [comment]
I have just done: http://stackoverflow.com/questions/30359894/how-to-do-an-aspect-after-of-renderrow-method-using-dgrid-with-tree-extension

Thanks in advance for your help.
