### ISSUE TITLE
Grid with Tree Column and shouldExpand = message: "This deferred has already been resolved"

### ISSUE THREAD

**Issue by cgodfrey** [SitePen/dgrid#399]
I have been working with an older version of dgrid (0.3.1) and recently upgraded (0.3.5-dev) zip file

I have a dgrid with a tree column, the tree column has a shouldExpand function defined
Looks something like this (I have an indicator in the data whether or not the row should be expanded. 

shouldHierarchyExpand: function (row, level, previouslyExpanded) {
                if (level == 0) {
                    return true;
                }
                if (row.data.initExpand) {
                    return true;
                }
                    return false;
            },

After upgrading my version of dgrid - I now see console errors "This deferred has already been resolved" - every time I expand a tree item. If I remove the shouldExpand definition from my tree column - this console error goes away - not sure what I could be doing wrong or if there is an issue with the tree column, shouldExpand

....
 window.hierarchyTree = declare([Grid, ColumnSet, DijitRegistry, Selection])({
                id: "hierarchyTree",
                store: emptyhierarchyStore,
                query: { EmployeeID: ModelData.EmployeeId },
                selectionMode: "single",
                columnSets: [
                    [
                        { EmployeeName: Tree({ label: 'Team Members', sortable: false, shouldExpand: pagesSalesHierarchy.shouldHierarchyExpand, renderCell: pagesSalesHierarchy.renderTeamMember }) }
                    ],
                    [
                        [
                            { label: 'FYTD' + ModelData.SalesRptHeader.CurrentYear, field: 'CurrentFYYTD', sortable: false, renderCell: pagesSalesHierarchy.renderSalesDetailsFY2Link },
                            { label: 'FYTD' + ModelData.SalesRptHeader.PreviousYear, field: 'PrevFYYTD', sortable: false, renderCell: pagesSalesHierarchy.renderSalesDetailsFY1Link },
                            { label: '% Growth', field: 'PCTGrowth', sortable: false, formatter: common.formatPercent },
                            { label: 'Growth', field: 'DollarGrowth', sortable: false, formatter: common.formatCurrency },
                            { label: 'FYTD' + ModelData.SalesRptHeader.CurrentYear + ' Pending', field: 'CurrentPending', sortable: false, renderCell: pagesSalesHierarchy.renderPendingFY2Link },
                            { label: 'FYTD' + ModelData.SalesRptHeader.PreviousYear + ' Pending', field: 'PrevPending', sortable: false, renderCell: pagesSalesHierarchy.renderPendingFY1Link },
                            { label: 'FYTD' + ModelData.SalesRptHeader.CurrentYear + ' Trans + Pending', field: 'CurrentFYTDTransPending', sortable: false, formatter: common.formatCurrency },
                            { label: 'FYTD' + ModelData.SalesRptHeader.PreviousYear + ' Trans + Pending', field: 'PriorFYTDTransPending', sortable: false, formatter: common.formatCurrency },
                            { label: '% Growth Trans + Pending', field: 'PCTGrowthTransPending', sortable: false, formatter: common.formatPercent },
                            { label: 'Growth Trans + Pending', field: 'TransPendingDollarGrowth', sortable: false, formatter: common.formatCurrency },
                            { label: 'YTD Summary (TTQ)', field: 'EmployeeID', sortable: false, renderCell: pagesSalesHierarchy.renderYTDLink },
                            { label: 'Market & Territory by Commission Category', field: 'ManagerEmployeeID', sortable: false, renderCell: pagesSalesHierarchy.renderByCCLink },
                            { label: 'Market & Territory NO Commission Category', field: 'HasChildren', sortable: false, renderCell: pagesSalesHierarchy.renderNoCCLink }
                        ]
                    ]
                ]
            });

Thanks In Advance

**Comment by SamarthUpenn** [comment]
How to expand a particular row programmatically?
