### ISSUE TITLE
Instead of clicking + on the grid header to show hider menu node, i want to show by clicking of some image which outside the dgrid

### ISSUE THREAD

**Issue by Jasmine2013** [SitePen/dgrid#410]
Instead of clicking "+ "on the grid header to show hider menu node, i want to show columnhider menu  by clicking of some image which is outside the dgrid. so i have written like:

onclick of my image:

if(_hiderMenuOpened === true){
hiderMenuNode.style.display = "";
}
else{
hiderMenuNode.style.display ="none";
}

i want the following things:
1) The columnhider menu should move towards my images(should not be at the top of grid header: 

As the columnhider menu is placed on the grid's dom node in ColumnHider.js.. i could not move towards my image 

put(this.domNode, hiderMenuNode); in ColumnHider.js

2) Now if i click outside of columnhider menu, the menu is not closing..
How to close from outside if i click?

**Comment by kfranqueiro** [comment]
While we have considered possibly separating the ColumnHider APIs for hiding/showing columns and the menu functionality to two separate modules, I'm not sure we'd take it as far as accounting for separation of the menu from the grid entirely.

You could ostensibly write a custom widget yourself that iterates over the `grid.columns` hash and constructs a menu from the objects inside, then calls `grid.toggleColumnHiddenState(columnId, hidden)` (exposed by the ColumnHider extension) as appropriate.  You can easily hide ColumnHider's own toggle node via CSS by setting `display: none` for `.dgrid-hider-toggle`.
