### ISSUE TITLE
grid.refresh() make memory of explorer grow 

### ISSUE THREAD

**Issue by cwocwo** [SitePen/dgrid#435]
I test it on IE8, firefox18.0.2, 
I use  "dgrid/test/OnDemand.html" , change rows in "data/base.js" to 1000, then call 
```javascript
window.grid.refresh();
```

**Comment by kfranqueiro** [comment]
I have not been able to reproduce any meaningful increase in memory following these steps.  Usually I see memory increase a negligible amount at best and then lower a second later.  I've tried with both 0.3.17 and 0.4.
