### ISSUE TITLE
Error with Drag N Drop

### ISSUE THREAD

**Issue by mddev22** [SitePen/dgrid#484]
I experienced occasional error with dgrid using tree column pluggin and dnd extensions. 

Sometimes when rows are dragged, an exception is reported with  "TypeError: Cannot call method cloneNode of undefined" in  dnd/Avatar.js,

Unfortunately, I can't provide an example to demonstrate this, as  I can't make it happen in a repeatable manner.  

On the occasions when the error occurred, I noticed the 'id' values in grid.selection and '_selectedNodes' differed in function DnD.js/getSelectedNodes() . Hence the 'undefined' value is pushed into the 't' array (as per code section extracted below), causing issues elsewhere.  

for(id in this.grid.selection){
     t.push(this._selectedNodes[id]);
}

I wrapped 'if (this._selectedNodes[id])' test around  't.push'  and I have not encountered the issue since.  I understand this issue can't be definitely resolved without a repeatable demonstration, but perhaps  that test could be included in master code.

**Comment by kfranqueiro** [comment]
I'm closing this given our recent inability to reproduce the issue.  If someone here does manage to reproduce it reliably, please let us know.
