### ISSUE TITLE
'set' function in subRow definition can be ignored

### ISSUE THREAD

**Issue by nikkikom** [SitePen/dgrid#489]
If the grid uses subrows, the 'set' functions is ignored for all subrows but the last one.

The DGrid calls _configColumns() for each subrow. The _StoreMixin clears this._columnsWithSet in its _configColumns(). Thus only the last subrow's 'set' functions finally stored in this._columnsWithSet.

**Comment by kfranqueiro** [comment]
This was fixed back in late March 2013 primarily via https://github.com/SitePen/dgrid/commit/0bf494891aaa3c4dda06147b6f923acf25a5a016.  I didn't notice at the time that this ticket was accidentaly left open.  Sorry!
