### ISSUE TITLE
ColumnReorder is broken in dgrid 0.3.7

### ISSUE THREAD

**Issue by lixopmstp** [SitePen/dgrid#525]
When I try to swap columns the grid headers disappear.  Observed in Firefox 20 (Firebug shows a "too much recursion" error) and MSIE 9 with dojo 1.8.1.  Works fine in dgrid 0.3.6.
Note I'm using the following extensions and plugins:

        "dgrid/Grid", 
        "dgrid/selector", 
        "dgrid/Keyboard", 
        "dgrid/Selection", 
        "dgrid/extensions/Pagination",
        "dgrid/extensions/ColumnReorder",
        "dgrid/extensions/ColumnResizer", 
        "dgrid/extensions/ColumnHider",

**Comment by kfranqueiro** [comment]
Sorry this issue ended up left open.  Yes, I believe this was fixed in 0.3.7.  Furthermore, in 0.4, there is no longer a `disabled` property for selector columns since it is redundant of `Selection#allowSelect`.
