### ISSUE TITLE
noDataMessage is displayed in multiple rows

### ISSUE THREAD

**Issue by Housik** [SitePen/dgrid#546]
**OnDemandGrid, v0.3.7**
I'm having 2 grids: when row is selected in the first one, it calls 

```javascript
grid.set("query", {matchIdentityActivityFilter: idIdentityActivityFilter});
```
on the second grid (JsonRest store). If I'm fast and select another row at the first grid, but previous query request (or requests) is not resolved yet and it has no data, sometimes noDataMessage is displayed in multiple rows, after multiple async queries are resolved. Screenshot is attached ("žádné údaje" is noDataMessage).

![FireShot Screen Capture 036 - ZF2 Skeleton aplikace - admin_internetclient_info_localhost](https://f.cloud.github.com/assets/1431749/395300/6d8f7c9e-a7f7-11e2-93e7-6c021d0e0cd2.jpg)

It would be nice to have a method (or option) to discard any previous async requests made by `grid.query()` calls.

**Comment by kfranqueiro** [comment]
This should be resolved along with #542.

Regarding better management/canceling of async requests, that's definitely something on our minds for the next major release (maybe sooner if the changes aren't too invasive).
