### ISSUE TITLE
ondemandlist problems with small page len and async loading

### ISSUE THREAD

**Issue by lemonhub** [SitePen/dgrid#553]
i am loading from a jsonrest store with a pagelength of 1. yes only 1 item a time is loaded.
ondemandlist only renders 2 rows.

problem is that after an async load the below preload is not the same as grid.preload anymore.
i did not completely understand the logic by with the preloads are adressed.
however this fixed the bug:

line 527:
						// make sure we have covered the visible area
						grid.preload = below; // <-- inserted
						grid._processScroll();
						return rows;

pls let me know if i fixed the bug correctly.
you can easily reproduce the bug by setting both minRowsPerPage and maxRowsPerPage to 1
and try to render from a jsonreststore.

thank you!

**Comment by kfranqueiro** [comment]
Given no further activity on this ticket, I'm closing it, as it is likely to have been resolved in later versions of 0.3.x as well as 0.4.
