### ISSUE TITLE
ColumnReorder issues in simple grid

### ISSUE THREAD

**Issue by JCVoogden** [SitePen/dgrid#556]
There seems to be an issue with the ColumnReorder extension when using it on a simple grid structure (no column sets, no sub rows).

Tracing the code, the extension improperly use "columSets" as the structure property (there is no column set), but the problem is more complex than that since the subRows indices are false either.

Stack trace : 
Uncaught TypeError: Cannot read property '1' of undefined ColumnReorder.js:19
getMatchingSubRow ColumnReorder.js:19
declare.onDropInternal ColumnReorder.js:53
declare.onDrop Source.js:329
declare.onDndDrop Source.js:297
(anonymous function) lang.js:373
target.(anonymous function).dispatcher aspect.js:91
on.emit on.js:274
on.emit on.js:321
Evented.emit Evented.js:31
publish topic.js:25
declare.onMouseUp Manager.js:151
(anonymous function) lang.js:373

**Comment by kasiwal123** [comment]
The columnReorder extension reorders only the column headers and not the actual data in the grid. I am using tree, columnResizer and compoundColumns extensions along with columnReorder. Any particular reason why this could be happening?

I spent sometime debugging and couldn't find the cause. The subRows array in grid is getting updated as per the reorder but it doesn't reflect in grid.Columns.
Any help will be appreciated.

**Comment by kfranqueiro** [comment]
@kasiwal123, you already reported this under #1117, but we can't diagnose it without a test case.  You don't need to cross-post issues.
