### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by dylans** [SitePen/dgrid#584]
We should add a CONTRIBUTING.md file (similar to https://github.com/kitsonk/dojo2-boilerplate-package/blob/master/CONTRIBUTING.md ) to hopefully encourage pull requests to have a CLA on file before submitting them.

**Comment by kfranqueiro** [comment]
dgrid 0.4 has a [CONTRIBUTING.md](https://github.com/SitePen/dgrid/blob/v0.4.0/CONTRIBUTING.md).  (Thanks @msssk!)
