### ISSUE TITLE
Stylus versions of Skins

### ISSUE THREAD

**Issue by dylans** [SitePen/dgrid#607]
Consider adding Stylus versions of the dgrid skins. While they are quite simple, it would be nice for projects choosing to use Style and Dijit to manage styles more cleanly.

**Comment by kfranqueiro** [comment]
I've converted dgrid's skins to use stylus in https://github.com/SitePen/dgrid/commit/9fcdac2f6e67d6b538ad6a987160c36896dd576d.  (The structural styles are also organized using Stylus now.)

I've created variables to cover as much of the common needs of skins as possible, so if you look at e.g. the Claro skin, you'll see that it is now simply a series of variable definitions, then an import of `skin.styl`, which is responsible for creating styles from those variables.

I've also created a Gruntfile (in https://github.com/SitePen/dgrid/commit/2bc176b95775e708dd5b2205a90f0f2b3c10a68e) with tasks to build/watch stylus files and clean CSS files.

You can find basic information about the new Stylus skins in the new [Customizing Skins](https://github.com/SitePen/dgrid/blob/2052f12804b495a9a577257a5cdb730568926ab5/doc/usage/Customizing-Skins.md) documentation page.
