### ISSUE TITLE
Grid refresh resets horizontal scroll

### ISSUE THREAD

**Issue by marzetas** [SitePen/dgrid#666]
I'm having an issue with the horizontal scroll in dgrid, and I was hoping someone could shed some light on it. 

I have a dgrid where the width of the columns is wider than the grid, so it ends up having a horizontal scroll (obviously). The moment the contents of the grid are refreshed, that horizontal scroll is lost (scrollLeft:0). 

I've seen that the refresh method in List.js sets this value to 0 (this.scrollTo({ x: 0, y: 0 });), but removing this line doesn't seem to make any difference. 

This is quite annoying, especially if the number of columns is big and you need to check the values of the column you've used for sorting (for example) if it falls outside the visible contents.

**Comment by billdwhite** [comment]
keepScrollPosition setting in dgrid may fix this?

**Comment by quilesbaker** [comment]
+1 on keepScrollPosition. Only if you use dgrid properly you could call refresh({keepScrollPosition: true}).

**Comment by kfranqueiro** [comment]
Yes, setting `keepScrollPosition` on the instance preserves both x and y coordinates.

Setting on the instance (as opposed to passing to `refresh`) would be necessary to accommodate user interaction cases such as changing sort order via header cell clicks.
