### ISSUE TITLE
Double click to edit cell occasionally fails silently

### ISSUE THREAD

**Issue by andygup** [SitePen/dgrid#689]
Sometimes double click to edit any cells fails to work. No errors are thrown. Reloading the entire page resolves. Certainly not the desired behavior. Unable to reproduce consistently. This behavior has been seen on latest versions of Firefox and Chrome as well as IE 9.

columnArr[i] = editor({
  label:key.toString(),
  field:key.toString(),
  hidden: false,
  editor:"text",
  editOn:"dblclick"
});

**Comment by davewilton** [comment]
I got this error when having repeat id's too
