### ISSUE TITLE
Space and enter keys dont work correctly with the selector extension

### ISSUE THREAD

**Issue by swapnilghan** [SitePen/dgrid#731]
I am using dgrid/selector plugin. when I try to select/deselect columns using keyboard keys space or enter the column doesn't change the selection state.

after debugging this problem, it looks like "onSelect" function from selector.js is called twice when space or enter key is used. 

following line adds the event listeners

listeners.push(grid.on(".dgrid-selector:click,.dgrid-selector:keydown", onSelect));

but when user hits the space/enter, I guess both click and keydown events are emitted and the onSelect method is called twice and column goes back to the original state.

**Comment by gerpres** [comment]
same problem for me (chrome, dojo 1.10.4, dgrid 0.3.16)  - .dgrid-selector:click and .dgrid-keydown are fired for the selector-checkbox when hitting the [space]-key causing the row to get selected and being immediately deselected.
store is set up correctly

**Comment by kfranqueiro** [comment]
Hm. Trying again, I can reproduce this if I click directly on a selector checkbox and then hit space, but not if I focus the cell itself and hit space.

**Comment by gerpres** [comment]
the column is configured like
 
```javascript
selector({id:'selector',unhidable:true,tabIndex:0})
```

I'm selecting the checkbox by tabbing into it and then hit [space]

**Comment by rushil-patel** [comment]
I'm seeing a related issue but In this case I'm not using the selector plugin-in. I'm listening for the "dgrid-sort" event which seems to be called twice when "enter" or "space is clicked. It looks like "click" and "keydown" events are fired when "enter" or "space" key is pressed. 

This is my listener that appears to be called twice:
`grid.on("dgrid-sort", function (evt) {.....}`
