### ISSUE TITLE
tree.js: getChildren-method defined not in model but in view

### ISSUE THREAD

**Issue by jankel** [SitePen/dgrid#780]
My situation
-------------
In my current project, I'm using lots of ("ObservableCached")-JsonRest-stores as API for viewing and manipulating serverside database-tables.

As long as I'm using one dgrid with one store, there are no problems with displaying updates,  made by users to the underlying stores: the different dgrids on multiple LayoutContainer-pages, observing their store-query-results, are updated as expected.

getChildren definition in model: a limitation?
------------------------------------
Now I also wanted to have tree-grids in my app. While defining the method "getChildren" on store-level as it is actually implemented in current tree-column-extension (https://github.com/SitePen/dgrid/wiki/tree#store-considerations), I can't use the same store (responsible for one serverside  db-table) for multiple tree-dgrids with the same "mainlevel"-store but different "getChildren"-methods.

My first bad solution
------------------
My first approach, avoiding this problem by creating multiple "mainlevel"-stores with the same serverside-target for every tree-featured-dgrid, resulted in the problem, that obviously multiple ("ObservableCached")-JsonRest-stores having the same "mainlevel" must be synchronised manually if it comes to mainlevel-store-changes - what seems to be a quite uncomfortable idea.

Let the view combine two stores loosely
----------------------------------------------
Would it be quite wrong to expect the "joining"-method (getChildren) between a mainlevel-store and a sublevel-store to be an attribute of the view (for example defined as an attribute of the tree-column-definition), instead of statically define only one children-store per main-store?

Let me post my solution, that gave me more flexibility:

```javascript
diff --git a/dgrid/tree.js b/dgrid/tree.js
index 16c12ed..30d281d 100644
--- a/dgrid/tree.js
+++ b/dgrid/tree.js
@@ -205,6 +205,10 @@ function tree(column){
                                        container = rowElement.connected = put('div.dgrid-tree-container');//put(rowElement, '+...
                                        preloadNode = target.preloadNode = put(rowElement, '+', container, 'div.dgrid-preload');
                                        var query = function(options){
+                                                if ("dummy_flag_new_dgrid_tree_feature" && column.getChildren){
+                                                        return column.getChildren.call(grid, row.data, options);
+                                                }
+
                                                return grid.store.getChildren(row.data, options);
                                        };
                                        if(column.allowDuplicates){

```

After that, one could define a column in a tree-dgrid like in this incomplete javascript-snippet:

```javascript

        columns: [
            tree({
                field: "article_id",
                label: "Article",
                getChildren: function(parent, options) {
                    // return the deferred returned by a sublevel-store-query
                }
            }),

```

Actually this could be a quite simple addition to tree.js, that would definitely make my day! :-) BTW I'm working with dgrid v0.3.12.

Are there any other ideas, that I haven't thought of? Thanks in advance, Jan

**Comment by kfranqueiro** [comment]
If you're basically saying that you have multiple grids reading the same data but with different definitions of what "children" are, I wonder if it would be possible for you to create delegates of the store instance (i.e. with `lang.delegate`), each having its own overridden `getChildren` implementation.

Another idea might be to have one central store that you manually observe, then relay those changes to the other stores (via [`notify`](http://dojotoolkit.org/reference-guide/1.10/dojo/store/Observable.html#triggering-notification-events) for dojo/store or [`emit`](https://github.com/SitePen/dstore/blob/v1.0.1/docs/Store.md#method-summary) for dstore).  I suppose this might be akin to the first solution you tried though.

I apologize for getting to this question ridiculously late after the fact.  If you have more questions about your use of dgrid, I'd suggest trying one of dgrid's [recommended free support options](https://github.com/SitePen/dgrid/tree/v0.4.0#getting-support).
