### ISSUE TITLE
preloadNode.parentNode is null intermitantly

### ISSUE THREAD

**Issue by gibbsonn** [SitePen/dgrid#818]
I'm getting a error in OnDemandList.renderQuery in the callback from renderArray, the specific line which is causing the issue is commented below, for some reason the parentNode provided to _getFirstRowSibling call is null, this causes _getFirstRowSibling to cause a js exception as it tries to get the lastChild property from a null value

Unfortunatly this error is intermitant and I've not been able to reliably reproduce yet. All I can say is that the times I've detected this error it's been on this line so I assume that means that no results were being returned because it's only run when total =0. 

A few questions
- what is the purpose of the preloadNode and how is it used when loading records?
- have you seen this error before at all?
- If I can't find the cause, any suggestions for any hacks I could do to bypass this issue until I can get it fixed?
  
  ```
  if(typeof results === "undefined"){
      // Synchronous error occurred (but was caught by _trackError)
      errback();
      return;
  }
  
  // Render the result set
  Deferred.when(self.renderArray(results, preloadNode, options), function(trs){
      var total = typeof results.total === "undefined" ?
          results.length : results.total;
      return Deferred.when(total, function(total){
          var trCount = trs.length,
              parentNode = preloadNode.parentNode,
              noDataNode = self.noDataNode;
  
          put(loadingNode, "!");
          if(!("queryLevel" in options)){
              self._total = total;
          }
          // now we need to adjust the height and total count based on the first result set
          if(total === 0){
              if(noDataNode){
                  put(noDataNode, "!");
                  delete self.noDataNode;
              }
              self.noDataNode = noDataNode = put("div.dgrid-no-data");
              parentNode.insertBefore(noDataNode, self._getFirstRowSibling(parentNode)); // <<<<<<<<<-- parentNode is null
              noDataNode.innerHTML = self.noDataMessage;
          }
  ```

**Comment by pukhrajbal** [comment]
Reproduced same error with pagination extension turned on when store had 0 records. Turning pagination off removed error.

**Comment by kfranqueiro** [comment]
If the error you reproduced is the same one as reported initially in this issue (which references `OnDemandList`), the problem could be due to mixing `OnDemandList` and `Pagination` together, which is incorrect, [as mentioned in the docs](https://github.com/SitePen/dgrid/blob/v0.4.0/doc/components/extensions/Pagination.md#pagination).

**Comment by pukhrajbal** [comment]
Thank you for clarification. Combo of onDemand and Paging was causing error for me.

**Comment by danielkurtz** [comment]
I am able to reproduce this issue using a RequestMemory store and an OnDemandGrid programmatically.  If I switch to a Memory store (commented out below), I don't get the error.  I'm using Dojo 1.10.4, dgrid 0.4, and dstore 1.1.0.  In this case, the JSON file simply contains "[]".  In the OnDemandList.renderQuery, total === 0 and parentNode is null.

	
		<script>
			require([
				"dojo/dom-construct",
				"dgrid/OnDemandGrid",
				"dstore/RequestMemory",
				"dstore/Memory",
		     	"dojo/domReady!"], function(
		     	domConstruct,
		     	OnDemandGrid,
		     	RequestMemory,
		     	Memory
			){
			
				var grid = new OnDemandGrid({
					collection: RequestMemory( { target: "./dgridTestData.json" } )
					//collection: Memory( { data: [] } )
        		}, domConstruct.create("div"));
        		
        		var columns = '[ { "field": "firstName", "label": "First Name" }, { "field": "lastName", "label": "Last Name" } ]';
				grid.set("columns", JSON.parse(columns));
        		
        		domConstruct.place(grid.domNode, document.body);
        		grid.startup();
        		
        		grid.refresh();
			
			});
		</script>
