### ISSUE TITLE
dgrid header displayed on multiple lines instead of showing up the horizontal scrollbar

### ISSUE THREAD

**Issue by uozznezz** [SitePen/dgrid#843]
Hello,

I am experimenting a Nodejs project using dojo dgrid 0.3.12-dev on the client side.
The dgrid works fine when loaded as a stand-alone view, composed of a border container with a button toolbar in the top region and the grid itself in the center:
http://localhost:3000/otn-ws-webapp/wdm/pages/templateGrid/list.html

However, when the above page is loaded in the top region of another border container having a tab container in the center, the grid header wraps along multiple rows, instead of showing up a single header row with an horizontal scrollbar:
http://localhost:3000/otn-ws-webapp/wdm/pages/templateGrid/listWithView360.html

You see the code here:
https://github.com/uozznezz/asonWebClient

Download the code and run Nodejs:

> node app.js

Then open the following URL in the browser:
http://localhost:3000/otn-ws-webapp/wdm/pages/templateGrid/list.html -> dgrid ok
http://localhost:3000/otn-ws-webapp/wdm/pages/templateGrid/listWithView360.html -> dgrid ko

Thanks
Giacomo

**Comment by AndrewHenryOttawa** [comment]
Thanks Ken. I'll be looking out for it. Had too much on my plate myself.

**Comment by AndrewHenryOttawa** [comment]
Ken, 

0.3.17 resolved our bug. Thanks.
