### ISSUE TITLE
Rows disappear on OnDemandGrid when notifying underlying data

### ISSUE THREAD

**Issue by rhpijnacker** [SitePen/dgrid#859]
See test program: https://gist.github.com/rhpijnacker/9249778.
Way to reproduce the problem:

* Load program
* Select the top row. This notifies the underlying data in the store.
One thing to note here is that the ordering of the list changes, which is unexpected.

* Keep selecting the top row until rows 24 and 25 are at the top. Selecting these two causes them to disappear completely.

**Comment by kfranqueiro** [comment]
A warning was added to later 0.3.x versions to account for this edge case, and it is no longer an issue in 0.4.
