### ISSUE TITLE
Paramter to disable scrollbar

### ISSUE THREAD

**Issue by ivarconr** [SitePen/dgrid#89]
I manged to style away the scrollbar in the grid, but I would like this to be an optional paramter you can use when creating the grid. e.g: "disableScrollBar: true".

**Comment by jsr6720** [comment]
I know this is closed, but you can also add class "dgrid-autoheight" to get the auto height effect
https://github.com/SitePen/dgrid/blob/master/css/dgrid.css#L127

**Comment by gladenko** [comment]
I have big problem with render in windows a header and column are not aligned the scrollbar is a problem if there is lot of row. i don't resolve with css becouse if i add row the grid appear.

How resolve this big big big problem

**Comment by dylans** [comment]
@gladenko how many rows is a lot of rows in your case? I wonder if you are reaching the maximum height within various browsers?
